<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output version="1.0" omit-xml-declaration="yes" encoding="UTF-8" indent="yes"/>
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
  <xsl:template match="Book[@id='book_1']/@desc" ><xsl:attribute name="desc">{=Sa9X6NnL}A scroll filled with techniques and diagrams of swordsmanship in the Kage-ryū style. Developed in 1438 by Aisu Hisatada, Kage-ryū has established itself as one of the three major origins for the evolution of sword based-martial arts.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_2']/@desc" ><xsl:attribute name="desc">{=LZgp1XsH}A scroll detailing the techniques of the Shintou-ryū style, a school of swordsmanship founded by Iizasa Ienao and now counted among the three main origins of the martial arts.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_3']/@desc" ><xsl:attribute name="desc">{=AdaDocYA}A scroll describing the Shinkage-ryū style swordsmanship style, a school established by Kamiizumi Nobutsuna as a derivative of the Kage-ryū style.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_4']/@desc" ><xsl:attribute name="desc">{=fSHsjzwC}This scroll summarises the swordsmanship techniques of the Ten-ryū style, a martial arts school that also includes polearms, throwing and jūjutsu.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_5']/@desc" ><xsl:attribute name="desc">{=43Qyl6a1}A scroll that describes the techniques of the Toda-ryū style of swordsmanship, a school founded by Itou Kagehisa after visiting Kanemaki Michimune, a master of the Nakajou-ryū style</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_6']/@desc" ><xsl:attribute name="desc">{=Q4dwDikE}This scroll contains the teachings of Marume Nagayoshi, a disciple of the Shintou-ryū style and founder of the Marumeshinkage-ryū school of swordsmanship.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_7']/@desc" ><xsl:attribute name="desc">{=YDassFgV}A scroll depicting the techniques of Houzouin-ryū school, a spear martial arts specialised in the use of the Jūmonji sickle spear to enable diverse offensive and defensive techniques.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_8']/@desc" ><xsl:attribute name="desc">{=IUww3Wm5}A book written by Ogasawara Mochinaga, master of archery for Shogun Ashikaga Yoshinori, that explains how to handle the bow and what to do when it is broken.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_9']/@desc" ><xsl:attribute name="desc">{=JG93otWp}This book contains the secret archery techniques of the Takeda Clan, passed down for generations and written down by Takeda Motonobu, head of a junior branch of the clan.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_10']/@desc" ><xsl:attribute name="desc">{=OJgoEU16}This book describes the horseriding technique of the Ōtsubo-ryū school, one of the classical schools of horsemanship that counts the Ashikaga Shoguns among its practitioners.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_11']/@desc" ><xsl:attribute name="desc">{=DY9tJx32}This scroll details the medicinal method of horse breeding and contains a depiction of the patron god of horse doctors as well as medicinal herbs used as horse medicine.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_12']/@desc" ><xsl:attribute name="desc">{=zDkXRI5J}This scroll contains the teachings of the Anzai-ryū school of horse medicine and describes the relationship between esoteric philosophy and horse diseases, including the methods and effects of treatment with acupuncture.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_13']/@desc" ><xsl:attribute name="desc">{=Nqt9jf0G}This book describes the secrets of horse treatment written by Kuwashima Hirotsuna and provides details on the parts of the horse's body and various methods of moxibustion treatment.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_14']/@desc" ><xsl:attribute name="desc">{=VNF4HoAS}A book containing the teachings of Hachijou Fusashige, founder of the Hachijou-ryū school of horsemanship.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_15']/@desc" ><xsl:attribute name="desc">{=uchnzXJ3}This book by Ogasawara Mochinaga, master of archery for Shogun Ashikaga Yoshinori, describes the manners and techniques of the Yabusame mounted archery.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_16']/@desc" ><xsl:attribute name="desc">{=u2cqrvgL}This book by Ogasawara Motonaga, son of Mochinaga master of archery for the Ashikaga Shogunate, details the manners and techniques of the Kasagake mounted archery.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_17']/@desc" ><xsl:attribute name="desc">{=FtTUGDMu}This book by Ogasawara Mochinaga, master of archery for Shogun Ashikaga Yoshinori, describes the manners and techniques of the Inuoumono mounted archery.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_18']/@desc" ><xsl:attribute name="desc">{=OyqAdyhX}This scroll contains a secret gunpowder recipe, originally sent by Ōtomo Sourin, and describes the method of preparation, precautions and proportions of ingredients.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_19']/@desc" ><xsl:attribute name="desc">{=fILAeW5I}This scroll describes the production of gunpowder techniques of the Tsuda-ryū school of artillery.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_20']/@desc" ><xsl:attribute name="desc">{=zPKXoJ7N}This scroll explains how to produce gun ammunition and more than 30 different types of balls, including balls made by connecting several balls with a wire and hollow balls.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_21']/@desc" ><xsl:attribute name="desc">{=5Id7cGyB}A book describing the art of gunnery. Written by Karaudo Chikahiro, a firearm instructor for the Jimbo clan.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_22']/@desc" ><xsl:attribute name="desc">{=3zsuNC4G}A set of scrolls describing the art of gunnery of the Kishiwada-ryū school of gunnery, written by Yoshida Morisada. The book details proper firing techniques and gunpowder recipes. The scroll also includes many descriptions from a spiritual perspective, linking guns with esoteric Buddhism and the role of guns in expelling evil demons.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_23']/@desc" ><xsl:attribute name="desc">{=2wY88rzX}A scroll containing over three decades of esoteric iconography and scriptures, assembled by Kintaibō Kakuzen. Contains over one hundred volumes and is one of the largest collections of its kind.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_24']/@desc" ><xsl:attribute name="desc">{=RuQ4TZhh}A scroll containing the different scholastic and oral traditions from various schools of esoteric Buddhism, organized into two hundred twenty-eight volumes. Organized by Gokurakubou Jouchou, taking over thirty years to compile.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_25']/@desc" ><xsl:attribute name="desc">{=OBbYaTVr}A scroll containing the oral traditions, events, and manners from various schools of esoteric Buddhism. Organized by Sōkushoin Koushū, a learned monk of the Tendai sect, who ascended Mount Hiei to study the unique sects of Buddhism.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_26']/@desc" ><xsl:attribute name="desc">{=unC8XMbS}A book of scrolls compiling rituals and doctrines related to mountain ascetic practices of Shugendo. Written by Akūbou Sokuden, a mountain ascetic from Mount Nikko.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_27']/@desc" ><xsl:attribute name="desc">{=pYmNTiMK}A book of letters testifying to the transmission of ritual doctrine in Shugendo. Written by Akūbou Sokuden, a mountain ascetic from Mount Nikko.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_28']/@desc" ><xsl:attribute name="desc">{=AYhzKPj2}Five volumes authored by, Utsunomiya Mikawa-nyūdou, an officer in charge of managing the Katana of the Shogun Ashikaga Yoshimitsu. He categorized katana by period and presented a genealogy of katana smiths, as well as famous swords and their measurements.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_29']/@desc" ><xsl:attribute name="desc">{=EwYMTiHV}A scroll containing a list of names of katana smiths by region. Includes each smith’s inscriptions, weapon characteristics, anecdotes, and genealogical information.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_30']/@desc" ><xsl:attribute name="desc">{=b5wKRFvG}A book finished by Saitou Toshimasa, started by his father, that covers around eight hundred forty Katana. Includes Katana from Awataguchi, Soushū, Chūgoku-Shikoku, Hokuriku, Bizen-Bitchū, and Kyūshū.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_31']/@desc" ><xsl:attribute name="desc">{=kCaKCo01}A book classifying katana smiths in different countries into five levels of evaluation and includes highlights of their blades, the date of their production, and examples of famous swords.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_32']/@desc" ><xsl:attribute name="desc">{=sLDnkOCe}A book describing beliefs, origins, and history of the mountains of the Kinki region.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_33']/@desc" ><xsl:attribute name="desc">{=z0uNk7ZU}A book composed of experiences traveling from to Kamakura to Kyoto in 1223. It is filled with phrases from old Chinese texts, poetry, Buddhist writings, as well as detailed descriptions of landscapes and landmarks.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_34']/@desc" ><xsl:attribute name="desc">{=Docmd9xI}A travelogue book composed of experiences on the way from Higashiyama, Kyoto to Kamakura in 1242. It is filled with detailed descriptions of landscapes.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_35']/@desc" ><xsl:attribute name="desc">{=415dA2QQ}A collection of diary entries written by Abutsuni, consort of Fujiwara no Tameie. The entries focused on her travels from Kyoto to Kamakura to appeal to the Kamakura Shogunate over a territorial dispute between her son and his half-brother.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_36']/@desc" ><xsl:attribute name="desc">{=PGtz6eGJ}A book, written by Shōgoin Dōkō, cataloging various materials of his travels on the Hokuriku Route. Includes various writings on the Ou-shū region, multiple kinds of poems, legends, and writings on historical sites.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_37']/@desc" ><xsl:attribute name="desc">{=UPBYYWDk}A book describing the life and culture of the warriors and provinces of Japan during the Muromachi period.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_38']/@desc" ><xsl:attribute name="desc">{=0juzWg0C}A collection of studies on Japan’s geography, customs, manners, and natural history. Written by Tei Shunkō who was sent to Japan to help in the suppression of Japanese Pirates.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_39']/@desc" ><xsl:attribute name="desc">{=efFEbXCp}A book detailing the relations between Korea and Japan, prepared by the Yi Dynasty diplomat Shin Suk-ju. It records the politics of Japan and Ryukyu, including history of diplomatic exchanges and reception of envoys.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_40']/@desc" ><xsl:attribute name="desc">{=ZTWHS0RH}A Japanese book on the military strategy established at the end of the Heian period. It was created as a supplementary military book to the writings of Sun Tzu.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_41']/@desc" ><xsl:attribute name="desc">{=b8DDdAe6}This book, is revered as one of China's major military strategy books, also known as The Art of War, written by Sonshi (Sun Tzu). With advances in organized conflict, this text has become increasingly important for strategists across Japan. Utilized as a source for the writings of Takeda Shingen.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_42']/@desc" ><xsl:attribute name="desc">{=SPfjkxAC}This book is revered as one of China's major military strategy books, written by Goshi (Wu Qi). With advances in organized conflict, this text has become increasingly important for strategists across Japan.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_43']/@desc" ><xsl:attribute name="desc">{=JQq34w3V}Revered as one of China's major military strategy books. With advances in organized conflict, this text has become increasingly important for strategists across Japan.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_44']/@desc" ><xsl:attribute name="desc">{=JQq34w3V}Revered as one of China's major military strategy books. With advances in organized conflict, this text has become increasingly important for strategists across Japan.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_45']/@desc" ><xsl:attribute name="desc">{=JQq34w3V}Revered as one of China's major military strategy books. With advances in organized conflict, this text has become increasingly important for strategists across Japan.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_46']/@desc" ><xsl:attribute name="desc">{=JQq34w3V}Revered as one of China's major military strategy books. With advances in organized conflict, this text has become increasingly important for strategists across Japan.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_47']/@desc" ><xsl:attribute name="desc">{=JQq34w3V}Revered as one of China's major military strategy books. With advances in organized conflict, this text has become increasingly important for strategists across Japan.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_48']/@desc" ><xsl:attribute name="desc">{=6R5Bg134}A book on the theories of writing renga, written by the court noble Nijō Yoshimoto. It describes the history and rules of renga, the spirit of renga creation, attire, and how to organize renga meetings.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_49']/@desc" ><xsl:attribute name="desc">{=vMQT3wfW}A book on the theories of writing Muromachi period renga, written by the renga master Sōgi. It describes the history of renga and the techniques of renga creation in a question-and-answer style, with examples.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_50']/@desc" ><xsl:attribute name="desc">{=19KEPyJH}This book is a collection of two thousand fifty-two renga poems, many written by samurai. Compiled by Ichijou Fuyuyoshi, Sanjōnishi Sanetaka, Sōgi and others.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_51']/@desc" ><xsl:attribute name="desc">{=zTf4tDVo}Written by the monk Gen’e, this book is an assortment of diverse knowledge and education necessary for social life. The contents cover food, clothing, housing, occupations, territorial management, architecture, judiciary practices, professions, Buddhism, armor, culture, and recuperation.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_52']/@desc" ><xsl:attribute name="desc">{=hKNscAQA}Written by the nobleman Ichijou Kaneyoshi, this book is an assortment of miscellaneous information. Includes details on the social life of samurai and court nobles, horses, armor, blacksmithing, temples, famous painters, alcoholic beverages, landmarks, memorial services, teas, and much more.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_53']/@desc" ><xsl:attribute name="desc">{=HwMZdP7F}Written by the nobleman Ichijou Kaneyoshi, this book is a compilation of Shintou and Buddhist Rituals, worship, processions, events, clothing, secret banquets, bad luck rites, imperial edicts, and other miscellaneous writings.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_54']/@desc" ><xsl:attribute name="desc">{=zyv9c1x4}A collection of explanations into the manners and systems of the Muromachi Shogunate’s warrior class, including accounts of negotiations between court nobles and samurai. Authored by Ise Sadamachi, governor of Yamashiro Province.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_55']/@desc" ><xsl:attribute name="desc">{=LJHypGfx}A story describing the contrasts between the Taira and Minamoto, their subsequent battles and downfalls, and the human drama of the Heian Nobles.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_56']/@desc" ><xsl:attribute name="desc">{=3N5nee3C}An eight volume narrative on Minamoto no Yoshitsune and his followers.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_57']/@desc" ><xsl:attribute name="desc">{=cwqXvgWV}A book detailing the accession of Emperor Go-Daigo. Includes the fall of the Kamakura Shogunate, and the new government and its collapse.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_58']/@desc" ><xsl:attribute name="desc">{=eT7w6xyJ}A Kamakura period biographical story based on the revenge of the Soga brothers in Fujino. Written in the style of a military history treatise.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_59']/@desc" ><xsl:attribute name="desc">{=XflIVwxR}A collection of four books on Confucious thought and five books on assorted poems, documents, rites, and other texts. It was possibly compiled in some way by Confucious himself.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_60']/@desc" ><xsl:attribute name="desc">{=SjVaQf1a}An Encyclopaedia by Minamoto no Shitagō, containing about three thousand entries on his opinions of various matters.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_61']/@desc" ><xsl:attribute name="desc">{=edDbDSHL}A book of six hundred twenty articles filled with miscellaneous meanings of Japanese and Chinese words and phrases. Includes celestial phenomena, deities, countries, inner regions, geography, plants, grass, birds, beasts and insects, human affairs, the human body, Buddhism, treasures, clothing, musical instruments, miscellaneous items, food and drink, and more.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_62']/@desc" ><xsl:attribute name="desc">{=AspEeudR}An Encyclopaedia of the Middle Ages, authored by Tōin Kinkata.  Includes astronomy, geography, the divisions of court, literature, manners and customs, arts and crafts, religion, and taboos.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_63']/@desc" ><xsl:attribute name="desc">{=xFWvS5gM}An Encyclopaedia by  Tōroku no Hanō with eighteen sections on society, seasonal events, quantities, language, human ethics, and more.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_64']/@desc" ><xsl:attribute name="desc">{=r13LNEG0}A scroll filled with an assortment of writings. Includes astronomy, geography, literature, divisions of court, customs, goods, arts and crafts, religion, and taboos.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_65']/@desc" ><xsl:attribute name="desc">{=qYy1U6EE}A collection of thirty-one articles codifying the customary laws of maritime traders in the Seto Inland Sea. Includes regulations for ships, shipowners, sailors, maritime salvage, and nautical rituals.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_66']/@desc" ><xsl:attribute name="desc">{=sBKwO1Rh}Fifty-one articles comprising the codes of the Kamakura shogunate. Filled with diverse content including the duties of Shugo guardians and Jitou constables and codifies unique samurai jurisprudence that differs from the traditional court law and manor law.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_67']/@desc" ><xsl:attribute name="desc">{=er6VQ05c}A commentary on the shogunate's basic code of law, the Goseibaishikimoku, authored by Kiyohara no Nobukata. The contents contain quotes and explanations of the various theories of kōke law and discusses the blending of different kōke laws within samurai families.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_68']/@desc" ><xsl:attribute name="desc">{=tRpBlqV8}Seventeen articles consisting of laws authored by Asakura Takakage, given to his heir Ujikage. The contents cover directives on the control of vassals, recruitment of personnel, strengthening of military power, emphasis on civil administration, fostering of territorial culture, strictness of justice, and vigilance against other domains.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_69']/@desc" ><xsl:attribute name="desc">{=gsOIC4l7}An assorted set of laws written by Date Tanemune detailing a number of regulations on the governance of his territory. It is characterized by detailed provisions on criminal offenses such as murder and robbery, the broad recognition of landowners' right to rule, and preferential treatment in the sale and purchase of land to craftsmen of arms and farming implements.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_70']/@desc" ><xsl:attribute name="desc">{=XKXBAN3A}An article of law written by Imagawa Yoshimoto detailing a number of regulations on the governance of his territory. It provides stipulation on relations between lords and peasants, boundary disputes, responses in case of conflicts and banditry, restrictions on the sale and purchase of territory, provisions for the vassal system, non-interventionist rights, and inheritance and court procedures, and much more.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_71']/@desc" ><xsl:attribute name="desc">{=3ybFlk33}A set of laws written by Takeda Harunobu (Shingen) for the realms under the control of the Takeda Clan. A total of fifty-five articles, It stipulates the prohibition of private wars, the regulation of letters to other domains, the prohibition of sectarian disputes, and the prohibition of private alliances.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_72']/@desc" ><xsl:attribute name="desc">{=l5m8ME5Y}A set of laws written by Sagara Haruhiro for the realms under the control of the Sagara Clan. Includes stipulations on the sale and purchase of rice fields, master-servant relations, water access, fines for sheltering fugitives, and prohibits the Ikkou sect. Prayers by anyone other than Buddhists, Shinto, or mountain dwelling priests are strictly prohibited.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_73']/@desc" ><xsl:attribute name="desc">{=peUDJ52f}A medical treatise compiled by Izumo no Hirosada from the Heian period, sporting a collection of medicinal herbs across the region.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_74']/@desc" ><xsl:attribute name="desc">{=16fh1qth}A medical treatise compiled by Tanba Yasuyori, a doctor of acupuncture who served as court physician during the Heian period. It compiled into thirty volumes and consists of doctors' ethics, general medical theory, therapies for various diseases, health and hygiene regimen, medical techniques and medical thought.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_75']/@desc" ><xsl:attribute name="desc">{=vq0zLdDx}A leading medical treatise of the Kamakura period, compiled by the physician Kajiwara Shouzen (梶原性全). Kajiwara utilized his knowledge of medicine and references from the latest Chinese Medical texts of the period to assemble this set of volumes. Includes details on vast amount of illnesses and diagrams of internal organs.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_76']/@desc" ><xsl:attribute name="desc">{=irBHhwiz}Kajiwara Shouzen (梶原性全)’s medical treatise written around 1313 and entirely in Chinese. Intended to transmit and preserve the art of medicine.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_77']/@desc" ><xsl:attribute name="desc">{=WOuDgTfK}Ten volumes of Yū Souritsu’s Ming dynasty medical texts reprinted and published by Asaino Sōzui, a merchant in Sakai. Intended for en-masse sale, this collection is vital for spreading knowledge on a plethora of ailments.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_78']/@desc" ><xsl:attribute name="desc">{=PtJNY3zY}A set of eight volumes on diseases and treatments by Manase Dousan. Contains information on diverse etiologies from ancient and modern Chinese sources and is vital for the cataloging and treating of numerous ailments across Japan.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_79']/@desc" ><xsl:attribute name="desc">{=hWxWyNii}A comprehensive collection of articles on the methods and procedures of castle building. Inside are detailed descriptions of the material, manpower, and techniques required of castles depending on their terrain and complexity.</xsl:attribute></xsl:template> 
  <xsl:template match="Book[@id='book_80']/@desc" ><xsl:attribute name="desc">{=jXNpbKGC}Sou Kouryou (Zeng Gongliang)'s completed collection of military writings from the Song Dynasty. Each volume is filled with theories and doctrines on assorted military knowledge as well as descriptions of various siege engines and defensive equipment.</xsl:attribute></xsl:template> 
</xsl:stylesheet>