<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output version="1.0" omit-xml-declaration="yes" encoding="UTF-8" indent="yes"/>
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
  <xsl:template match="Hero[@id='lord_1_maeda']/@text" ><xsl:attribute name="text">{=D3463d2f}Maeda Toshiie (前田利家) is from Owari Province, born as Inuchiyo (犬千代), and identified himself as Maeda Matazaemon (前田又左衛門) later. He began to serve Oda Nobunaga as a page boy, and later as his elite soldier. He likes to use a long pike with a crimson shaft. So, he is nicknamed Yari no Mataza, or Mataza the spear, due to his skill and this showy weapon. He is sometimes quite short-tempered. He had been exiled for a few years and was allowed to rejoin Oda's army just a few years ago. He committed a crime to kill a favored servant of Nobunaga who insulted Toshiie.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_akechi']/@text" ><xsl:attribute name="text">{=540e3dFA}Akechi Mitsuhide (明智光秀), born as Hikotarou (彦太郎), identified himself as Akechi Jūbē (明智十兵衛) later. He and his family don't serve the Oda clan hereditarily. After over a decade wandering, he began to serve Oda Nobunaga. Now, Nobunaga favors his talent and frankly calls him Kinka Aatama, the Kumquat Head, which means that he teased his bald head.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_tokugawa']/@text" ><xsl:attribute name="text">{=4FEF32B1}Tokugawa Ieyasu (徳川家康) was born as Takechiyo (竹千代), and once identified himself as Matsudaira Jirou-saburou (松平次郎三郎), as a young head of the Matsudaira clan, the current Tokugawa clan. He is young, but rumored that he is thoughtful and patient. He is also known by several names: Motonobu (元信), Motoyasu (元康), and Ieyasu (家康). In this period, a samurai lord gives one kanji character from his name to his retainer to rename his name. This is often an honor, but also a proof of servitude. After the death of Imagawa Yoshimoto (今川義元), Ieyasu, whose name was Motoyasu at that time, immediately renamed himself Ieyasu.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_honda']/@text" ><xsl:attribute name="text">{=88741768}Honda Tadakatsu (本多忠勝), born as Nabenosuke (鍋之助), identified himself as Honda Heihachirou (本多平八郎), is one of the powerful warlords serving Ieyasu. His spear is said to be so sharpened that a dragonfly landing on the top is bisected by its weight. He is very strong, so it is rumored that he has never been wounded on the battlefield.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_hattori']/@text" ><xsl:attribute name="text">{=8c994Bb0}Hattori Masanari (服部正成), identified as himself Hattori Hanzou (服部半蔵), was born in Iga province. He is a samurai serving the Tokugawa clan. He is a master of the spear and is famous for his performance on the battlefield, so he is feared like an Oni demon.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_uesugi']/@text" ><xsl:attribute name="text">{=Bd0b0fd8}Nagao Terutora (長尾輝虎) was born as the illegitimate child of Nagao Tamekage and was named Torachiyo (虎千代). Although the polygamy system was accepted among the Samurai society at that period, the wives and their children were discriminated against by the mothers' family background. He lived in the Rinsen-ji temple in his childhood. Later, he was summoned to the Nagao family and finally inherited the head of the clan from his sickly older half-brother. His name became Kagetora (景虎) and his byname became Nagao Heizou (長尾平三) when coming of age. But he renamed himself Terutora later. He is very faithful due to, or not to, his childhood life, and particularly devoted to Bishamonten, a Buddhist guardian and a deity of war. Later, he became a monk with the Buddhist name Hushikian Kenshin (不識庵謙信), named after a monk who raised him. After people recognized his martial talent, he was also admired as Gunshin, the God of War. His current surname, Uesugi, was inherited from Uesugi Norimasa (上杉憲政), a former Kantou Kanrei, the regent of the Vice Shogun.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_takeda']/@text" ><xsl:attribute name="text">{=d04Ca636}Takeda Harunobu (武田晴信), born as Katsuchiyo (勝千代), identified himself as Takeda Tarou (武田太郎), is a cunning, old strategist, diplomat, and warlord. His name, Harunobu, derives from Yoshiharu, an ex-Shogun of Ashikaga dynasty. He has ruled Kai province, a mountainous and hard land, for many years, and is known for his strategic and martial talent and several times of battles against Uesugi Kenshin. Through the battles, he became a monk with the Buddhist name Tokueiken Shingen (徳榮軒信玄), his most well-known name later. He also preferred high-society culture and invited famous Buddhist monks, the most intellectual people during this period, many times. His banner shows a famous phrase, Fūrinkazan, cited from Sonshi, the Art of War by Sun Tzu, which they may have taught him.{NEWLINE}{NEWLINE}It is said that Shingen invented Houtou, a kind of noodle dish. It contains some root vegetables and doesn't contain meat. However, it is well-nourished. This is just a lore, but this lore it self shows his reputation among folks.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_mori']/@text" ><xsl:attribute name="text">{=6Da818C5}Mouri Terumoto (毛利輝元) was born as Koutsurumaru (幸鶴丸). He identifies himself as Mouri Shoutarou (毛利少輔太郎). He had no choice but to initiate the genpuku, the coming-of-age ceremony at age 11, and inherited the head of the Mouri clan after his father passed away suddenly. His name, Terumoto, derives from the ex-shogun Yoshiteru. However, Shogun Yoshiteru was killed right after that. Terumonoto needs to confront several problems, but is supported by Motonari, his great grandfather, and his uncles.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_mori_1']/@text" ><xsl:attribute name="text">{=F3032095}Mouri Motonari (毛利元就), born as Shoujumaru (松壽丸), identified himself as Ōe Jibunoshou (大江治部少輔), named after the ancestral clan of Mouri. He was born into a family of a minor local lord, and his parents died in his young. In this era, such local minor lords are forced to be involved in power and succession struggles with relatives, and also in the political disputes between neighboring major daimyos appointed by the central government in Kyōto. Starting his life to get back his land and castle, which was taken by his uncle, Motonari finally took almost the whole of the San'you and San'in regions, which were dominated by daimyos that he had once been subordinated to, by merging many minor and larger clans. Although he is getting old now, definitely, he is one of the greatest strategists and diplomats during this period.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_kobayakawa']/@text" ><xsl:attribute name="text">{=8294a96e}Mouri Takakage (毛利隆景), born as Tokujumaru (徳寿丸), identified himself as Kobayakawa Matashirou (小早川又四郎), is the third son of Mouri Motonari. Like his brother, He was adopted into the Kobayakawa family, a local notable family in the Aki province, and inherited the family. These adoptions are Motonari's plot to expand his domain. After the death of his oldest brother, he assists Terumoto, his nephew, with his brother and father.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_kobayakawa_1']/@text" ><xsl:attribute name="text">{=Shokuho3666bc12}Kobayakawa Toida No Ōkata .</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_kikkawa']/@text" ><xsl:attribute name="text">{=B329E7c7}Mouri Motoharu (毛利元春), identified himself as Kikkawa Shoujirou (吉川少輔次郎), is the second son of Mouri Motonari (毛利元就), adopted into and later inherited the Kikkawa family, a distinguished family of Aki province. He assists Terumoto, his nephew and lord, well.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_satake']/@text" ><xsl:attribute name="text">{=6a4a1eFc}Satake Yoshisige (佐竹義重), born as Tokujumaru (徳寿丸), the son of Yoshiaki, identified himself as Satrake Jirou (佐竹次郎). The Satake clan is one of the longstanding samurai clans, originating from Genji. Yoshishige, the eighteenth head of the Satake clan, is a talented warlord. He is admired and nicknamed Bandou Tarou (坂東太郎), while feared as Oni Yoshishige, the demonic Yoshishige.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_matsunaga']/@text" ><xsl:attribute name="text">{=8a0aa05A}Matsunaga Hisahide (松永久秀), called himself Matsunaga Soudai (松永霜台), also known as Matsunaga Danjou (松永弾正), served the Miyoshi clan. However, in Kinai, he is increasing his presence by his ability and opportunistic decision.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_ashikaga_6']/@text" ><xsl:attribute name="text">{=143aB3C3}Ashikaga Yoshihide (足利義栄) was born in a branch family of the Ashikaga clan in Awa province. He is also sickly; thus, he was not expected as the future Shogun. However, at this period, the Shogunate's authority can be easily distorted by powerful and ambitious vassals. After Shogun Yoshiteru is killed by the Miyoshi, they get close to Yoshihide and invite him to Kyoto, and then make him a puppet Shogun. Now the Miyoshi's plot is successful; however, why do we conclude that anyone else doesn't come up with such a plot?</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_hosokawa']/@text" ><xsl:attribute name="text">{=27063725}Hosokawa Fujitaka (細川藤孝) was born as Mankichi (萬吉) and adopted into a branch family of the Hosokawa clan. The Hosokawa clan is a distinguished clan that produces Kanrei, the Shogun's assistant or chief steward, generation by generation. He identifies himself as Hosokawa Yoichirou (細川与一郎). Living in the high society in Kyōto, Fujitaka is a nobleman with talent in various domains of arts: Poetry, Sarugaku act, Sadou tea party, Kemari football, and martial arts. However, the Hosokawa clan is now falling with the Shogunate. Fujitaka decided to escape from Kyōto with Yoshiaki, a brother of the killed Shogun, and asked for aid from Oda Nobunaga.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_oda']/@text" ><xsl:attribute name="text">{=ea421876}Oda Nobunaga (織田信長) was born with the name Kippoushi (吉法師). He is the son of Nobuhide, serving the mainstream of the Oda clan. The Owari province is divided and ruled by some substream families of the Oda clan. He identified himself as Oda Saburou (織田三郎) or Kazusa-no-kami (上総守) later. In his adolescence, He plays arrogantly and tracklessly in his teens. There was no doubt that succession problems arose when his father passed. However, Nobunaga defeated all of his confronting relatives and vassals, and succeeded in ruling the whole of Owari province. Then, following the successive military triumphs, his domain is expanding more and more.{NEWLINE}{NEWLINE}Saitou Dousan (斎藤道三), his father-in-law and the former ruler of Mino province, once predicted Nobunaga's great leaping out at first glance before the marriage between his daughter and Nobunaga, when he still had a reputation as ō-utsuke, the most foolish guy. It is said since a long ago that fifty years in a human's life is as short as a one-night dream in Heaven. However, now, it is still halfway for Nobunaga, and the result is still unpredictable for humans.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_kinoshita']/@text" ><xsl:attribute name="text">{=3698eF33}Kinoshita Hideyoshi (木下秀吉), born as Hiyoshimaru (日吉丸), identified himself as Kinoshita Toukichirou (木下藤吉郎), is one of Oda's vassals. He is not from a distinguished family and has served a few minor samurai clans. However, now he is emerging among the vassals of the Oda clan by his talent.</xsl:attribute></xsl:template>
  <xsl:template match="Hero[@id='lord_1_shimazu']/@text" ><xsl:attribute name="text">{=C3C99df1}Shimazu Yoshihisa (嶋津義久), born as Torajumaru (虎寿丸), identified himself as Shimazu Matasaburou (嶋津又三郎). First, his given name was Tadayoshi (忠良), same name as Jisshin-sai (日新斎), his great-grandfather; however, he later renamed himself Yoshihisa. He has a talented warlord, while his brothers are also skilled warriors.</xsl:attribute></xsl:template>
</xsl:stylesheet>