<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output version="1.0" omit-xml-declaration="yes" encoding="UTF-8" indent="yes"/>
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_sword']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='masterwork_sword']/@name" ><xsl:attribute name="name">{=8Tal0XIj}Masterwork {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='balanced_sword']/@name" ><xsl:attribute name="name">{=fdgcpipH}Balanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='dull_sword']/@name" ><xsl:attribute name="name">{=LmzHz4CG}Dull {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='rusty_sword']/@name" ><xsl:attribute name="name">{=l7QEpVwU}Rusty {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_bow']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='masterwork_bow']/@name" ><xsl:attribute name="name">{=8Tal0XIj}Masterwork {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='balanced_bow']/@name" ><xsl:attribute name="name">{=fdgcpipH}Balanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='cracked_bow']/@name" ><xsl:attribute name="name">{=br0N6SSH}Cracked {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='splintered_bow']/@name" ><xsl:attribute name="name">{=8Pd6fLoy}Splintered {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_crossbow']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='masterwork_crossbow']/@name" ><xsl:attribute name="name">{=8Tal0XIj}Masterwork {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='tuned_crossbow']/@name" ><xsl:attribute name="name">{=WbaIorOh}Tuned {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='bent_crossbow']/@name" ><xsl:attribute name="name">{=06e12828}Rusted {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='cracked_crossbow']/@name" ><xsl:attribute name="name">{=br0N6SSH}Cracked {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_arrows']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='balanced_arrows']/@name" ><xsl:attribute name="name">{=fdgcpipH}Balanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='large_bag_arrows']/@name" ><xsl:attribute name="name">{=3JaHZA3Y}Large Bag of {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='bent_arrows']/@name" ><xsl:attribute name="name">{=eb4miTUB}Bent {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='splintered_arrows']/@name" ><xsl:attribute name="name">{=8Pd6fLoy}Splintered {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_bolts']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='balanced_bolts']/@name" ><xsl:attribute name="name">{=fdgcpipH}Balanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='large_bag_bolts']/@name" ><xsl:attribute name="name">{=3JaHZA3Y}Large Bag of {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='bent_bolts']/@name" ><xsl:attribute name="name">{=eb4miTUB}Bent {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='splintered_bolts']/@name" ><xsl:attribute name="name">{=8Pd6fLoy}Splintered {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_cheap']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='fine_cheap']/@name" ><xsl:attribute name="name">{=xeb1b5PQ}Fine {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='well_crafted_cheap']/@name" ><xsl:attribute name="name">{=85WO1MKG}Well made {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='bent_cheap']/@name" ><xsl:attribute name="name">{=eb4miTUB}Bent {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='cracked_cheap']/@name" ><xsl:attribute name="name">{=br0N6SSH}Cracked {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_polearm']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='masterwork_polearm']/@name" ><xsl:attribute name="name">{=8Tal0XIj}Masterwork {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='balanced_polearm']/@name" ><xsl:attribute name="name">{=fdgcpipH}Balanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='bent_polearm']/@name" ><xsl:attribute name="name">{=eb4miTUB}Bent {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='cracked_polearm']/@name" ><xsl:attribute name="name">{=br0N6SSH}Cracked {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_mace']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='masterwork_mace']/@name" ><xsl:attribute name="name">{=8Tal0XIj}Masterwork {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='balanced_mace']/@name" ><xsl:attribute name="name">{=fdgcpipH}Balanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='unbalanced_mace']/@name" ><xsl:attribute name="name">{=VbxJPJGe}Unbalanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='splintered_mace']/@name" ><xsl:attribute name="name">{=8Pd6fLoy}Splintered {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_axe']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='masterwork_axe']/@name" ><xsl:attribute name="name">{=8Tal0XIj}Masterwork {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='quality_axe']/@name" ><xsl:attribute name="name">{=bAdxUq7s}Quality {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='dented_axe']/@name" ><xsl:attribute name="name">{=PobRGG9S}Dented {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='rusty_axe']/@name" ><xsl:attribute name="name">{=l7QEpVwU}Rusty {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_axe_throwing']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='large_bag_axe_throwing']/@name" ><xsl:attribute name="name">{=3JaHZA3Y}Large Bag of {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='balanced_axe_throwing']/@name" ><xsl:attribute name="name">{=fdgcpipH}Balanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='bent_axe_throwing']/@name" ><xsl:attribute name="name">{=eb4miTUB}Bent {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='splintered_axe_throwing']/@name" ><xsl:attribute name="name">{=8Pd6fLoy}Splintered {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_knife_throwing']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='balanced_knife_throwing']/@name" ><xsl:attribute name="name">{=fdgcpipH}Balanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='large_bag_knife_throwing']/@name" ><xsl:attribute name="name">{=3JaHZA3Y}Large Bag of {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='bent_knife_throwing']/@name" ><xsl:attribute name="name">{=eb4miTUB}Bent {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='rusty_knife_throwing']/@name" ><xsl:attribute name="name">{=l7QEpVwU}Rusty {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_spear_dart_throwing']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='balanced_spear_dart_throwing']/@name" ><xsl:attribute name="name">{=fdgcpipH}Balanced {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='large_bag_spear_dart_throwing']/@name" ><xsl:attribute name="name">{=3JaHZA3Y}Large Bag of {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='bent_spear_dart_throwing']/@name" ><xsl:attribute name="name">{=eb4miTUB}Bent {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='cracked_spear_dart_throwing']/@name" ><xsl:attribute name="name">{=br0N6SSH}Cracked {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_shield']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='lordly_shield']/@name" ><xsl:attribute name="name">{=w3jn7Ahz}Lordly {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='thick_shield']/@name" ><xsl:attribute name="name">{=BA9c7gPb}Thick {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='battered_shield']/@name" ><xsl:attribute name="name">{=TePk4BSJ}Battered {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='cracked_shield']/@name" ><xsl:attribute name="name">{=br0N6SSH}Cracked {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_plate']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='lordly_plate']/@name" ><xsl:attribute name="name">{=w3jn7Ahz}Lordly {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='fine_plate']/@name" ><xsl:attribute name="name">{=xeb1b5PQ}Fine {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='dented_plate']/@name" ><xsl:attribute name="name">{=PobRGG9S}Dented {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='rusty_plate']/@name" ><xsl:attribute name="name">{=l7QEpVwU}Rusty {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_chain']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='lordly_chain']/@name" ><xsl:attribute name="name">{=w3jn7Ahz}Lordly {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='fine_chain']/@name" ><xsl:attribute name="name">{=xeb1b5PQ}Fine {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='loose_chain']/@name" ><xsl:attribute name="name">{=bWhJwHA1}Loose {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='rusty_chain']/@name" ><xsl:attribute name="name">{=l7QEpVwU}Rusty {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_leather']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='fine_leather']/@name" ><xsl:attribute name="name">{=xeb1b5PQ}Fine {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='waxed_leather']/@name" ><xsl:attribute name="name">{=zPqPvf0o}Waxed {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='worn_leather']/@name" ><xsl:attribute name="name">{=5yVgXqQr}Worn {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='battered_leather']/@name" ><xsl:attribute name="name">{=TePk4BSJ}Battered {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_cloth']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='fine_cloth']/@name" ><xsl:attribute name="name">{=xeb1b5PQ}Fine {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='tailored_cloth']/@name" ><xsl:attribute name="name">{=Q5HVyNWJ}Tailored {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='worn_cloth']/@name" ><xsl:attribute name="name">{=5yVgXqQr}Worn {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='ripped_cloth']/@name" ><xsl:attribute name="name">{=Pbb94NdW}Ripped {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='legendary_cloth_unarmoured']/@name" ><xsl:attribute name="name">{=lRf4t9Qg}Legendary {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='fine_cloth_unarmoured']/@name" ><xsl:attribute name="name">{=xeb1b5PQ}Fine {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='tailored_cloth_unarmoured']/@name" ><xsl:attribute name="name">{=Q5HVyNWJ}Tailored {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='worn_cloth_unarmoured']/@name" ><xsl:attribute name="name">{=5yVgXqQr}Worn {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='ripped_cloth_unarmoured']/@name" ><xsl:attribute name="name">{=Pbb94NdW}Ripped {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_lean']/@name" ><xsl:attribute name="name">{=cmNJ45Xl}Lean {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_stubborn']/@name" ><xsl:attribute name="name">{=DXzpdjAq}Stubborn {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_headstrong']/@name" ><xsl:attribute name="name">{=yIZDvo8I}Headstrong {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_brave']/@name" ><xsl:attribute name="name">{=uh2w0Ehh}Brave {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_fierce']/@name" ><xsl:attribute name="name">{=Bb618GDp}Fierce {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_strong']/@name" ><xsl:attribute name="name">{=wIcAgF0D}Strong {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_bulky']/@name" ><xsl:attribute name="name">{=2k8qk1KD}Bulky {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_quick']/@name" ><xsl:attribute name="name">{=YuzBp6p4}Quick {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_fast']/@name" ><xsl:attribute name="name">{=D1eK25tu}Fast {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_slow']/@name" ><xsl:attribute name="name">{=NX2FkbdC}Slow {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_sickly']/@name" ><xsl:attribute name="name">{=ICfSXUvV}Sickly {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_aneamic']/@name" ><xsl:attribute name="name">{=Rxt7m2Sl}Aneamic {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_timid']/@name" ><xsl:attribute name="name">{=nSILI9b9}Timid {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_cowardly']/@name" ><xsl:attribute name="name">{=gsNgwoAq}Cowardly {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_healthy']/@name" ><xsl:attribute name="name">{=NuViWQIf}Healthy {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_docile']/@name" ><xsl:attribute name="name">{=XyaeTnrM}Docile {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_gentle']/@name" ><xsl:attribute name="name">{=egOcNUMs}Gentle {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_swayback']/@name" ><xsl:attribute name="name">{=OOtfJCaJ}Swayback {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='horse_purebred']/@name" ><xsl:attribute name="name">{=MC29cHra}Purebred {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_lean']/@name" ><xsl:attribute name="name">{=cmNJ45Xl}Lean {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_stubborn']/@name" ><xsl:attribute name="name">{=DXzpdjAq}Stubborn {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_headstrong']/@name" ><xsl:attribute name="name">{=yIZDvo8I}Headstrong {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_brave']/@name" ><xsl:attribute name="name">{=uh2w0Ehh}Brave {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_fierce']/@name" ><xsl:attribute name="name">{=Bb618GDp}Fierce {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_strong']/@name" ><xsl:attribute name="name">{=wIcAgF0D}Strong {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_bulky']/@name" ><xsl:attribute name="name">{=2k8qk1KD}Bulky {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_quick']/@name" ><xsl:attribute name="name">{=YuzBp6p4}Quick {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_fast']/@name" ><xsl:attribute name="name">{=D1eK25tu}Fast {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_slow']/@name" ><xsl:attribute name="name">{=NX2FkbdC}Slow {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_sickly']/@name" ><xsl:attribute name="name">{=ICfSXUvV}Sickly {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_aneamic']/@name" ><xsl:attribute name="name">{=Rxt7m2Sl}Aneamic {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_timid']/@name" ><xsl:attribute name="name">{=nSILI9b9}Timid {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_cowardly']/@name" ><xsl:attribute name="name">{=gsNgwoAq}Cowardly {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_healthy']/@name" ><xsl:attribute name="name">{=NuViWQIf}Healthy {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_docile']/@name" ><xsl:attribute name="name">{=XyaeTnrM}Docile {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_gentle']/@name" ><xsl:attribute name="name">{=egOcNUMs}Gentle {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_swayback']/@name" ><xsl:attribute name="name">{=OOtfJCaJ}Swayback {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='war_horse_purebred']/@name" ><xsl:attribute name="name">{=MC29cHra}Purebred {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_lean']/@name" ><xsl:attribute name="name">{=cmNJ45Xl}Lean {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_stubborn']/@name" ><xsl:attribute name="name">{=DXzpdjAq}Stubborn {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_headstrong']/@name" ><xsl:attribute name="name">{=yIZDvo8I}Headstrong {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_brave']/@name" ><xsl:attribute name="name">{=uh2w0Ehh}Brave {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_fierce']/@name" ><xsl:attribute name="name">{=Bb618GDp}Fierce {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_strong']/@name" ><xsl:attribute name="name">{=wIcAgF0D}Strong {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_bulky']/@name" ><xsl:attribute name="name">{=2k8qk1KD}Bulky {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_quick']/@name" ><xsl:attribute name="name">{=YuzBp6p4}Quick {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_fast']/@name" ><xsl:attribute name="name">{=D1eK25tu}Fast {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_slow']/@name" ><xsl:attribute name="name">{=NX2FkbdC}Slow {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_sickly']/@name" ><xsl:attribute name="name">{=ICfSXUvV}Sickly {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_aneamic']/@name" ><xsl:attribute name="name">{=Rxt7m2Sl}Aneamic {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_timid']/@name" ><xsl:attribute name="name">{=nSILI9b9}Timid {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_cowardly']/@name" ><xsl:attribute name="name">{=gsNgwoAq}Cowardly {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_healthy']/@name" ><xsl:attribute name="name">{=NuViWQIf}Healthy {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_docile']/@name" ><xsl:attribute name="name">{=XyaeTnrM}Docile {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_gentle']/@name" ><xsl:attribute name="name">{=egOcNUMs}Gentle {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_swayback']/@name" ><xsl:attribute name="name">{=OOtfJCaJ}Swayback {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='noble_horse_purebred']/@name" ><xsl:attribute name="name">{=MC29cHra}Purebred {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='lame_pack_horse']/@name" ><xsl:attribute name="name">{=geUpgQI5}Lame {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='lame_horse']/@name" ><xsl:attribute name="name">{=geUpgQI5}Lame {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='lame_war_horse']/@name" ><xsl:attribute name="name">{=geUpgQI5}Lame {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='lame_noble_horse']/@name" ><xsl:attribute name="name">{=geUpgQI5}Lame {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='companion_horse']/@name" ><xsl:attribute name="name">{=y3TvYqhG}Old {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='companion_weapon']/@name" ><xsl:attribute name="name">{=l7QEpVwU}Rusty {ITEMNAME}</xsl:attribute></xsl:template>
    <xsl:template match="ItemModifier[@id='companion_armor']/@name" ><xsl:attribute name="name">{=5yVgXqQr}Worn {ITEMNAME}</xsl:attribute></xsl:template>
</xsl:stylesheet>