<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output version="1.0" omit-xml-declaration="yes" encoding="UTF-8" indent="yes"/>
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
  <!-- entries should be split into multiple files to avoid the exception that says "syntax is too 'complex'" caused by very inconveninent Microsoft Csharp native XSLT parser library.  -->
  <xsl:template match="NPCCharacter[@id='lord_1_chiba_8']/@name" ><xsl:attribute name="name">{=RUVHqSha}Masatane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chiba_9']/@name" ><xsl:attribute name="name">{=r8PNf9r5}Tanenaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chiba_10']/@name" ><xsl:attribute name="name">{=L4V95dkR}Tanetoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_oda']/@name" ><xsl:attribute name="name">{=N0wdIy1B}Ujiharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_oda_1']/@name" ><xsl:attribute name="name">{=vC6z8WVM}Hazuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_2_oda_2']/@name" ><xsl:attribute name="name">{=oBXKUC02}Masaharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_2_oda_3']/@name" ><xsl:attribute name="name">{=lIMwYkmk}Keimyou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_oda_4']/@name" ><xsl:attribute name="name">{=73thINiW}Tomoharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_oda_5']/@name" ><xsl:attribute name="name">{=40uzrYwA}Moriharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_oda_6']/@name" ><xsl:attribute name="name">{=KDNrkROu}Koma</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_oda_7']/@name" ><xsl:attribute name="name">{=73thINiW}Tomoharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_oda_8']/@name" ><xsl:attribute name="name">{=QYDzg3jA}Riku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_oda_9']/@name" ><xsl:attribute name="name">{=73thINiW}Tomoharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kogakubo']/@name" ><xsl:attribute name="name">{=tCf4lIPu}Yoshiuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kogakubo_1']/@name" ><xsl:attribute name="name">{=NxaysxUC}Jyoko-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kogakubo_2']/@name" ><xsl:attribute name="name">{=O06DIhu2}Haruuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kogakubo_3']/@name" ><xsl:attribute name="name">{=xKCKGPUy}Houshun-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kogakubo_4']/@name" ><xsl:attribute name="name">{=9zqTKcqA}Fujimasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kogakubo_5']/@name" ><xsl:attribute name="name">{=2cUjpzfQ}Teruuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kogakubo_6']/@name" ><xsl:attribute name="name">{=8doVlvNw}Iekuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kogakubo_7']/@name" ><xsl:attribute name="name">{=olSVCZmf}Sato</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sano']/@name" ><xsl:attribute name="name">{=7JhWt0Cr}Masatsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sano_1']/@name" ><xsl:attribute name="name">{=OjtJRVA8}Moto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sano_2']/@name" ><xsl:attribute name="name">{=DkDMVX0S}Yasutsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sano_3']/@name" ><xsl:attribute name="name">{=aVzIfT5b}Kousen-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sano_4']/@name" ><xsl:attribute name="name">{=jTPsXTQs}Munetsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sano_5']/@name" ><xsl:attribute name="name">{=CimHJY3v}Chikatsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sano_6']/@name" ><xsl:attribute name="name">{=HxOIq1UO}Toyotsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sano_7']/@name" ><xsl:attribute name="name">{=TtRVEzF9}Jyoumei-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sano_8']/@name" ><xsl:attribute name="name">{=OjNzZ4z7}Fusatsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yuki']/@name" ><xsl:attribute name="name">{=peuTgDWX}Harutomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yuki_1']/@name" ><xsl:attribute name="name">{=2axdqLeU}Shoko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yuki_2']/@name" ><xsl:attribute name="name">{=l7gGIVfb}Teruko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yuki_3']/@name" ><xsl:attribute name="name">{=KaW2u7Wt}Tsuruko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yuki_4']/@name" ><xsl:attribute name="name">{=3dRiCHIH}Kuniko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi']/@name" ><xsl:attribute name="name">{=WNXdlC6n}Yoshihiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_1']/@name" ><xsl:attribute name="name">{=mF93OB0Z}Maki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_2']/@name" ><xsl:attribute name="name">{=Vjv0jhtU}Yoshitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_3']/@name" ><xsl:attribute name="name">{=6pWBEhfi}Saka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_4']/@name" ><xsl:attribute name="name">{=1VsYAGf0}Takamoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_5']/@name" ><xsl:attribute name="name">{=Sl8tIOAe}Tame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_6']/@name" ><xsl:attribute name="name">{=ZOyxIYLt}Takatsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_7']/@name" ><xsl:attribute name="name">{=RZW4u1bw}Kuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_8']/@name" ><xsl:attribute name="name">{=BijTmjLN}Yoshimasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_9']/@name" ><xsl:attribute name="name">{=mSLw5dla}Hisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_10']/@name" ><xsl:attribute name="name">{=ojHJapKr}Yoshiyori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_11']/@name" ><xsl:attribute name="name">{=XsI6P4Lw}Hama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_12']/@name" ><xsl:attribute name="name">{=Ae4oJ078}Tane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satomi_13']/@name" ><xsl:attribute name="name">{=BLEI9odB}Toyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki']/@name" ><xsl:attribute name="name">{=3u6MPLG6}Noritoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_1']/@name" ><xsl:attribute name="name">{=wTQEOpa7}Kaname</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_2']/@name" ><xsl:attribute name="name">{=eCgQgJ32}Tokitada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_3']/@name" ><xsl:attribute name="name">{=AWwPQ7GP}Kine</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_4']/@name" ><xsl:attribute name="name">{=r9bbr3VW}Tokimichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_5']/@name" ><xsl:attribute name="name">{=NClTemsw}Chie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_6']/@name" ><xsl:attribute name="name">{=y968PY0G}Tokinari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_7']/@name" ><xsl:attribute name="name">{=10oV0mMQ}Saki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_8']/@name" ><xsl:attribute name="name">{=jysbc6Uf}Tokikatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_9']/@name" ><xsl:attribute name="name">{=FxCpKg3G}Fusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_10']/@name" ><xsl:attribute name="name">{=MHd8ZnPH}Tokihide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_11']/@name" ><xsl:attribute name="name">{=P3Qi7ksg}Yoritoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_masaki_12']/@name" ><xsl:attribute name="name">{=UkMRMuYI}Tokitomi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_sakai']/@name" ><xsl:attribute name="name">{=EnNxr4sS}Taneharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_sakai_1']/@name" ><xsl:attribute name="name">{=L3rcTXEN}Keirin-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_sakai_2']/@name" ><xsl:attribute name="name">{=JgzJTQRD}Yasuharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_utsunomiya']/@name" ><xsl:attribute name="name">{=4UF3c1YO}Hirotsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_utsunomiya_1']/@name" ><xsl:attribute name="name">{=k8YjNpOk}Nanryo-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_utsunomiya_2']/@name" ><xsl:attribute name="name">{=YMsdSa5O}Kunitsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_haga']/@name" ><xsl:attribute name="name">{=gwB9W7mm}Takasada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_haga_1']/@name" ><xsl:attribute name="name">{=J0VnbU4a}Tama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_haga_2']/@name" ><xsl:attribute name="name">{=0xmB7XJS}Takakage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_haga_3']/@name" ><xsl:attribute name="name">{=l2brrFCq}Chiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_haga_4']/@name" ><xsl:attribute name="name">{=WO5zvxR8}Takatsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_haga_5']/@name" ><xsl:attribute name="name">{=tGEgf2XE}Miki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasama']/@name" ><xsl:attribute name="name">{=7vqf8p1x}Mikitsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasama_1']/@name" ><xsl:attribute name="name">{=B55gNGt8}Sue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasama_2']/@name" ><xsl:attribute name="name">{=GhX1cQFn}Tsunaie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasama_3']/@name" ><xsl:attribute name="name">{=u6pL0K8t}Kiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasama_4']/@name" ><xsl:attribute name="name">{=qs5YLGCM}Sakon</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satake']/@name" ><xsl:attribute name="name">{=IpGWXGXO}Yoshishige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satake_1']/@name" ><xsl:attribute name="name">{=lTEN0uBO}Hoju-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_satake_2']/@name" ><xsl:attribute name="name">{=lEBzZaFW}Yoshiaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_satake_3']/@name" ><xsl:attribute name="name">{=cyPZnisM}Kotoku-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satake_4']/@name" ><xsl:attribute name="name">{=cS0BYmEj}Yoshihisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satake_5']/@name" ><xsl:attribute name="name">{=O91iIET8}Akane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satake_6']/@name" ><xsl:attribute name="name">{=TO3KcPYq}Yoshitane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satake_7']/@name" ><xsl:attribute name="name">{=di3hvLje}Yoshitsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_satake_8']/@name" ><xsl:attribute name="name">{=RlQJPV7D}Chitose</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_edo']/@name" ><xsl:attribute name="name">{=f5XYXxSk}Michimasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_edo_1']/@name" ><xsl:attribute name="name">{=tLFdyt4x}Seishou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_edo_2']/@name" ><xsl:attribute name="name">{=isJ2mg9v}Shigemichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_daijo']/@name" ><xsl:attribute name="name">{=pRzOVEbH}Sadakuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_daijo_1']/@name" ><xsl:attribute name="name">{=iK6pKdiD}Fumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_daijo_2']/@name" ><xsl:attribute name="name">{=JrCw7IOL}Yoshimoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_daijo_3']/@name" ><xsl:attribute name="name">{=ad2F8T2d}Rensho-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_daijo_4']/@name" ><xsl:attribute name="name">{=mWRFq0Y2}Tsuneharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_daijo_5']/@name" ><xsl:attribute name="name">{=RHgM2Jbk}Hana</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashima']/@name" ><xsl:attribute name="name">{=fFzatPZB}Ujimiki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kashima_1']/@name" ><xsl:attribute name="name">{=P0Rdtbsk}Harutoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kashima_2']/@name" ><xsl:attribute name="name">{=lK0BVLKk}Myouke-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashima_3']/@name" ><xsl:attribute name="name">{=e3yhg6Dv}Yoshikiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashima_4']/@name" ><xsl:attribute name="name">{=wOWbGCUg}Nami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashima_5']/@name" ><xsl:attribute name="name">{=Nc8F0LEf}Sadanobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashima_6']/@name" ><xsl:attribute name="name">{=xuJSkGe4}Chiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashima_7']/@name" ><xsl:attribute name="name">{=wGuR0ntw}Kiyohide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashima_8']/@name" ><xsl:attribute name="name">{=aYVxNbSo}Sai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashima_9']/@name" ><xsl:attribute name="name">{=g1hC3I76}Michiharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashima_10']/@name" ><xsl:attribute name="name">{=iqtWNEZR}Sae</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nasu']/@name" ><xsl:attribute name="name">{=oRMj5Dw4}Suketane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nasu_1']/@name" ><xsl:attribute name="name">{=Niu6EEIX}Toyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nasu_2']/@name" ><xsl:attribute name="name">{=BiJQ3gwj}Sukeharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nasu_3']/@name" ><xsl:attribute name="name">{=vgzjShtW}Masa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akamatsu']/@name" ><xsl:attribute name="name">{=kLlP5rni}Yoshisuke</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akamatsu_1']/@name" ><xsl:attribute name="name">{=tUcpDeTS}Azami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akamatsu_2']/@name" ><xsl:attribute name="name">{=nR1sGRoK}Norifusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kodera']/@name" ><xsl:attribute name="name">{=pRDHDfAf}Masamoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kodera_1']/@name" ><xsl:attribute name="name">{=YrKWMZru}Kame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kodera_2']/@name" ><xsl:attribute name="name">{=AptV40KY}Norimoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kodera_3']/@name" ><xsl:attribute name="name">{=awh97eY4}Beni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kodera_4']/@name" ><xsl:attribute name="name">{=qaSYtI7f}Ujimoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kodera_5']/@name" ><xsl:attribute name="name">{=964hRB7s}Kasuga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda']/@name" ><xsl:attribute name="name">{=uq93RE5H}Yoshitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_1']/@name" ><xsl:attribute name="name">{=zFfxKok8}Mitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_2']/@name" ><xsl:attribute name="name">{=q2wWaf6n}Mototaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_3']/@name" ><xsl:attribute name="name">{=vpp0X2di}Masu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_4']/@name" ><xsl:attribute name="name">{=nbMsupjp}Nagamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_5']/@name" ><xsl:attribute name="name">{=WBljkXLV}Toshitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_6']/@name" ><xsl:attribute name="name">{=tPBBMN4Z}Toshinori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_7']/@name" ><xsl:attribute name="name">{=qgu18aBw}Naoyuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_8']/@name" ><xsl:attribute name="name">{=jqDkyoQZ}Kayo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_9']/@name" ><xsl:attribute name="name">{=Oew1Bf9P}Kine</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuroda_10']/@name" ><xsl:attribute name="name">{=FZ1Eq6lh}Fuku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bessho']/@name" ><xsl:attribute name="name">{=So1hDGim}Yasuharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bessho_1']/@name" ><xsl:attribute name="name">{=vbW4lVBo}Azuma</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_bessho_2']/@name" ><xsl:attribute name="name">{=apqhx41m}Nariharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_bessho_3']/@name" ><xsl:attribute name="name">{=dO3CawFk}Nanzen-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bessho_4']/@name" ><xsl:attribute name="name">{=Brly3Pam}Nagaharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bessho_5']/@name" ><xsl:attribute name="name">{=VYrrxnX9}Tomoyuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bessho_6']/@name" ><xsl:attribute name="name">{=nbMsupjp}Nagamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bessho_7']/@name" ><xsl:attribute name="name">{=gzC7F4fo}Yoshichika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bessho_8']/@name" ><xsl:attribute name="name">{=PVVSjRbo}Kashi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bessho_9']/@name" ><xsl:attribute name="name">{=qRHfzyUs}Shigemune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bessho_10']/@name" ><xsl:attribute name="name">{=MYV9KYo1}Seri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsunaga']/@name" ><xsl:attribute name="name">{=pyD59qMo}Hisahide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsunaga_1']/@name" ><xsl:attribute name="name">{=pvqqQutQ}Kasumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsunaga_2']/@name" ><xsl:attribute name="name">{=0VHC3xFH}Hisamichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsunaga_3']/@name" ><xsl:attribute name="name">{=Boxu3rYM}Wakaba</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui']/@name" ><xsl:attribute name="name">{=Xe63ilYA}Junkei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui_1']/@name" ><xsl:attribute name="name">{=sTM8QM4l}Taka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_tsutsui_2']/@name" ><xsl:attribute name="name">{=us2k9KPi}Junkou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_tsutsui_3']/@name" ><xsl:attribute name="name">{=L3NzXFr3}Saya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_tsutsui_4']/@name" ><xsl:attribute name="name">{=pnoyota2}Junshou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui_5']/@name" ><xsl:attribute name="name">{=v8k486Cv}Okata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui_6']/@name" ><xsl:attribute name="name">{=kZUzygaP}Junkoku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui_7']/@name" ><xsl:attribute name="name">{=D6cW9BRv}Koharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui_8']/@name" ><xsl:attribute name="name">{=vwBchbKt}Sadatsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui_9']/@name" ><xsl:attribute name="name">{=YP2fV2hW}Toshihiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui_10']/@name" ><xsl:attribute name="name">{=pAupiXnj}Tai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui_11']/@name" ><xsl:attribute name="name">{=z8vSvDSj}Junsai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsutsui_12']/@name" ><xsl:attribute name="name">{=bPdxO4MG}Hiroyuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_atagi']/@name" ><xsl:attribute name="name">{=3Cbdw30u}Nobuyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_atagi_1']/@name" ><xsl:attribute name="name">{=QZU9vMWY}Sawa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_atagi_2']/@name" ><xsl:attribute name="name">{=M8CaIjW3}Fuyuyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_atagi_3']/@name" ><xsl:attribute name="name">{=pDYIBBAa}Keiten-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_atagi_4']/@name" ><xsl:attribute name="name">{=DakzCL2f}Kiyoyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ashikaga']/@name" ><xsl:attribute name="name">{=Iqa3v7D1}Yoshiaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ashikaga_1']/@name" ><xsl:attribute name="name">{=Cxfk22gK}Sako</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ashikaga_2']/@name" ><xsl:attribute name="name">{=FlzkbFch}Yoshiharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ashikaga_3']/@name" ><xsl:attribute name="name">{=o05gJRtq}Keijyu-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ashikaga_4']/@name" ><xsl:attribute name="name">{=lhA4QmHy}Yoshiteru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ashikaga_5']/@name" ><xsl:attribute name="name">{=hsD5bJui}Daiyou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ashikaga_6']/@name" ><xsl:attribute name="name">{=dKcLiTvb}Yoshihide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hosokawa']/@name" ><xsl:attribute name="name">{=DavzUQup}Fujitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hosokawa_1']/@name" ><xsl:attribute name="name">{=EmiPhqA0}Jyakou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hosokawa_2']/@name" ><xsl:attribute name="name">{=HQiKv4QF}Tadaoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hosokawa_3']/@name" ><xsl:attribute name="name">{=DtWZ2i3N}Okimoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hosokawa_4']/@name" ><xsl:attribute name="name">{=iYqL2Vy6}Sen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hosokawa_5']/@name" ><xsl:attribute name="name">{=7oUfZNuF}Iya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_issiki']/@name" ><xsl:attribute name="name">{=CHalr5aK}Yoshimichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_issiki_1']/@name" ><xsl:attribute name="name">{=ruz4z36n}Tunako</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_issiki_2']/@name" ><xsl:attribute name="name">{=CzufOZcO}Yoshiyuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_issiki_3']/@name" ><xsl:attribute name="name">{=RurSjEyY}Keitoku-In</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_issiki_4']/@name" ><xsl:attribute name="name">{=K0rUvzyH}Yoshisada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_issiki_5']/@name" ><xsl:attribute name="name">{=Ez9wouSk}Yoshikiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_issiki_6']/@name" ><xsl:attribute name="name">{=JD9quZid}Haruko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamana']/@name" ><xsl:attribute name="name">{=oNEiBB2d}Suketoyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamana_1']/@name" ><xsl:attribute name="name">{=kJXoV9Pb}Tomoko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yamana_2']/@name" ><xsl:attribute name="name">{=NmILYBIw}Munetoyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamana_3']/@name" ><xsl:attribute name="name">{=nMjExeXI}Yoshichika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamana_4']/@name" ><xsl:attribute name="name">{=QbkbZH6B}Akihiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hatakeyama']/@name" ><xsl:attribute name="name">{=vs49SDks}Akitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_hatakeyama_1']/@name" ><xsl:attribute name="name">{=BeVxuHbe}Masakuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_hatakeyama_2']/@name" ><xsl:attribute name="name">{=eHD3yI8F}Seiko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hatakeyama_3']/@name" ><xsl:attribute name="name">{=0TdWVoYC}Takamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hatakeyama_4']/@name" ><xsl:attribute name="name">{=9QUwXAo6}Fusako</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hatakeyama_5']/@name" ><xsl:attribute name="name">{=kYtWhJo4}Yuko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hatakeyama_6']/@name" ><xsl:attribute name="name">{=ACqEvloB}Masahisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasumi']/@name" ><xsl:attribute name="name">{=PbADW8O5}Munefusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasumi_1']/@name" ><xsl:attribute name="name">{=JrNemg5t}Yata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasumi_2']/@name" ><xsl:attribute name="name">{=iMqha8Z4}Tomonaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasumi_3']/@name" ><xsl:attribute name="name">{=Rrbu472n}Nobukuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasumi_4']/@name" ><xsl:attribute name="name">{=wCCzDL2D}Chie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yukawa']/@name" ><xsl:attribute name="name">{=fcAG1QqW}Naoharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yukawa_1']/@name" ><xsl:attribute name="name">{=3QhK8vOe}Komatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yukawa_2']/@name" ><xsl:attribute name="name">{=WCJsiBsB}Naomitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yukawa_3']/@name" ><xsl:attribute name="name">{=rCZzutl7}Koumyou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yukawa_4']/@name" ><xsl:attribute name="name">{=QQ62CWn2}Nobuharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yukawa_5']/@name" ><xsl:attribute name="name">{=Bqky19ae}Hiroharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yukawa_6']/@name" ><xsl:attribute name="name">{=NbKeRcPM}Kageharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honganji']/@name" ><xsl:attribute name="name">{=vVdUl9kZ}Kennyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honganji_1']/@name" ><xsl:attribute name="name">{=uhGVlVcb}Nyosyun-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honganji_2']/@name" ><xsl:attribute name="name">{=ZHgHiq5g}Kyounyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honganji_3']/@name" ><xsl:attribute name="name">{=dLk4Mfmb}Kenson</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ganshoji']/@name" ><xsl:attribute name="name">{=CGMTB5IR}Syoui</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ganshoji_1']/@name" ><xsl:attribute name="name">{=RqrjjOwd}Shoumyou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ganshoji_2']/@name" ><xsl:attribute name="name">{=dcTmgzR2}Kennin</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_rokkaku']/@name" ><xsl:attribute name="name">{=KyBM4EGe}Yoshikata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_rokkaku_1']/@name" ><xsl:attribute name="name">{=YKfuhIdz}Shizuno</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_rokkaku_2']/@name" ><xsl:attribute name="name">{=5c4QE4T3}Yoshiharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_rokkaku_3']/@name" ><xsl:attribute name="name">{=f4nYiBuo}Tomoe</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_rokkaku_4']/@name" ><xsl:attribute name="name">{=0TCCnJ52}Yoshisada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_rokkaku_5']/@name" ><xsl:attribute name="name">{=ejRgtgY3}Chizuru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_gamou']/@name" ><xsl:attribute name="name">{=rUBu7S4M}Katahide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_gamou_1']/@name" ><xsl:attribute name="name">{=3d9HHjwb}Mitsuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_gamou_2']/@name" ><xsl:attribute name="name">{=FD9LbBC5}Ujisato</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_gamou_3']/@name" ><xsl:attribute name="name">{=GM8rv4Ak}Shigesato</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_gamou_4']/@name" ><xsl:attribute name="name">{=SuEovhqt}Tomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_gamou_5']/@name" ><xsl:attribute name="name">{=2wRgcvgX}Sana</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_azai']/@name" ><xsl:attribute name="name">{=iZkMYp72}Nagamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_azai_1']/@name" ><xsl:attribute name="name">{=rvDsCUpk}Ichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_azai_2']/@name" ><xsl:attribute name="name">{=qIzG5074}Hisamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_azai_3']/@name" ><xsl:attribute name="name">{=RF8JjIdu}Ako</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_azai_4']/@name" ><xsl:attribute name="name">{=Av28pOpi}Masamoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_azai_5']/@name" ><xsl:attribute name="name">{=VBrMcD42}Masayuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_todo']/@name" ><xsl:attribute name="name">{=A73fNqDB}Torataka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_todo_1']/@name" ><xsl:attribute name="name">{=wATMO4SF}Ayame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_todo_2']/@name" ><xsl:attribute name="name">{=ZkYr4Q04}Takatora</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_todo_3']/@name" ><xsl:attribute name="name">{=MRwSxq1k}Takanori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_todo_4']/@name" ><xsl:attribute name="name">{=6F2ikYXs}Fuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_todo_5']/@name" ><xsl:attribute name="name">{=VejCmIYn}Tsuta</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_isono']/@name" ><xsl:attribute name="name">{=kHIiTY6k}Kazumasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_isono_1']/@name" ><xsl:attribute name="name">{=aNr0aTAb}Ayame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_isono_2']/@name" ><xsl:attribute name="name">{=5wrVt0wH}Yukinobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_isono_3']/@name" ><xsl:attribute name="name">{=BzIGHgCx}Masanaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akao']/@name" ><xsl:attribute name="name">{=WvVFYg9z}Kiyotsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akao_1']/@name" ><xsl:attribute name="name">{=eqrjET0Q}Kiru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akao_2']/@name" ><xsl:attribute name="name">{=HGBst1md}Kiyofuyu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akao_3']/@name" ><xsl:attribute name="name">{=quPWUb7d}Yuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda']/@name" ><xsl:attribute name="name">{=wqjEk0zZ}Nobunaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_1']/@name" ><xsl:attribute name="name">{=aCLFE9fV}Nou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_oda_2']/@name" ><xsl:attribute name="name">{=6fpqsOCb}Nobuhide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_3']/@name" ><xsl:attribute name="name">{=WKW8zGVB}Dota-gezen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_4']/@name" ><xsl:attribute name="name">{=3k7drsea}Nobutada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_5']/@name" ><xsl:attribute name="name">{=0JPVJU94}Nobukatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_6']/@name" ><xsl:attribute name="name">{=ITHpOHC1}Nobutaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_7']/@name" ><xsl:attribute name="name">{=XFJfiBaw}Nobuhiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_8']/@name" ><xsl:attribute name="name">{=Asdctfqh}Nobukane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_9']/@name" ><xsl:attribute name="name">{=7whQnMzi}Hisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_10']/@name" ><xsl:attribute name="name">{=8BhkuRWC}Nagamasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oda_11']/@name" ><xsl:attribute name="name">{=Jn0K7PNf}Sei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kinoshita']/@name" ><xsl:attribute name="name">{=gqt0QIl5}Hideyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kinoshita_1']/@name" ><xsl:attribute name="name">{=wmriGx9z}Nene</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kinoshita_2']/@name" ><xsl:attribute name="name">{=9zZwFuMM}Yaemon</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kinoshita_3']/@name" ><xsl:attribute name="name">{=YCkbvrI5}Naka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kinoshita_4']/@name" ><xsl:attribute name="name">{=iu9a9wWD}Hidenaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kinoshita_5']/@name" ><xsl:attribute name="name">{=nerTByza}Tae</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kinoshita_6']/@name" ><xsl:attribute name="name">{=eBydZ8UR}Tomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kinoshita_7']/@name" ><xsl:attribute name="name">{=LmtF2OEL}Yoshifusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kinoshita_8']/@name" ><xsl:attribute name="name">{=78tz8gaC}Asahi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kinoshita_9']/@name" ><xsl:attribute name="name">{=TDa0KpyV}Yoshinari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shibata']/@name" ><xsl:attribute name="name">{=Z6OKK1nA}Katsuie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shibata_1']/@name" ><xsl:attribute name="name">{=v5MbvJJH}Sae</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shibata_2']/@name" ><xsl:attribute name="name">{=VuO1uj5T}Katsusato</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shibata_3']/@name" ><xsl:attribute name="name">{=6DNrUFap}Katsutada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shibata_4']/@name" ><xsl:attribute name="name">{=JmzS3yub}Katsumasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shibata_5']/@name" ><xsl:attribute name="name">{=3tcSrSZS}Katsutoyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shibata_6']/@name" ><xsl:attribute name="name">{=DEN7nvP0}Katsutoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakuma']/@name" ><xsl:attribute name="name">{=rV9fvZPM}Nobumori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakuma_1']/@name" ><xsl:attribute name="name">{=zccColGo}Tsutsuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sakuma_2']/@name" ><xsl:attribute name="name">{=1Auqkl29}Nobuharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakuma_3']/@name" ><xsl:attribute name="name">{=llqgj9e4}Koushou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakuma_4']/@name" ><xsl:attribute name="name">{=9GlIn49d}Nobuhide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakuma_5']/@name" ><xsl:attribute name="name">{=I0VAUSEq}Nobutoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takigawa']/@name" ><xsl:attribute name="name">{=sc9FjP2E}Kazumasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takigawa_1']/@name" ><xsl:attribute name="name">{=C67lGw7D}Kano</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takigawa_2']/@name" ><xsl:attribute name="name">{=eYxUCzZl}Kazutada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takigawa_3']/@name" ><xsl:attribute name="name">{=iMc2zSg8}Kazutoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takigawa_4']/@name" ><xsl:attribute name="name">{=Ey1d5pwc}Kiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takigawa_5']/@name" ><xsl:attribute name="name">{=wCNIpIB4}Sana</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuki']/@name" ><xsl:attribute name="name">{=WbWoS8l0}Yoshitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuki_1']/@name" ><xsl:attribute name="name">{=RsCPH7VE}Nami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuki_2']/@name" ><xsl:attribute name="name">{=rwB3k83J}Naritaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kuki_3']/@name" ><xsl:attribute name="name">{=99ZeqWCB}Shima</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake']/@name" ><xsl:attribute name="name">{=JTzieEQH}Tomonori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_1']/@name" ><xsl:attribute name="name">{=cq8VOWkD}Matsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kitabatake_2']/@name" ><xsl:attribute name="name">{=H2FsCrUJ}Harutomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kitabatake_3']/@name" ><xsl:attribute name="name">{=f3DEuNXC}Kuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_4']/@name" ><xsl:attribute name="name">{=PtY5O0oR}Tomofusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_5']/@name" ><xsl:attribute name="name">{=wbEuy9q4}Tomofuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_6']/@name" ><xsl:attribute name="name">{=P1AgeXcD}Chikanari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_7']/@name" ><xsl:attribute name="name">{=Q50kWDFW}Yuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_8']/@name" ><xsl:attribute name="name">{=xz7VtMCD}Tsuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_9']/@name" ><xsl:attribute name="name">{=dme8x5FX}Fumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_10']/@name" ><xsl:attribute name="name">{=XWDbAYjm}Tomomasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_11']/@name" ><xsl:attribute name="name">{=sPSLtwCr}Ten</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_12']/@name" ><xsl:attribute name="name">{=B4oQXBYc}Nagamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kitabatake_13']/@name" ><xsl:attribute name="name">{=KvnteUqO}Tomochika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_11']/@name" ><xsl:attribute name="name">{=X2sLljXc}Takahisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_shimazu_2']/@name" ><xsl:attribute name="name">{=DHsiGvld}Sessou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu']/@name" ><xsl:attribute name="name">{=7s4dxFt3}Yoshihisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_1']/@name" ><xsl:attribute name="name">{=gv3wrMe3}Enshin-inden</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_2']/@name" ><xsl:attribute name="name">{=czGM0U4X}Ōhira</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_3']/@name" ><xsl:attribute name="name">{=yquLAovd}Shinjo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_4']/@name" ><xsl:attribute name="name">{=p9NeUjUw}Yoshihiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_5']/@name" ><xsl:attribute name="name">{=8fj2kDNi}Kochou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_6']/@name" ><xsl:attribute name="name">{=vI3iTRAa}Yachi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_7']/@name" ><xsl:attribute name="name">{=PRLxNKTC}Toshihisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_8']/@name" ><xsl:attribute name="name">{=BgW75GXX}Ume</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_9']/@name" ><xsl:attribute name="name">{=bCEeQkkF}Iehisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimazu_10']/@name" ><xsl:attribute name="name">{=LvRRedWW}Nagi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_10']/@name" ><xsl:attribute name="name">{=xTIL6Lf0}Tadaaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_11']/@name" ><xsl:attribute name="name">{=j5q1b0ZO}Murasaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin']/@name" ><xsl:attribute name="name">{=UdtsY26m}Tadaao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_1']/@name" ><xsl:attribute name="name">{=a5ytpM6f}Shizuku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_2']/@name" ><xsl:attribute name="name">{=gJxQjIhn}Tadamune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_3']/@name" ><xsl:attribute name="name">{=60Aeo2HK}Kusafuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_4']/@name" ><xsl:attribute name="name">{=t99JjHho}Harunari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_5']/@name" ><xsl:attribute name="name">{=YiDzP43I}Tadatane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_6']/@name" ><xsl:attribute name="name">{=ltdCwtlK}Hikari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_7']/@name" ><xsl:attribute name="name">{=CtPTpklz}Hisanobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_8']/@name" ><xsl:attribute name="name">{=0PAYYOYo}Sasayuri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ijuin_9']/@name" ><xsl:attribute name="name">{=t99JjHho}Harunari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hongo_4']/@name" ><xsl:attribute name="name">{=9j0CtAEy}Tadachika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hongo_5']/@name" ><xsl:attribute name="name">{=Fm7HitzI}Hasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hongo']/@name" ><xsl:attribute name="name">{=a7Bus3qz}Tokihisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hongo_1']/@name" ><xsl:attribute name="name">{=YBDz0cMr}Haru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hongo_2']/@name" ><xsl:attribute name="name">{=SpjpkISo}Sukehisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hongo_3']/@name" ><xsl:attribute name="name">{=jp7XzhCN}Tadatora</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kimotsuki_1']/@name" ><xsl:attribute name="name">{=aUgD8yWg}Kanetsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kimotsuki_6']/@name" ><xsl:attribute name="name">{=A8Iz9ZZT}Ominami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kimotsuki']/@name" ><xsl:attribute name="name">{=J1KrYoB2}Yoshikane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kimotsuki_1']/@name" ><xsl:attribute name="name">{=blCzYNBm}Takashiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kimotsuki_2']/@name" ><xsl:attribute name="name">{=xk81zGz1}Kanemiki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kimotsuki_3']/@name" ><xsl:attribute name="name">{=Ywbdn3tH}Izumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kimotsuki_4']/@name" ><xsl:attribute name="name">{=Z7OeNcGK}Kanesuke</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kimotsuki_5']/@name" ><xsl:attribute name="name">{=N5VldQQt}Kanemori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_tanegashima_1']/@name" ><xsl:attribute name="name">{=SqR0Mu6S}Shigetoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tanegashima_4']/@name" ><xsl:attribute name="name">{=XCSdjqll}Suiren</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tanegashima']/@name" ><xsl:attribute name="name">{=qyCDkM5m}Tokitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tanegashima_1']/@name" ><xsl:attribute name="name">{=QF3JI70b}Nishi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tanegashima_2']/@name" ><xsl:attribute name="name">{=zy3vzsD2}Hisatoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tanegashima_3']/@name" ><xsl:attribute name="name">{=V9EPyj3M}Nippou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami']/@name" ><xsl:attribute name="name">{=L1wnB6pW}Hisazumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_1']/@name" ><xsl:attribute name="name">{=ewils0Dz}Kita</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_2']/@name" ><xsl:attribute name="name">{=92pspLlK}Hisatoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_3']/@name" ><xsl:attribute name="name">{=qb7Z1U5h}Hisamichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_4']/@name" ><xsl:attribute name="name">{=QeuaL3cf}Tsuta</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_5']/@name" ><xsl:attribute name="name">{=V6jIFhcG}Tadakatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_6']/@name" ><xsl:attribute name="name">{=TLxsl5iX}Mina</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kawakami_7']/@name" ><xsl:attribute name="name">{=k3CpNDG5}Hisaaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_8']/@name" ><xsl:attribute name="name">{=eCNnvQM4}Ai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_9']/@name" ><xsl:attribute name="name">{=ODtiTkOv}Hisatoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_10']/@name" ><xsl:attribute name="name">{=CaWfkO0p}Yoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_11']/@name" ><xsl:attribute name="name">{=Ht8hAJcl}Tadatomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_12']/@name" ><xsl:attribute name="name">{=emI5NXQu}Yae</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_13']/@name" ><xsl:attribute name="name">{=Ax7ZFxHb}Tadakata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_14']/@name" ><xsl:attribute name="name">{=fexWXUPu}Tadae</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_15']/@name" ><xsl:attribute name="name">{=HjyxWWhy}Hisatomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawakami_16']/@name" ><xsl:attribute name="name">{=u6vPOWe7}Sachi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai']/@name" ><xsl:attribute name="name">{=KhqU55r0}Kunikane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai_1']/@name" ><xsl:attribute name="name">{=3vLKX0xu}Matsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai_2']/@name" ><xsl:attribute name="name">{=JMd4a3AO}Kakuken</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai_3']/@name" ><xsl:attribute name="name">{=5iU3TdnF}Tomi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai_4']/@name" ><xsl:attribute name="name">{=Otv143ry}Tsunekane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai_5']/@name" ><xsl:attribute name="name">{=ELhVncx1}Hideaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai_6']/@name" ><xsl:attribute name="name">{=o1LMD9ny}Ise</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai_7']/@name" ><xsl:attribute name="name">{=vXMcTPtw}Satokane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai_8']/@name" ><xsl:attribute name="name">{=tb6JqqiB}Shige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uwai_9']/@name" ><xsl:attribute name="name">{=yU00LUuA}Aki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niro']/@name" ><xsl:attribute name="name">{=dcCPC5JH}Tadamoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niro_1']/@name" ><xsl:attribute name="name">{=uOiEhWdc}Shima</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niro_2']/@name" ><xsl:attribute name="name">{=VHFYSwnu}Tadataka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niro_3']/@name" ><xsl:attribute name="name">{=we21zLIb}Tadamasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niro_4']/@name" ><xsl:attribute name="name">{=8SPgT8lv}Kaya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niro_5']/@name" ><xsl:attribute name="name">{=JhlzLqNk}Yasuhisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niro_6']/@name" ><xsl:attribute name="name">{=B8yOZDB1}Sue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niro_7']/@name" ><xsl:attribute name="name">{=wqENKt24}Hisaatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niro_8']/@name" ><xsl:attribute name="name">{=NkRdYQ2Z}Tadahide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ryuzoji_1']/@name" ><xsl:attribute name="name">{=TVY3ysQM}Chikaie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_2']/@name" ><xsl:attribute name="name">{=pKRWlHY2}Keigin-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji']/@name" ><xsl:attribute name="name">{=EJFqZ0Re}Takanobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_1']/@name" ><xsl:attribute name="name">{=GJikOBTs}Aoi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_3']/@name" ><xsl:attribute name="name">{=IunQmBW8}Masaie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_4']/@name" ><xsl:attribute name="name">{=BpNWO1VW}Ietane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_5']/@name" ><xsl:attribute name="name">{=sLjMUtzo}Ienobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_6']/@name" ><xsl:attribute name="name">{=GJikOBTs}Aoi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_7']/@name" ><xsl:attribute name="name">{=dJrycT5U}Yasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_8']/@name" ><xsl:attribute name="name">{=Bun8uTcC}Nobukane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_9']/@name" ><xsl:attribute name="name">{=QoJqPtiQ}Shinobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_10']/@name" ><xsl:attribute name="name">{=1U8b3UIP}Nobuaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_11']/@name" ><xsl:attribute name="name">{=tITu2Ofm}Naganobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_12']/@name" ><xsl:attribute name="name">{=jmFzBD6r}Satsuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_13']/@name" ><xsl:attribute name="name">{=oKY3txxT}Yasutoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_14']/@name" ><xsl:attribute name="name">{=uPz1Xvdn}Kikyou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ryuzoji_15']/@name" ><xsl:attribute name="name">{=UOIYnsPP}Shinkou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuura']/@name" ><xsl:attribute name="name">{=IuaPQ3Jf}Takanobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuura_1']/@name" ><xsl:attribute name="name">{=8SJ7vUnX}Suiran</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuura_2']/@name" ><xsl:attribute name="name">{=5vMME1MH}Shigenobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuura_3']/@name" ><xsl:attribute name="name">{=MRn4lWn1}Shī</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuura_4']/@name" ><xsl:attribute name="name">{=ZjiY3efx}Koreaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuura_5']/@name" ><xsl:attribute name="name">{=XUnjjMXE}Chikashi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuura_6']/@name" ><xsl:attribute name="name">{=GVedNuqp}Kanoko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuura_7']/@name" ><xsl:attribute name="name">{=SNVHLgax}Ayame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nabeshima']/@name" ><xsl:attribute name="name">{=25ZutWwE}Kiyofusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nabeshima_1']/@name" ><xsl:attribute name="name">{=3WB4WKAb}Kakei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nabeshima_2']/@name" ><xsl:attribute name="name">{=v3bb1Q5X}Nobufusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nabeshima_4']/@name" ><xsl:attribute name="name">{=Jnx18tIy}Naoshige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nabeshima_5']/@name" ><xsl:attribute name="name">{=0YuKB1a0}Hikotsuru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nabeshima_6']/@name" ><xsl:attribute name="name">{=vHYZgp4m}Kiyoyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nabeshima_7']/@name" ><xsl:attribute name="name">{=b8DHDVJl}Iwagiri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saigo']/@name" ><xsl:attribute name="name">{=aBevKeGx}Sumitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saigo_1']/@name" ><xsl:attribute name="name">{=MLD6QUoN}Sada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saigo_2']/@name" ><xsl:attribute name="name">{=s2QgGxRbzM}Suminao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saigo_3']/@name" ><xsl:attribute name="name">{=0WWMrnLV}Mayumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saigo_4']/@name" ><xsl:attribute name="name">{=Duy1yvLw}Sumihisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saigo_5']/@name" ><xsl:attribute name="name">{=VhUaonxW}Sumimasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kumabe']/@name" ><xsl:attribute name="name">{=LfZC8oxt}Chikaie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kumabe_1']/@name" ><xsl:attribute name="name">{=YazRHukF}Inasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kumabe_2']/@name" ><xsl:attribute name="name">{=PJm0OEPx}Chikanaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kumabe_3']/@name" ><xsl:attribute name="name">{=Xup6gETO}Yamase</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kumabe_4']/@name" ><xsl:attribute name="name">{=vAL4CzPc}Chikayasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kumabe_5']/@name" ><xsl:attribute name="name">{=Vz6OtTyq}Shigefusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kumabe_6']/@name" ><xsl:attribute name="name">{=XbjCzJTi}Kiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kumabe_7']/@name" ><xsl:attribute name="name">{=W3XjwTmf}Chikafusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kumabe_8']/@name" ><xsl:attribute name="name">{=aACMcMnP}Akafuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_arima']/@name" ><xsl:attribute name="name">{=EALX2wiH}Yoshisada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_arima_1']/@name" ><xsl:attribute name="name">{=Zf2ThTMe}Utsugi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_arima_2']/@name" ><xsl:attribute name="name">{=bqlAf3Ep}Yoshizumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_arima_3']/@name" ><xsl:attribute name="name">{=8KGtAWLM}Kanoko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_arima_4']/@name" ><xsl:attribute name="name">{=P5bd2ucF}Yuri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_arima_5']/@name" ><xsl:attribute name="name">{=B67b5TXq}Chikashi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_arima_6']/@name" ><xsl:attribute name="name">{=HbzP5AAB}Harunobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_omura']/@name" ><xsl:attribute name="name">{=y7KNSSPN}Sumitada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_omura_1']/@name" ><xsl:attribute name="name">{=6VZ8rqKC}Oen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_omura_2']/@name" ><xsl:attribute name="name">{=qtwaI7LN}Yoshiaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_omura_3']/@name" ><xsl:attribute name="name">{=XqAwpT3d}Yuugao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_omura_4']/@name" ><xsl:attribute name="name">{=YgGJdujN}Shirasame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasutomi']/@name" ><xsl:attribute name="name">{=hPnLYYJO}Sadanao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasutomi_1']/@name" ><xsl:attribute name="name">{=UxSkwZcc}Fuse</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasutomi_2']/@name" ><xsl:attribute name="name">{=qjFeheme}sumiharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasutomi_3']/@name" ><xsl:attribute name="name">{=M9fL4iOG}Kesa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasutomi_4']/@name" ><xsl:attribute name="name">{=S9l95YBY}Sumiyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasutomi_5']/@name" ><xsl:attribute name="name">{=4hhMmQZv}Sumitoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasutomi_6']/@name" ><xsl:attribute name="name">{=gP7qZ1sx}Fuku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasutomi_7']/@name" ><xsl:attribute name="name">{=xzrz8EdV}Sumioki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yasutomi_8']/@name" ><xsl:attribute name="name">{=0u4eOAjF}Yumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fukuda']/@name" ><xsl:attribute name="name">{=99cmIBLl}Tadakane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fukuda_1']/@name" ><xsl:attribute name="name">{=IqQ6wbYX}Momo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fukuda_2']/@name" ><xsl:attribute name="name">{=3DxSAP5P}Kanetsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fukuda_3']/@name" ><xsl:attribute name="name">{=m9ddTE2d}Chise</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fukuda_4']/@name" ><xsl:attribute name="name">{=wq7KfqBC}Kanechika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fukuda_5']/@name" ><xsl:attribute name="name">{=5EDIHiUN}koshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_otomo_1']/@name" ><xsl:attribute name="name">{=TzTHrzds}Yoshiaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_otomo_2']/@name" ><xsl:attribute name="name">{=z3dbPelZ}Boujou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_otomo']/@name" ><xsl:attribute name="name">{=3AFE1DCF}Yoshishige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_otomo_1']/@name" ><xsl:attribute name="name">{=UIKx01xx}Nata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_otomo_2']/@name" ><xsl:attribute name="name">{=7sbPoa0a}Yoshimune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_otomo_3']/@name" ><xsl:attribute name="name">{=a5rohL3A}Chikaie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_otomo_4']/@name" ><xsl:attribute name="name">{=acpnamQM}Chikamori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_otomo_5']/@name" ><xsl:attribute name="name">{=HgdZp0Wl}Emi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_otomo_6']/@name" ><xsl:attribute name="name">{=5HotxjQe}Yuri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_otomo_7']/@name" ><xsl:attribute name="name">{=svKW968A}Chikasada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kii_5']/@name" ><xsl:attribute name="name">{=QhQNpW8c}Nagafusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kii_6']/@name" ><xsl:attribute name="name">{=vTJsC4OH}Aogiri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kii']/@name" ><xsl:attribute name="name">{=k92lOXHJ}Shigefusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kii_1']/@name" ><xsl:attribute name="name">{=teYikAqn}Yohira</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kii_2']/@name" ><xsl:attribute name="name">{=SqbUj7yq}Tomofusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kii_3']/@name" ><xsl:attribute name="name">{=bS8yxN7k}Masafusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kii_4']/@name" ><xsl:attribute name="name">{=iIKYURwu}Sukefusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kamachi']/@name" ><xsl:attribute name="name">{=ccbI0eaO}Akimori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kamachi_1']/@name" ><xsl:attribute name="name">{=l20Tre0E}Otsutsuru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kamachi_2']/@name" ><xsl:attribute name="name">{=mZZiN58r}Shigehisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kamachi_3']/@name" ><xsl:attribute name="name">{=4UMLD8VG}Shigenami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kamachi_4']/@name" ><xsl:attribute name="name">{=BQpT7Ot2}Tamatsuru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kamachi_5']/@name" ><xsl:attribute name="name">{=PhtIj0GH}Muneyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bekki']/@name" ><xsl:attribute name="name">{=NkAfByDU}Akitsura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bekki_1']/@name" ><xsl:attribute name="name">{=c5eoivff}Hatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bekki_2']/@name" ><xsl:attribute name="name">{=ovVdGXOn}Ginchiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_bekki_3']/@name" ><xsl:attribute name="name">{=ZlHul9Zt}Shigetsura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_bekki_4']/@name" ><xsl:attribute name="name">{=HQk5m5lx}Chikayuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_bekki_5']/@name" ><xsl:attribute name="name">{=b9gzn2hY}Akikata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshihiro']/@name" ><xsl:attribute name="name">{=lKbRz6eD}Akitada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshihiro_1']/@name" ><xsl:attribute name="name">{=0Y43uQrL}Sekkoku-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshihiro_2']/@name" ><xsl:attribute name="name">{=Sj68FhWp}Shigenobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshihiro_3']/@name" ><xsl:attribute name="name">{=gcJhVyAL}Toki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshihiro_4']/@name" ><xsl:attribute name="name">{=lpweWPGd}Muneyuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshihiro_5']/@name" ><xsl:attribute name="name">{=LeuCYp9y}Munekazu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshihiro_6']/@name" ><xsl:attribute name="name">{=dmMvttf2}Munesada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshihiro_7']/@name" ><xsl:attribute name="name">{=m19CQd6x}Kanoko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshihiro_8']/@name" ><xsl:attribute name="name">{=1yDEuokr}Yamayuri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takahashi']/@name" ><xsl:attribute name="name">{=E46uMtvl}Shigetada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takahashi_1']/@name" ><xsl:attribute name="name">{=j1RRxloG}Kaname</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takahashi_2']/@name" ><xsl:attribute name="name">{=2GaQofVb}Munetora</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takahashi_3']/@name" ><xsl:attribute name="name">{=uBCOrdQV}Kai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takahashi_4']/@name" ><xsl:attribute name="name">{=Z2GCOUtm}Ochiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takahashi_5']/@name" ><xsl:attribute name="name">{=x6R93cIi}Kaya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_aso']/@name" ><xsl:attribute name="name">{=NYlbLufq}Koremasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_aso_1']/@name" ><xsl:attribute name="name">{=fo7AmZvZ}Hinageshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_aso_2']/@name" ><xsl:attribute name="name">{=VwVczw6S}Koretane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_aso_3']/@name" ><xsl:attribute name="name">{=LRFeUoJn}Azami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kai']/@name" ><xsl:attribute name="name">{=9rmhZ9SX}Souun</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kai_1']/@name" ><xsl:attribute name="name">{=0YMRJmlt}Oume</xsl:attribute></xsl:template>
</xsl:stylesheet>