<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output version="1.0" omit-xml-declaration="yes" encoding="UTF-8" indent="yes"/>
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
  <!-- entries should be split into multiple files to avoid the exception that says "syntax is too 'complex'" caused by very inconveninent Microsoft Csharp native XSLT parser library.  -->
  <xsl:template match="NPCCharacter[@id='lord_1_asakura']/@name" ><xsl:attribute name="name">{=yAchbdS0}Yoshikage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asakura_1']/@name" ><xsl:attribute name="name">{=92Plru2R}Shouko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asakura_2']/@name" ><xsl:attribute name="name">{=PeZKtHl4}Kageakira</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asakura_3']/@name" ><xsl:attribute name="name">{=10GS8hh6}Fusako</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamazaki']/@name" ><xsl:attribute name="name">{=zHzGUOYl}Yoshiie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamazaki_1']/@name" ><xsl:attribute name="name">{=nTqCvCWT}Icho</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yamazaki_2']/@name" ><xsl:attribute name="name">{=byu8D8HC}Nagayoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yamazaki_3']/@name" ><xsl:attribute name="name">{=maSOGXrZ}Shoumyou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamazaki_4']/@name" ><xsl:attribute name="name">{=MxewE2UB}Yoshitake</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamazaki_5']/@name" ><xsl:attribute name="name">{=X5qVfju7}Yoshinobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamazaki_6']/@name" ><xsl:attribute name="name">{=K5vrtqxW}Kogiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamazaki_7']/@name" ><xsl:attribute name="name">{=LrsfIPm8}Naganori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mizoe']/@name" ><xsl:attribute name="name">{=FjN0SPCO}Kageyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mizoe_1']/@name" ><xsl:attribute name="name">{=edubnNQh}Tome</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mizoe_2']/@name" ><xsl:attribute name="name">{=DGRdBFWD}Nagayasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mizoe_3']/@name" ><xsl:attribute name="name">{=YiN0QUpV}Oku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mizoe_4']/@name" ><xsl:attribute name="name">{=htAMl2eb}Nagauji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mizoe_5']/@name" ><xsl:attribute name="name">{=m28lOKlG}Ben'ei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeba']/@name" ><xsl:attribute name="name">{=jGCv6Uil}Kagemasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeba_1']/@name" ><xsl:attribute name="name">{=jaNkGPsJ}Sei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_maeba_2']/@name" ><xsl:attribute name="name">{=Bhxb1sTw}Kagesada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_maeba_3']/@name" ><xsl:attribute name="name">{=aCNFnmpJ}Keiko-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeba_4']/@name" ><xsl:attribute name="name">{=ZctOTbV9}Katsuhide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeba_5']/@name" ><xsl:attribute name="name">{=FXVHs6Rl}Yoshitsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeba_6']/@name" ><xsl:attribute name="name">{=pTApzZjo}Kyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anekouji']/@name" ><xsl:attribute name="name">{=8NfTd97s}Yoshiyori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anekouji_1']/@name" ><xsl:attribute name="name">{=khSBd7oA}Hagi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anekouji_2']/@name" ><xsl:attribute name="name">{=zgHNjeAc}Yoritsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anekouji_3']/@name" ><xsl:attribute name="name">{=Ozp8uVH2}Mei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anekouji_4']/@name" ><xsl:attribute name="name">{=3t8eBlK9}Nobutsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anekouji_5']/@name" ><xsl:attribute name="name">{=50rxSxoL}Hidetsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anekouji_6']/@name" ><xsl:attribute name="name">{=YS6J1DSx}Suetsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anekouji_7']/@name" ><xsl:attribute name="name">{=ChLVdmm5}Hisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anekouji_8']/@name" ><xsl:attribute name="name">{=fllPpIHN}Tei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miki']/@name" ><xsl:attribute name="name">{=rmn0keBY}Kunitsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miki_1']/@name" ><xsl:attribute name="name">{=pOV36qLw}Kise</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miki_2']/@name" ><xsl:attribute name="name">{=Mwzg4d94}Akitsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miki_3']/@name" ><xsl:attribute name="name">{=BUaB2CAs}Yuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uchigashima']/@name" ><xsl:attribute name="name">{=reQL1Reg}Ujimasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uchigashima_1']/@name" ><xsl:attribute name="name">{=ZAVB59DI}Tsune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_uchigashima_2']/@name" ><xsl:attribute name="name">{=x5bCceO3}Ujitoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_uchigashima_3']/@name" ><xsl:attribute name="name">{=0wP2NHjx}Shinkou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uchigashima_4']/@name" ><xsl:attribute name="name">{=BFpJOH9B}Ujiyuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uchigashima_5']/@name" ><xsl:attribute name="name">{=oWMNADvQ}Chise</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uchigashima_6']/@name" ><xsl:attribute name="name">{=VkHrE7QN}Ujinori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uchigashima_7']/@name" ><xsl:attribute name="name">{=8Njl5F1v}Ujifusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uchigashima_8']/@name" ><xsl:attribute name="name">{=XOj9DW3l}Ujichika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uchigashima_9']/@name" ><xsl:attribute name="name">{=iDawiizs}Sue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma']/@name" ><xsl:attribute name="name">{=nO8nbFeD}Rairen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_1']/@name" ><xsl:attribute name="name">{=YJnCp2Ng}Tenshou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_2']/@name" ><xsl:attribute name="name">{=ELQ0jKOQ}Rairyou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_3']/@name" ><xsl:attribute name="name">{=L6k0BihZ}Munekiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_4']/@name" ><xsl:attribute name="name">{=6EDf32QW}Rengoyoku-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_5']/@name" ><xsl:attribute name="name">{=JkG837Se}Saiko-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_6']/@name" ><xsl:attribute name="name">{=dTVh9niZ}Raishou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_7']/@name" ><xsl:attribute name="name">{=uWUgquZb}Keian-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_8']/@name" ><xsl:attribute name="name">{=ttOsDrht}Nakataka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_9']/@name" ><xsl:attribute name="name">{=v3KNHiGz}Raitan</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_10']/@name" ><xsl:attribute name="name">{=vJhGvDMI}Koutoku-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shimotsuma_11']/@name" ><xsl:attribute name="name">{=xnKhOXA6}Rairyū</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shichiri']/@name" ><xsl:attribute name="name">{=Eh5FcIr3}Yorichika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shichiri_1']/@name" ><xsl:attribute name="name">{=HBQgU0KK}Renmyou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shichiri_2']/@name" ><xsl:attribute name="name">{=YxadjwHu}Shoukou-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shichiri_3']/@name" ><xsl:attribute name="name">{=EDp1Ip1P}Tenshin-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_notohatakeyama']/@name" ><xsl:attribute name="name">{=zzPufQWW}Yoshinori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_notohatakeyama_1']/@name" ><xsl:attribute name="name">{=Uq5GEfN0}Keiko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_notohatakeyama_2']/@name" ><xsl:attribute name="name">{=uWclrYkK}Yoshitsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_notohatakeyama_3']/@name" ><xsl:attribute name="name">{=L7cUrjNA}Keisei-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_notohatakeyama_4']/@name" ><xsl:attribute name="name">{=MzeRfL4G}Yoshitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_cho']/@name" ><xsl:attribute name="name">{=Ykm1ZcKt}Tsugutsura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_cho_1']/@name" ><xsl:attribute name="name">{=54P6AoCQ}Kine</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_cho_2']/@name" ><xsl:attribute name="name">{=BH4qApyf}Tsunatsura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_cho_3']/@name" ><xsl:attribute name="name">{=mxxEQmKL}Chiho</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_cho_4']/@name" ><xsl:attribute name="name">{=Pd02cWIP}Yoshitsura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yusa']/@name" ><xsl:attribute name="name">{=6UGnlTvg}Tsugumitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yusa_1']/@name" ><xsl:attribute name="name">{=mtpjGuCC}Sue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yusa_2']/@name" ><xsl:attribute name="name">{=JoEyAqpB}Morimitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nukui']/@name" ><xsl:attribute name="name">{=zfaBVnTz}Kagetaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nukui_1']/@name" ><xsl:attribute name="name">{=PkUrZWtb}Kane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_nukui_2']/@name" ><xsl:attribute name="name">{=9LHg8tSs}Tsugumune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_nukui_3']/@name" ><xsl:attribute name="name">{=PySBB1Zv}En</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nukui_4']/@name" ><xsl:attribute name="name">{=1zGy3GLa}Nagamori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nukui_5']/@name" ><xsl:attribute name="name">{=uNnrQHZs}Mitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda']/@name" ><xsl:attribute name="name">{=8ZM8IWIL}Toshiie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_1']/@name" ><xsl:attribute name="name">{=X37Mxlbd}Matsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_maeda_2']/@name" ><xsl:attribute name="name">{=XY7oOzvJ}Toshiharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_3']/@name" ><xsl:attribute name="name">{=16wGsj58}Chorei-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_4']/@name" ><xsl:attribute name="name">{=gUfblyxg}Toshinaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_5']/@name" ><xsl:attribute name="name">{=HNxdD6bx}Kou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_6']/@name" ><xsl:attribute name="name">{=KkMduqEv}Shizu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_7']/@name" ><xsl:attribute name="name">{=37zNtHHt}Toshihisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_8']/@name" ><xsl:attribute name="name">{=pm7cjBgT}Tomi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_9']/@name" ><xsl:attribute name="name">{=DCmCs5kM}Toshimasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_10']/@name" ><xsl:attribute name="name">{=qPinCtuZ}Yasukatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_11']/@name" ><xsl:attribute name="name">{=o6NRDplP}Aki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_12']/@name" ><xsl:attribute name="name">{=6cjX925Z}Toshiyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_13']/@name" ><xsl:attribute name="name">{=pVCYrGIa}Hidetsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_14']/@name" ><xsl:attribute name="name">{=JJRp7jcS}Kai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_maeda_15']/@name" ><xsl:attribute name="name">{=EAijrwwg}Toshihide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akechi']/@name" ><xsl:attribute name="name">{=FOuyGkLb}Mitsuhide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akechi_1']/@name" ><xsl:attribute name="name">{=WM3E1lhn}Hiroko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akechi_2']/@name" ><xsl:attribute name="name">{=YMwxPbeL}Mitsuyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akechi_3']/@name" ><xsl:attribute name="name">{=ADvtqTtw}Ei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akechi_4']/@name" ><xsl:attribute name="name">{=nvlUciWt}Mitsutada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akechi_5']/@name" ><xsl:attribute name="name">{=lQFaxxIJ}Toku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akechi_6']/@name" ><xsl:attribute name="name">{=CkNry5Sa}Hidemitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akechi_7']/@name" ><xsl:attribute name="name">{=1R17d0b8}Tama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niwa']/@name" ><xsl:attribute name="name">{=SKcB9YGC}Nagahide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niwa_1']/@name" ><xsl:attribute name="name">{=L05jsNrJ}Fuse</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niwa_2']/@name" ><xsl:attribute name="name">{=3qxBLbew}Masa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_niwa_3']/@name" ><xsl:attribute name="name">{=XLXbashl}Take</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ikeda']/@name" ><xsl:attribute name="name">{=duYGUbdI}Tsuneoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ikeda_1']/@name" ><xsl:attribute name="name">{=Ry3yD8SW}Zen'o-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ikeda_2']/@name" ><xsl:attribute name="name">{=7PtkKC5L}Tsunetoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ikeda_3']/@name" ><xsl:attribute name="name">{=a8fhiErH}Youtoku-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ikeda_4']/@name" ><xsl:attribute name="name">{=mZrml2Ov}Motosuke</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ikeda_5']/@name" ><xsl:attribute name="name">{=VylcfU2r}Terumasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ikeda_6']/@name" ><xsl:attribute name="name">{=qiIMdezD}Sen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tokugawa']/@name" ><xsl:attribute name="name">{=lhX5bcSW}Ieyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tokugawa_1']/@name" ><xsl:attribute name="name">{=0VxHt8iA}Tsukiyama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tokugawa_2']/@name" ><xsl:attribute name="name">{=KPL2cW75}Nobuyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tokugawa_3']/@name" ><xsl:attribute name="name">{=zHBbLO7U}Kame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tokugawa_4']/@name" ><xsl:attribute name="name">{=T7whzugC}Toku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda']/@name" ><xsl:attribute name="name">{=ttXuqvjP}Tadakatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_1']/@name" ><xsl:attribute name="name">{=wTE64EJ5}Hisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_2']/@name" ><xsl:attribute name="name">{=pzKWxRoL}Shigetsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_3']/@name" ><xsl:attribute name="name">{=BDFqD8yc}Sane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_4']/@name" ><xsl:attribute name="name">{=9DY2gzT7}Toshimasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_5']/@name" ><xsl:attribute name="name">{=OfpHBzpT}Chie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_6']/@name" ><xsl:attribute name="name">{=oGp9i8O6}Masanobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_7']/@name" ><xsl:attribute name="name">{=NIaOPKNj}Shī</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_8']/@name" ><xsl:attribute name="name">{=dID6ayTM}Masazumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_9']/@name" ><xsl:attribute name="name">{=9gdMPNbq}Masashige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honda_10']/@name" ><xsl:attribute name="name">{=7TBN1cQm}Tsune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakakibara']/@name" ><xsl:attribute name="name">{=A8v1L7R2}Yasumasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sakakibara_1']/@name" ><xsl:attribute name="name">{=vXdi14Dt}Nagamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sakakibara_2']/@name" ><xsl:attribute name="name">{=RuAChgqW}Yuzu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakakibara_3']/@name" ><xsl:attribute name="name">{=46c1t4F9}Kiyomasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakai']/@name" ><xsl:attribute name="name">{=GgnkEyTV}Tadatsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakai_1']/@name" ><xsl:attribute name="name">{=rrFghyqq}Usui</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakai_2']/@name" ><xsl:attribute name="name">{=A626l0Gm}Ietsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakai_3']/@name" ><xsl:attribute name="name">{=60W9WGjN}Fuu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ii']/@name" ><xsl:attribute name="name">{=PsuvJwcR}Naotora</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ii_1']/@name" ><xsl:attribute name="name">{=eeY8Wqqk}Naochika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ii_2']/@name" ><xsl:attribute name="name">{=xF9RihZf}Hiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ii_3']/@name" ><xsl:attribute name="name">{=usy9v6yR}Naomasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ii_4']/@name" ><xsl:attribute name="name">{=hznl27AL}Takase</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo']/@name" ><xsl:attribute name="name">{=4RHGzzz5}Tadakazu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo_1']/@name" ><xsl:attribute name="name">{=tIwfNdAU}Kaede</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo_2']/@name" ><xsl:attribute name="name">{=bp0JE7lD}Tadayo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo_3']/@name" ><xsl:attribute name="name">{=p9CqbJC5}Koto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo_4']/@name" ><xsl:attribute name="name">{=e0sW01xt}Tadachika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo_5']/@name" ><xsl:attribute name="name">{=ulF9F7Xm}Tadanari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo_6']/@name" ><xsl:attribute name="name">{=CAxVPHIx}Tadasuke</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo_7']/@name" ><xsl:attribute name="name">{=0Kytj7yK}Amane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo_8']/@name" ><xsl:attribute name="name">{=2nmhylAz}Tadatame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okubo_9']/@name" ><xsl:attribute name="name">{=HrxOrz25}Tadataka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hattori']/@name" ><xsl:attribute name="name">{=3fFAXVUS}Masanari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hattori_1']/@name" ><xsl:attribute name="name">{=Q3mn8U0b}Naga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_hattori_2']/@name" ><xsl:attribute name="name">{=fdPNZSo0}Yasunaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_hattori_3']/@name" ><xsl:attribute name="name">{=9eEzhPnB}Kiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hattori_4']/@name" ><xsl:attribute name="name">{=YnqiSByctO}Masanari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_hattori_5']/@name" ><xsl:attribute name="name">{=So0Nn6DM}Yasutoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hattori_6']/@name" ><xsl:attribute name="name">{=cYVbPLNq}Tsuru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hattori_7']/@name" ><xsl:attribute name="name">{=mdI2AIhF}Yasuhide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hattori_8']/@name" ><xsl:attribute name="name">{=6S59Qnpu}Yasumasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hattori_9']/@name" ><xsl:attribute name="name">{=vSW8NxqF}Haru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hattori_10']/@name" ><xsl:attribute name="name">{=ksrFELDK}Yasunari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uesugi']/@name" ><xsl:attribute name="name">{=qNbyhQaj}Kenshin</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_uesugi_1']/@name" ><xsl:attribute name="name">{=MLZq7awV}Tamekage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uesugi_2']/@name" ><xsl:attribute name="name">{=QwRXJCmI}Seigan-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uesugi_3']/@name" ><xsl:attribute name="name">{=8Iv9ecNC}Aya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_uesugi_4']/@name" ><xsl:attribute name="name">{=axhJs6IX}Masakage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uesugi_5']/@name" ><xsl:attribute name="name">{=RWQCCx4o}Kagekatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uesugi_6']/@name" ><xsl:attribute name="name">{=shVCPmCc}Madoka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_irobe']/@name" ><xsl:attribute name="name">{=Cg9EoY4r}Katsunaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_irobe_1']/@name" ><xsl:attribute name="name">{=6z9bSHa7}Azuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_irobe_2']/@name" ><xsl:attribute name="name">{=luKhUhXh}Akinaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_irobe_3']/@name" ><xsl:attribute name="name">{=bSqEzLcJ}Nagazane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kakizaki']/@name" ><xsl:attribute name="name">{=XgIyv7bL}Kageie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kakizaki_1']/@name" ><xsl:attribute name="name">{=wOt7PGWW}Kiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kakizaki_2']/@name" ><xsl:attribute name="name">{=RNZWsztn}Haruie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kakizaki_3']/@name" ><xsl:attribute name="name">{=UX8SD6t0}Matsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_naoe']/@name" ><xsl:attribute name="name">{=CQuYOgRo}Kagetsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_naoe_1']/@name" ><xsl:attribute name="name">{=9zniFw6a}Ran</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_naoe_2']/@name" ><xsl:attribute name="name">{=aizCBXYO}Sen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_shibata']/@name" ><xsl:attribute name="name">{=4yJ1D3Lk}Nagaatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_shibata_1']/@name" ><xsl:attribute name="name">{=N5nPQ9iT}Saki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_2_shibata_2']/@name" ><xsl:attribute name="name">{=jCqzvM9s}Tsunasada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_2_shibata_3']/@name" ><xsl:attribute name="name">{=r6hPxS8L}Tenshou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_shibata_4']/@name" ><xsl:attribute name="name">{=Vnl5lCcr}Shigeie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_shibata_5']/@name" ><xsl:attribute name="name">{=msDDZ9zQ}Kotake</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_jinbo']/@name" ><xsl:attribute name="name">{=lTQNNnd4}Nagamoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_jinbo_1']/@name" ><xsl:attribute name="name">{=hVSyu2fz}Asahi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_jinbo_2']/@name" ><xsl:attribute name="name">{=TbOZeUsx}Nagazumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_jinbo_3']/@name" ><xsl:attribute name="name">{=6HJv9QVb}Naka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_jinbo_4']/@name" ><xsl:attribute name="name">{=rctAbfBY}Nagakuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_jinbo_5']/@name" ><xsl:attribute name="name">{=Bs8eZQFC}Sayo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami']/@name" ><xsl:attribute name="name">{=W5wJGTC8}Yoshikiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami_1']/@name" ><xsl:attribute name="name">{=MESMSv9a}Fune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami_2']/@name" ><xsl:attribute name="name">{=yGFHfoKI}Yoshikatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami_3']/@name" ><xsl:attribute name="name">{=TCUOLBRT}Sada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami_4']/@name" ><xsl:attribute name="name">{=5O1LWXJp}Yoshiteru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami_5']/@name" ><xsl:attribute name="name">{=RuCWEn4I}Kyou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami_6']/@name" ><xsl:attribute name="name">{=6qygzS4a}Yoshikuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami_7']/@name" ><xsl:attribute name="name">{=kQx9hdpB}Tai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami_8']/@name" ><xsl:attribute name="name">{=H9SHda0i}Kunikiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_murakami_9']/@name" ><xsl:attribute name="name">{=subHFWkG}Kazu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honma']/@name" ><xsl:attribute name="name">{=qmR0GKfJ}Sadakane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honma_1']/@name" ><xsl:attribute name="name">{=DM691On9}Tsuta</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honma_2']/@name" ><xsl:attribute name="name">{=fMcQDpxT}Takatsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honma_3']/@name" ><xsl:attribute name="name">{=fy68erIy}Tomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honma_4']/@name" ><xsl:attribute name="name">{=wr8Xrdq3}Tsunayuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honma_5']/@name" ><xsl:attribute name="name">{=jKoS0rtx}Takaou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honjo']/@name" ><xsl:attribute name="name">{=Yb8Jirco}Shigenaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honjo_1']/@name" ><xsl:attribute name="name">{=NDluCjrj}Momiji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honjo_2']/@name" ><xsl:attribute name="name">{=Ng1qk1bc}Akinaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honjo_3']/@name" ><xsl:attribute name="name">{=9107Gylz}Saneyori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honjo_4']/@name" ><xsl:attribute name="name">{=7U80DoRY}Sagami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honjo_5']/@name" ><xsl:attribute name="name">{=5LpGgkPs}Hidetsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honjo_6']/@name" ><xsl:attribute name="name">{=1oAT3tap}Ise</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_honjo_7']/@name" ><xsl:attribute name="name">{=3MdGZMX4}Kageyori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda']/@name" ><xsl:attribute name="name">{=CmHdCNgW}Shingen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_1']/@name" ><xsl:attribute name="name">{=4i6fDyD8}Sanjou-no-kata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_takeda_2']/@name" ><xsl:attribute name="name">{=0W8I3WDW}Nobutora</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_takeda_3']/@name" ><xsl:attribute name="name">{=ypwKxiQu}Oi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_4']/@name" ><xsl:attribute name="name">{=86eH8vEV}Katsuyori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_5']/@name" ><xsl:attribute name="name">{=v3Z4a3yT}Nobukiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_6']/@name" ><xsl:attribute name="name">{=DaR7ks4O}Mari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_7']/@name" ><xsl:attribute name="name">{=oDOj9SD6}Kiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_8']/@name" ><xsl:attribute name="name">{=xpuvPs14}Matsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_9']/@name" ><xsl:attribute name="name">{=y03WXHuV}Nobukado</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_10']/@name" ><xsl:attribute name="name">{=XTtGyQDW}Oboro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_11']/@name" ><xsl:attribute name="name">{=08ToFFXf}Nobuzumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_12']/@name" ><xsl:attribute name="name">{=1TVdy9aJ}Nobuaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_13']/@name" ><xsl:attribute name="name">{=AnDrohq6}Tsuyu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_14']/@name" ><xsl:attribute name="name">{=zTstz8YU}Nobutomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takeda_15']/@name" ><xsl:attribute name="name">{=Kr9vJDJr}Koharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_baba']/@name" ><xsl:attribute name="name">{=mf6qRfQ9}Nobuharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_baba_1']/@name" ><xsl:attribute name="name">{=g6O5UTIU}Shinkou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_baba_2']/@name" ><xsl:attribute name="name">{=sUPNtt42}Masafusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_baba_3']/@name" ><xsl:attribute name="name">{=DHiUrEoe}Tatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_baba_4']/@name" ><xsl:attribute name="name">{=fcNnjXsC}Nobuyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_baba_5']/@name" ><xsl:attribute name="name">{=3qyP1ctn}Fumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_baba_6']/@name" ><xsl:attribute name="name">{=gz7lL74b}Fusakatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_baba_7']/@name" ><xsl:attribute name="name">{=njGs760D}Mai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kiso']/@name" ><xsl:attribute name="name">{=Hkshvmje}Yoshiyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kiso_1']/@name" ><xsl:attribute name="name">{=vbIJLnaE}Maki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kiso_2']/@name" ><xsl:attribute name="name">{=0glR6o3S}Yoshimasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kiso_3']/@name" ><xsl:attribute name="name">{=hCph1y6W}Mari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kiso_4']/@name" ><xsl:attribute name="name">{=Uh8eLrzj}Yoshitoyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kiso_5']/@name" ><xsl:attribute name="name">{=CST4VZ3y}Iwa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada']/@name" ><xsl:attribute name="name">{=nOD4Gqu3}Nobutsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_1']/@name" ><xsl:attribute name="name">{=LLDSUh4P}Kita</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_2']/@name" ><xsl:attribute name="name">{=wcz0nDz4}Yukitsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_3']/@name" ><xsl:attribute name="name">{=xCBCWoyE}Kyou'un-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_4']/@name" ><xsl:attribute name="name">{=Juq9azQr}Masateru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_5']/@name" ><xsl:attribute name="name">{=WVGige9a}Azuma</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_6']/@name" ><xsl:attribute name="name">{=kgkhqmWv}Masayuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_7']/@name" ><xsl:attribute name="name">{=8GNzUWme}Yamanote</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_8']/@name" ><xsl:attribute name="name">{=RxAnenAt}Nobuyuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_9']/@name" ><xsl:attribute name="name">{=SrBZhW62}Nobushige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sanada_10']/@name" ><xsl:attribute name="name">{=p6u25ahF}Nobutada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishina']/@name" ><xsl:attribute name="name">{=CGW3d2m1}Morinobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_nishina_1']/@name" ><xsl:attribute name="name">{=pMatiznR}Morimasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishina_2']/@name" ><xsl:attribute name="name">{=p5ZVom76}Sekishou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishina_3']/@name" ><xsl:attribute name="name">{=NxcRsCiG}Moritaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishina_4']/@name" ><xsl:attribute name="name">{=NMWHcNzI}Morikiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oyamada']/@name" ><xsl:attribute name="name">{=R2xuV24U}Nobushige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oyamada_1']/@name" ><xsl:attribute name="name">{=Dg5B2zhF}Momo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oyamada_2']/@name" ><xsl:attribute name="name">{=g45BojcX}Nobutsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oyamada_3']/@name" ><xsl:attribute name="name">{=zF6jIhMK}Harusuke</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anayama']/@name" ><xsl:attribute name="name">{=kJSK4wyx}Nobutada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_anayama_1']/@name" ><xsl:attribute name="name">{=aEtxWN2O}Fuchi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamagata']/@name" ><xsl:attribute name="name">{=foSkGqkk}Masakage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamagata_1']/@name" ><xsl:attribute name="name">{=HjUZWMTO}Yumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamagata_2']/@name" ><xsl:attribute name="name">{=YXIWbWf0}Masamitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamagata_3']/@name" ><xsl:attribute name="name">{=92oaxFYB}Hana</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamagata_4']/@name" ><xsl:attribute name="name">{=0mCx7j50}Masashige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamagata_5']/@name" ><xsl:attribute name="name">{=Yq8SOeXP}Masahisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamagata_6']/@name" ><xsl:attribute name="name">{=KDNU2gvn}Tsuku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamagata_7']/@name" ><xsl:attribute name="name">{=ecShe0I2}En</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasuga']/@name" ><xsl:attribute name="name">{=g4maTpNu}Toratsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasuga_1']/@name" ><xsl:attribute name="name">{=TYa3IRFt}Shige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasuga_2']/@name" ><xsl:attribute name="name">{=MpF2HDx9}Masazumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasuga_3']/@name" ><xsl:attribute name="name">{=Ha5aVxa5}Yuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasuga_4']/@name" ><xsl:attribute name="name">{=SMr29glZ}Masamoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasuga_5']/@name" ><xsl:attribute name="name">{=cZMqkGId}Masasada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_imagawa']/@name" ><xsl:attribute name="name">{=SJcxjwoG}Ujizane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_imagawa_1']/@name" ><xsl:attribute name="name">{=JaOi7kxn}Hayakawa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_imagawa_2']/@name" ><xsl:attribute name="name">{=PTuEiwT5}Sada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asahina']/@name" ><xsl:attribute name="name">{=6F0GOTMx}Yasutomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asahina_1']/@name" ><xsl:attribute name="name">{=iREsPn2R}Sawa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asahina_2']/@name" ><xsl:attribute name="name">{=LPbuuBT7}Yasumoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asahina_3']/@name" ><xsl:attribute name="name">{=tCqVkzwq}Nobuoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asahina_4']/@name" ><xsl:attribute name="name">{=TyQ6HZYx}Yui</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asahina_5']/@name" ><xsl:attribute name="name">{=OO1CZVQY}Nobuyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asahina_6']/@name" ><xsl:attribute name="name">{=OJ0Bt41g}Motonaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asahina_7']/@name" ><xsl:attribute name="name">{=QsBBAV6a}Munetoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fuji']/@name" ><xsl:attribute name="name">{=c9kHua0I}Nobutada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fuji_1']/@name" ><xsl:attribute name="name">{=Fo5zfzvM}Matsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fuji_2']/@name" ><xsl:attribute name="name">{=GtQEM4H1}Nobumichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fuji_3']/@name" ><xsl:attribute name="name">{=R6QFv61S}Yae</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fuji_4']/@name" ><xsl:attribute name="name">{=1dudFqAY}Nobushige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fuji_5']/@name" ><xsl:attribute name="name">{=BmHwTG2p}Kou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okabe']/@name" ><xsl:attribute name="name">{=R0oRncp7}Motonobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okabe_1']/@name" ><xsl:attribute name="name">{=P1UiQyME}Sakae</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_okabe_2']/@name" ><xsl:attribute name="name">{=r9MHER6o}Chikatsuma</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okabe_3']/@name" ><xsl:attribute name="name">{=mteALoQA}Myosen-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okabe_4']/@name" ><xsl:attribute name="name">{=jDEOJ3VU}Sanetaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okabe_5']/@name" ><xsl:attribute name="name">{=RGfPAqxo}Motoaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okabe_6']/@name" ><xsl:attribute name="name">{=9yB1OZBM}Masatsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okabe_7']/@name" ><xsl:attribute name="name">{=J8S3HAxP}Kame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okabe_8']/@name" ><xsl:attribute name="name">{=22eOrkcg}Nagamori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okabe_9']/@name" ><xsl:attribute name="name">{=FCzQSXcq}Nagaaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mori']/@name" ><xsl:attribute name="name">{=pK7A2Rp7}Terumoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mori_1']/@name" ><xsl:attribute name="name">{=fov5Mzy7}Motonari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mori_2']/@name" ><xsl:attribute name="name">{=DjUMn7At}Myokyu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mori_3']/@name" ><xsl:attribute name="name">{=14vUfETg}Takamoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mori_4']/@name" ><xsl:attribute name="name">{=BSWxMZFE}Ayaya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mori_5']/@name" ><xsl:attribute name="name">{=x08M6xh2}Motoaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mori_6']/@name" ><xsl:attribute name="name">{=HzJdFNL7}Hidekane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kobayakawa']/@name" ><xsl:attribute name="name">{=ljrQK9ik}Takakage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kobayakawa_1']/@name" ><xsl:attribute name="name">{=VQH0SYq0}Toida No Ōkata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa']/@name" ><xsl:attribute name="name">{=9BscWFYJ}Motoharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_1']/@name" ><xsl:attribute name="name">{=PqjmlE5W}Iwakuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_2']/@name" ><xsl:attribute name="name">{=QnqH5KZ0}Motonaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_3']/@name" ><xsl:attribute name="name">{=3OyxaM6M}Yomogi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_4']/@name" ><xsl:attribute name="name">{=0wrHmcK7}Hiroie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_5']/@name" ><xsl:attribute name="name">{=BrDafz9a}Tomi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_6']/@name" ><xsl:attribute name="name">{=akFMV6yS}Amane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_7']/@name" ><xsl:attribute name="name">{=UENAABaj}Tsuneyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_8']/@name" ><xsl:attribute name="name">{=BDvDn7EA}Awa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_9']/@name" ><xsl:attribute name="name">{=3PJdgQiO}Tsuneie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_10']/@name" ><xsl:attribute name="name">{=unkJIljQ}Momo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_11']/@name" ><xsl:attribute name="name">{=tZTNsQR1}Hina</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kikkawa_12']/@name" ><xsl:attribute name="name">{=9tqn5PPq}Tomoe</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshimi']/@name" ><xsl:attribute name="name">{=3gl90OC4}Masayori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshimi_1']/@name" ><xsl:attribute name="name">{=ujpvQZRt}Ōmiya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshimi_2']/@name" ><xsl:attribute name="name">{=tMK6TwxL}Hiroyori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshimi_3']/@name" ><xsl:attribute name="name">{=O6uSZlqz}Makomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshimi_4']/@name" ><xsl:attribute name="name">{=p4gAtQ44}Hiromasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshimi_5']/@name" ><xsl:attribute name="name">{=fFw7eVr9}Hagi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_naito']/@name" ><xsl:attribute name="name">{=eqnHNZTn}Takaharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_naito_1']/@name" ><xsl:attribute name="name">{=FjERkhTK}Ōmiya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_naito_2']/@name" ><xsl:attribute name="name">{=wREIyLQ0}Motoyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_nanjo_1']/@name" ><xsl:attribute name="name">{=fA2yEMQT}Munehiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_nanjo_2']/@name" ><xsl:attribute name="name">{=vsXnQaY3}Shoukoku-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanjo']/@name" ><xsl:attribute name="name">{=JBy4izdl}Motokiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanjo_1']/@name" ><xsl:attribute name="name">{=3t890NFw}Mukuge</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanjo_2']/@name" ><xsl:attribute name="name">{=IoiBIuNR}Mototsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanjo_3']/@name" ><xsl:attribute name="name">{=3WRBgvB5}Yukue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanjo_4']/@name" ><xsl:attribute name="name">{=Y4IdPEjO}Motoaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanjo_5']/@name" ><xsl:attribute name="name">{=Num8z5UZ}Nobumasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanjo_6']/@name" ><xsl:attribute name="name">{=JNbU5CCb}Tokiwa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanjo_7']/@name" ><xsl:attribute name="name">{=0LcWeO9q}Munenobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanjo_8']/@name" ><xsl:attribute name="name">{=0VdMZ0JH}Shima</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_misawa']/@name" ><xsl:attribute name="name">{=VUZ97dN1}Tamekiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_misawa_1']/@name" ><xsl:attribute name="name">{=U4DnOQh4}Kura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_misawa_2']/@name" ><xsl:attribute name="name">{=gYclqkoJ}Tametora</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_misawa_3']/@name" ><xsl:attribute name="name">{=WCuytuAF}Wase</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amano']/@name" ><xsl:attribute name="name">{=gzGocQQH}Takashige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amano_1']/@name" ><xsl:attribute name="name">{=e97cGhbY}Kitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amano_2']/@name" ><xsl:attribute name="name">{=VDpeZ1bz}Motoaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amano_3']/@name" ><xsl:attribute name="name">{=OCQRIum4}Naka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amano_4']/@name" ><xsl:attribute name="name">{=5v6c3AmS}Motosuke</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amano_5']/@name" ><xsl:attribute name="name">{=MQjGjSgA}Chise</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amano_6']/@name" ><xsl:attribute name="name">{=8ZbntjPj}Mototomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amano_7']/@name" ><xsl:attribute name="name">{=qU1saRSl}Motoyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amano_8']/@name" ><xsl:attribute name="name">{=Zrq9XCGa}Motonobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_murakami']/@name" ><xsl:attribute name="name">{=TmaAlQZ0}Takeyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_murakami_1']/@name" ><xsl:attribute name="name">{=YqOXyWEZ}Somefuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_murakami_2']/@name" ><xsl:attribute name="name">{=GdKyldZW}Motoyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_murakami_3']/@name" ><xsl:attribute name="name">{=wMYFNM6X}Konagi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_murakami_4']/@name" ><xsl:attribute name="name">{=BXLhyQKn}Michifusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_murakami_5']/@name" ><xsl:attribute name="name">{=N2Z8yCGx}Naoyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_murakami_6']/@name" ><xsl:attribute name="name">{=EHBZVYCj}Kohama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_murakami_7']/@name" ><xsl:attribute name="name">{=uIHSWACL}Yoshimichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_murakami_8']/@name" ><xsl:attribute name="name">{=MWaaoXcS}Suou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kawano_1']/@name" ><xsl:attribute name="name">{=dlXo3cfH}Michiharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_kawano_2']/@name" ><xsl:attribute name="name">{=s4Imj6GD}Seri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawano']/@name" ><xsl:attribute name="name">{=f846iOIo}Michinobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawano_1']/@name" ><xsl:attribute name="name">{=aNxr9NcV}Mukuge</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kawano_2']/@name" ><xsl:attribute name="name">{=tAxoidEM}Michinao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uragami']/@name" ><xsl:attribute name="name">{=wn4Z5851}Munekage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uragami_1']/@name" ><xsl:attribute name="name">{=ys5UK0RM}Shion</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uragami_2']/@name" ><xsl:attribute name="name">{=Vcpfb24L}Munetoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_uragami_3']/@name" ><xsl:attribute name="name">{=N1n8pWTZ}Tatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ukita_1']/@name" ><xsl:attribute name="name">{=4JsopToS}Okiie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ukita_2']/@name" ><xsl:attribute name="name">{=E1ylj5fW}Zenjo-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita']/@name" ><xsl:attribute name="name">{=FOH3wIT7}Naoie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_1']/@name" ><xsl:attribute name="name">{=0Gm8PH8I}Uzu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_2']/@name" ><xsl:attribute name="name">{=yEwFRYGg}Ai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_3']/@name" ><xsl:attribute name="name">{=EXLq4niV}Ran</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_4']/@name" ><xsl:attribute name="name">{=EFdrEfOJ}Tsukuha</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_5']/@name" ><xsl:attribute name="name">{=cqknUpXj}Kaya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_6']/@name" ><xsl:attribute name="name">{=Yc3JNSpo}Tadaie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_7']/@name" ><xsl:attribute name="name">{=HtkNPcxI}Nadeshiko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_8']/@name" ><xsl:attribute name="name">{=RTJSr2O7}Motoie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_9']/@name" ><xsl:attribute name="name">{=nAlhkml6}Akiie</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_10']/@name" ><xsl:attribute name="name">{=9rJmnygh}Shiramomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ukita_11']/@name" ><xsl:attribute name="name">{=Z173vNw9}Aofuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akashi']/@name" ><xsl:attribute name="name">{=y4yCzF20}Yukikatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akashi_1']/@name" ><xsl:attribute name="name">{=MBdD4EMq}Ashi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akashi_2']/@name" ><xsl:attribute name="name">{=Les0dY3I}Teruzumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akashi_3']/@name" ><xsl:attribute name="name">{=id3ouNCV}Akebi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_akashi_4']/@name" ><xsl:attribute name="name">{=Oh4D3H4n}Awa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amago']/@name" ><xsl:attribute name="name">{=cndf29xy}Katsuhisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amago_1']/@name" ><xsl:attribute name="name">{=3jEENNGd}Tamane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amago_2']/@name" ><xsl:attribute name="name">{=hJUC1nK9}Ujihisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amago_3']/@name" ><xsl:attribute name="name">{=Aa6selTk}Michihisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_amago_1']/@name" ><xsl:attribute name="name">{=yGggICSa}Sanehisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_amago_2']/@name" ><xsl:attribute name="name">{=e5jJlTcT}Seiryou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamanaka']/@name" ><xsl:attribute name="name">{=qYih12OY}Yukimori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamanaka_1']/@name" ><xsl:attribute name="name">{=npZ70oDb}Yura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yamanaka_2']/@name" ><xsl:attribute name="name">{=2qyQ5uu7}Yukitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yamanaka_1']/@name" ><xsl:attribute name="name">{=HhM0uBm3}Mitsuyuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yamanaka_2']/@name" ><xsl:attribute name="name">{=fdzr5fWf}Shunkei-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tatsuhara']/@name" ><xsl:attribute name="name">{=lDbNEfEh}Hisatsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tatsuhara_1']/@name" ><xsl:attribute name="name">{=WFQ0UuXw}Fuse</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tatsuhara_2']/@name" ><xsl:attribute name="name">{=07juHC01}Mitsutada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tatsuhara_3']/@name" ><xsl:attribute name="name">{=DFrIaaPX}Nami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata']/@name" ><xsl:attribute name="name">{=t4DRKSAY}Nobuzane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_1']/@name" ><xsl:attribute name="name">{=asA0b5mz}Tae</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_2']/@name" ><xsl:attribute name="name">{=6U06bX7V}Norishige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_3']/@name" ><xsl:attribute name="name">{=k7pTFu2E}Yumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_4']/@name" ><xsl:attribute name="name">{=SRa7FYKy}Nobutaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_5']/@name" ><xsl:attribute name="name">{=cy3gpggj}Yuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_6']/@name" ><xsl:attribute name="name">{=7lHBstOq}Nobuuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_7']/@name" ><xsl:attribute name="name">{=ayqIRS5x}Nobusada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_8']/@name" ><xsl:attribute name="name">{=K4rav43o}Masataka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_9']/@name" ><xsl:attribute name="name">{=zVUgQ4Mr}Tose</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_10']/@name" ><xsl:attribute name="name">{=ZPjH5pVz}Nobuhide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_obata_11']/@name" ><xsl:attribute name="name">{=9IFe41L8}Mina</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yura']/@name" ><xsl:attribute name="name">{=nSIP71V7}Narishige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yura_1']/@name" ><xsl:attribute name="name">{=Q4wQhlze}Myouin-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yura_2']/@name" ><xsl:attribute name="name">{=yWf4nQeJ}Kunishige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yura_3']/@name" ><xsl:attribute name="name">{=V5SvHfO0}Shigeaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yura_4']/@name" ><xsl:attribute name="name">{=b3YDzA8r}Akinaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yura_5']/@name" ><xsl:attribute name="name">{=ZiQq8JDT}Mayu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yura_6']/@name" ><xsl:attribute name="name">{=uog9xjJ7}Sumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo']/@name" ><xsl:attribute name="name">{=P3zTiZCm}Ujimasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_1']/@name" ><xsl:attribute name="name">{=RSvvwQuG}Housho-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_2']/@name" ><xsl:attribute name="name">{=fpxfCA95}Ujiyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_3']/@name" ><xsl:attribute name="name">{=w54S5I3N}Zuikei-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_4']/@name" ><xsl:attribute name="name">{=pizr75r3}Ujinao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_5']/@name" ><xsl:attribute name="name">{=1agVt6tW}Ujiteru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_6']/@name" ><xsl:attribute name="name">{=iUvP6aFv}Hisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_7']/@name" ><xsl:attribute name="name">{=fAdkH6BS}Ujikuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_8']/@name" ><xsl:attribute name="name">{=Ihhdccnz}Fuku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_9']/@name" ><xsl:attribute name="name">{=I6HLatlC}Ujinori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_10']/@name" ><xsl:attribute name="name">{=XT3whBO1}Kougen-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hojo_11']/@name" ><xsl:attribute name="name">{=HMftyqYc}Gen'an</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuda']/@name" ><xsl:attribute name="name">{=IFVBo0UW}Norihide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuda_1']/@name" ><xsl:attribute name="name">{=Koe4GEO4}Tani</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuda_2']/@name" ><xsl:attribute name="name">{=uzEB7rTO}Masaharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuda_3']/@name" ><xsl:attribute name="name">{=1ME4J4P8}Naohide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_matsuda_4']/@name" ><xsl:attribute name="name">{=GXvLySIv}Yasusada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_matsuda_5']/@name" ><xsl:attribute name="name">{=ViSD5Bbn}Jifuku-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuda_6']/@name" ><xsl:attribute name="name">{=tgMbwfiE}Yasunaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuda_7']/@name" ><xsl:attribute name="name">{=zDjE64TE}Izumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuda_8']/@name" ><xsl:attribute name="name">{=IOihIX4O}Naonaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuda_9']/@name" ><xsl:attribute name="name">{=N7FUZLza}Yasusato</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsuda_10']/@name" ><xsl:attribute name="name">{=8rJWmjlH}Ito</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_toyama']/@name" ><xsl:attribute name="name">{=WSOVFn2s}Masakage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_toyama_1']/@name" ><xsl:attribute name="name">{=iSVGS3Xg}Take</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_toyama_2']/@name" ><xsl:attribute name="name">{=hbrNLVoD}Tsunakage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_toyama_3']/@name" ><xsl:attribute name="name">{=KxM5VRa1}Joukou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_toyama_4']/@name" ><xsl:attribute name="name">{=zp5C0etl}Naokage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_toyama_5']/@name" ><xsl:attribute name="name">{=lsVY4d0J}Kagemune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_toyama_6']/@name" ><xsl:attribute name="name">{=wTLH9970}Tei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_toyama_7']/@name" ><xsl:attribute name="name">{=BEOaffU2}Kageyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_toyama_8']/@name" ><xsl:attribute name="name">{=PgAQVzbF}Kagenobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_toyama_9']/@name" ><xsl:attribute name="name">{=gSd6sI0U}Hideshige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_toyama_10']/@name" ><xsl:attribute name="name">{=szgwXx0f}Shigemasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_didoji']/@name" ><xsl:attribute name="name">{=f3MMiYMN}Masashige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_didoji_1']/@name" ><xsl:attribute name="name">{=HxDyc3ql}Shino</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_didoji_2']/@name" ><xsl:attribute name="name">{=nDpdaTzx}Naohide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_didoji_3']/@name" ><xsl:attribute name="name">{=Id4pOfky}Naoshige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita']/@name" ><xsl:attribute name="name">{=SwQ02lSF}Ujinaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_1']/@name" ><xsl:attribute name="name">{=Vm16qd8L}Araragi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_2']/@name" ><xsl:attribute name="name">{=78h2ApYu}Nagayasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_3']/@name" ><xsl:attribute name="name">{=5Zj9vfbh}Shirai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_narita_4']/@name" ><xsl:attribute name="name">{=dP4NuLXZ}Chikayasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_narita_5']/@name" ><xsl:attribute name="name">{=PiGMjXxP}Myuokou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_6']/@name" ><xsl:attribute name="name">{=QWiufJBx}Kai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_7']/@name" ><xsl:attribute name="name">{=z0hkNFGC}Yasuchika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_8']/@name" ><xsl:attribute name="name">{=l0dKAD1a}Futaba</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_9']/@name" ><xsl:attribute name="name">{=HyfCYlLK}Yasusue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_10']/@name" ><xsl:attribute name="name">{=wAcogWf3}Tomi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_11']/@name" ><xsl:attribute name="name">{=fLSGAgYC}Nagachika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_narita_12']/@name" ><xsl:attribute name="name">{=qjnRwQly}Mari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chiba']/@name" ><xsl:attribute name="name">{=KrY4IEpg}Tanetomi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chiba_1']/@name" ><xsl:attribute name="name">{=WYTqPJNj}Hagi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_chiba_2']/@name" ><xsl:attribute name="name">{=RUVHqSha}Masatane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_chiba_3']/@name" ><xsl:attribute name="name">{=zsUPpaIN}Seikyou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chiba_4']/@name" ><xsl:attribute name="name">{=BSQ982ou}Yoshitane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chiba_5']/@name" ><xsl:attribute name="name">{=lHQ3t4SP}Kunitane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chiba_6']/@name" ><xsl:attribute name="name">{=jdtXL2lm}Tanehide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chiba_7']/@name" ><xsl:attribute name="name">{=WYTqPJNj}Hagi</xsl:attribute></xsl:template>
  
</xsl:stylesheet>
