<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output version="1.0" omit-xml-declaration="yes" encoding="UTF-8" indent="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<!-- entries should be split into multiple files to avoid the exception that says "syntax is too 'complex'" caused by very inconveninent Microsoft Csharp native XSLT parser library.  -->
	<xsl:template match="string[@id='prebackstory.spc_wanderer_kanto_9']/@text" ><xsl:attribute name="text">{=W5MlHm8t}Sure. You can't sell a horse if you don't shout its praises, as they say.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_kanto_9']/@text" ><xsl:attribute name="text">{=Iy7eNC0Q}I was the brat of a caravan guard. Never knew my mother, but my Da kept me close. I grew up running between the legs of horses on the roads, eavesdropping on merchant gossip in the cities, eating mochi cakes bought me by the other guards. A happier childhood you couldn't imagine.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_kanto_9']/@text" ><xsl:attribute name="text">{=TAC5Tnx4}But when I got older, well, it wasn't so easy to take me on the road. Too many boys giving me funny looks. And my Da, he wanted a good husband for me, but the boys he knew weren't the marrying type. So I said to him, 'I'll be like you, Da, carry a sword and guard rich merchants. And maybe, with the money I earn, some decent boy will love me for my dowry, if not my family name.' He fussed a bit about that but he had no better ideas.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_kanto_9']/@text" ><xsl:attribute name="text">{=toWs4s58}So here I am. Guess I'm not so interested in the marriage part, but I like the denars and I like my freedom. Maybe some day I'll surprise my Da with a nice farm and a couple of slaves to keep him happy in his old age.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_kanto_9']/@text" ><xsl:attribute name="text">{=bLZVseMd}I'm sure he'll be happy if you're happy.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_kanto_9']/@text" ><xsl:attribute name="text">{=MlXbCLlO}You must have broken your poor father's heart.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_kanto_9']/@text" ><xsl:attribute name="text">{=A6WrXPQ6}So like I said: I can ride, swing a sword, manage a caravan, and I have good idea how to turn a profit. You know anyone looking to hire someone like that?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_kanto_9']/@text" ><xsl:attribute name="text">{=NaLmWKEQ}I was the child of a caravan guard. I spent my babyhood swinging from a sling on the side of a horse, and my childhood chasing strays. But caravans are preyed upon by bandits and others, and I decided I don't like being prey. I reckon I have the skills to be a predator.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_kanto_10']/@text" ><xsl:attribute name="text">{=1Slubhxc}It's not many who ask that question.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_kanto_10']/@text" ><xsl:attribute name="text">{=Csokpo5C}I was a farmer. But I split a man's head open with a hoe. He was also a farmer. It was a dispute over a broken fence, between my pasture and his. I had no intention of killing him.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_kanto_10']/@text" ><xsl:attribute name="text">{=JLHhV1ta}His cousins came for me, to take me to judgment. I would have gone willingly; I would have paid blood-money. Gladly. But one of them laid hands on me, and a black rage came over me, and I killed two of them, too. I didn't want to kill them either. </xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_kanto_10']/@text" ><xsl:attribute name="text">{=W2Jhsc2X}That was that. I could pay blood money for one man but not three. I fled. I cannot return.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_kanto_10']/@text" ><xsl:attribute name="text">{=zX3hVUKI}It sounds like you had no choice.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_kanto_10']/@text" ><xsl:attribute name="text">{=K9ig7Mst}A man who cannot master his rage is a greater threat then the man who murders with intent.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_kanto_10']/@text" ><xsl:attribute name="text">{=1gXv1YlG}If the choice I had been mine, I would have never hurt anyone. I would live on my land, eat what I had grown, marry and have children. But the Heavens have decreed that I should eat by shedding other men's blood. In the city, rich men pay me well for that.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_kanto_10']/@text" ><xsl:attribute name="text">{=b1Ucozvw}I was a farmer once. I killed a man in a fight and could not pay the blood money, so I had to flee. It's a common enough tale in the northlands. I accept that my destiny will be blood and hardship, rather than the simple life on the land I once craved.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_kanto_11']/@text" ><xsl:attribute name="text">{=rOUaG9iG}I can tell you my story, though it is painful to recall.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_kanto_11']/@text" ><xsl:attribute name="text">{=qKFHM8ZG}I'm a surgeon. I trained at the imperial academy in Kyoto. I had many rich and influential patients in the town. I thought I was well shielded from the intrigues and dangers of the imperial Court.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_kanto_11']/@text" ><xsl:attribute name="text">{=pzK7TN05}But one day I was contacted by an agent of the Emperor. I do not know how well you know them. At first they wanted small harmless details about my patients. To do so was a violation of my oath, but I was anxious to have the favor of the Emperor. But soon they began to call on me for more and more.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_kanto_11']/@text" ><xsl:attribute name="text">{=sfFLudTM}One time they came at midnight - they had a man who plotted against the Emperor, they said, and they needed a confession, and wished me to use my art to elicit that confession. If I refused, they said, they would disclose our relationship to my patients - I would be ruined. I went with them, to my shame, and what I was asked to do to that man's body -- I shall not repeat it.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_kanto_11']/@text" ><xsl:attribute name="text">{=BIsvfC0x}You too are a victim of the hideous power of the state.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_kanto_11']/@text" ><xsl:attribute name="text">{=hikXX6zE}You broke your oath. It is not surprising that you fell further.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_kanto_11']/@text" ><xsl:attribute name="text">{=x50bW6NF}I should have refused - my practice was ruined anyway. To blot out the memory of that night, I took opium, until my pallid face so alarmed my patients that they no longer called on me. So I fled the city, and have wandered from town to town ever since. I would welcome steady work, if I could find it.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_kanto_11']/@text" ><xsl:attribute name="text">{=pya1JSNe}I was a surgeon, trained at the imperial academy. But my home and infirmary were burned in a bout of unrest, and now I must wander the world a bit. There are many of us out there, you know, forced to make what living we can.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_kanto_12']/@text" ><xsl:attribute name="text">{=JFdjrbAF}Huh? Well, okay. Why not?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_kanto_12']/@text" ><xsl:attribute name="text">{=1Gr3wo1m}I was a smith. As you can see I'm a big fellow, strong... I was good at my job. Had a nice shop on the high street through my town. Saved a bit of money and thought about finding a girl to wed.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_kanto_12']/@text" ><xsl:attribute name="text">{=qx2IjYqq}There was a woman who lived out on the street. Refugee from the wars. Had a small child, a baby really. It was all she had. She'd make small cakes of rice over a fire. Then one day a young man from the palace came down the street in his horse. Wasn't looking where he was going, didn't care, and his horse crushed that baby's head.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_kanto_12']/@text" ><xsl:attribute name="text">{=rpOla1Vp}I saw her nurse that babe through two fevers. The patience, the sacrifice, of that mother - to see all for which she suffered snatched away like that from her, by some young drunk's carelessness... There was a crowd around them, he was yelling. I just walked over with my hammer and struck him dead.... That was the end of my life in the city. I think back, though, and can't imagine doing different.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_kanto_12']/@text" ><xsl:attribute name="text">{=bwthhDSN}Right or wrong, I cannot blame you for your anger.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_kanto_12']/@text" ><xsl:attribute name="text">{=hpKAp2ZW}The law is the law, and murder is murder.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_kanto_12']/@text" ><xsl:attribute name="text">{=DHCTLcp1}So here I am. I know men like me can make money guarding merchants, doing other tasks such as that. As long as no one wants me to hurt the innocent... Some day, I hope to find a new place to set up a smithy and start again.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_kanto_12']/@text" ><xsl:attribute name="text">{=XEsq2Gd6}I was a smith, but I had a problem with gambling. I borrowed from an alley gang, I couldn't pay back, and, well, you probably know what comes next. A smith just can't pack up and go to another place. There's guilds that make that difficult. But I'm a big fellow, I figure I can swing a weapon as well as my tools, and there might be work for me in the wars.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_0']/@text" ><xsl:attribute name="text">{=GNP9jLDo}I can share my story with you, if you have the time.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_0']/@text" ><xsl:attribute name="text">{=axVcadKQ}I come from a lengthy line of stonemasons who built walls and roads across the countryside for generations. During my apprenticeship, my father noticed that while my brothers hated tearing down the hollowed structures and foundations, I reveled in it.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_0']/@text" ><xsl:attribute name="text">{=Kaz4NbDN}My father, being as wise as he is, understood that stronger walls will need more powerful tools to bring them down. He sent me off to learn carpentry and siegecraft on my own.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_0']/@text" ><xsl:attribute name="text">{=YLn5hxVB}Now, before the Ounin war, if a man apprenticed in siegecraft went to work for another master, it meant a very painful death if he was recaptured. But times have changed. The richest mandarins of the Japan's cities have fallen, and they build their walls higher than they once did. The ou lords pay less for a siegemaster, and that pay is often late. So I am up to taking other employment, if it is offered.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_0']/@text" ><xsl:attribute name="text">{=HSHRP59J}Of course, of course. A good engineer deserves his pay.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_0']/@text" ><xsl:attribute name="text">{=cPpWwCU9}How virtue has crumbled since the old days.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_0']/@text" ><xsl:attribute name="text">{=l0OCTrl9}Indeed... Well, at any rate, if you find there is an inconvenient wall between you and the object of your desire, and you wish it reduced to rubble, you know where to find me.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_0']/@text" ><xsl:attribute name="text">{=SkUwSwLZ}My father was one of the men that Ashikaga Yoshiteru had trained by captured engineers. Our people knew little of siegecraft in those days. Well, he was not allowed to work for anyone but the Ashikaga Shogun, or he would be killed in a very unpleasant way. But he taught me, his son, what he knew, and in this generation things are a little more lenient. So I can work for whom I please.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_1']/@text" ><xsl:attribute name="text">{=RYWoN1qp}You know, you'd think this place could serve proper sake, instead of this piss... Sorry, where were we? Ah yes, my story.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_1']/@text" ><xsl:attribute name="text">{=QEO5Wo1m}I rode for years behind Ryūzouji Takanobu. I had good name and a good sum of money. There was a girl in a neighboring village, quiet thing but good childbearing hips, who I thought would make a good bride.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_1']/@text" ><xsl:attribute name="text">{=X9IcvNnc}So I went to her brother, and offered him 20 horses - a good price. But he said he wasn't giving his sister to a 'man like me.' Asked him what he meant by that, and he didn't answer, so I gave him a good punch. Maybe a couple punches - no more. Shouldn't have hurt a real man, but this little whelp died on me.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_1']/@text" ><xsl:attribute name="text">{=jwGsuWlN}Well, you know how these things go - his kin came to our village looking for my blood. They didn't find me, but wounded one of my cousins. It was time to teach them a lesson, but my brothers had a fit of cowardice. So they brokered a deal, and I was forced to leave. How do you like that?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_1']/@text" ><xsl:attribute name="text">{=bMHFQgVE}Aye, real honor is as scarce as hen's teeth these days.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_1']/@text" ><xsl:attribute name="text">{=xpENowWf}Strange thing, how people don't wish to die in someone else's quarrel.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_1']/@text" ><xsl:attribute name="text">{=rSwj5KBb}Let me tell you something - I'm sick of cowardice, sick of those who don't stand by their comrades and their kin.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_1']/@text" ><xsl:attribute name="text">{=F1hLRHDo}I rode behind the banner of the Ryūzouji Takanobu for years. I should have had a place of honor in his court. But I killed a man from a richer clan over an insult, and he had too many kinfolk for me to linger anymore.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_2']/@text" ><xsl:attribute name="text">{=LWjvkvyj}I am from one of the highland clans, in the far north. I do not know if you are familiar with their ways. I will try to explain.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_2']/@text" ><xsl:attribute name="text">{=IUbGYeJV}A man of another clan slew my father. My father had slain his uncle many years before. It was my job to avenge my father, but the plague carried off his killer first. So I would be expected to kill his brother instead. This is how it is with us.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_2']/@text" ><xsl:attribute name="text">{=qRwX7d5K}I wanted to go to the other clan and negotiate a settlement. I had always had a talent for setting conflicts, and in this case it seemed to me clearly that fate had ended the feud. But my mother begged me not to; my cousins begged me not to. They said I should spill blood, not words.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_2']/@text" ><xsl:attribute name="text">{=JAqysRea}MY family said others would mock my father's memory. They said no one would fear to steal our cow and horses, to molest my sisters. They told me I had a choice: do my duty, or I would no longer be of their blood. So be it. I chose exile. Why should more men die? </xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_2']/@text" ><xsl:attribute name="text">{=T07xEuQR}A noble decision!</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_2']/@text" ><xsl:attribute name="text">{=atWYxZBh}What? Does no one respect their parents anymore?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_2']/@text" ><xsl:attribute name="text">{=B7iZITxb}If an enemy chooses to stand in a battle-line and face my arrows, I would not hesitate to kill him. But our feuds - I cannot accept that I have no choice but to kill a man who had no choice but to be my enemy. I left my people. Here I can choose what I do.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_2']/@text" ><xsl:attribute name="text">{=7GpMPCMW}My clan was locked in a feud with another clan for years. One life of theirs, then one life of ours, year after year, decade after decade. But I chose to break the cycle. I left my family. I am not the first to do so. This happens among us, from time to time, though few speak of it.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_3']/@text" ><xsl:attribute name="text">{=HbBVafZh}Yeah... I'll tell you a tale of life in the great Tumed hordes, terror of the world.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_3']/@text" ><xsl:attribute name="text">{=hjmaZSrv}I fought for Altan Khan. But I fight on foot - my family's from the town, not the steppe. Life's a little different for us.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_3']/@text" ><xsl:attribute name="text">{=dCHCb1hb}The horse lords, the men of the great tribes - well they gallop here, and they gallup there, shooting this and shooting that. They win battles, I'll give them that. But at the end of the day, if the enemy's still laughing at you behind their walls, all that galloping means nothing.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_3']/@text" ><xsl:attribute name="text">{=DFaMQXWH}We foot-sloggers, we're the ones who go up the ladder and into the meat grinder. Did that for 15 years, and I'm still getting less pay than some boy fresh of his mother's tit who happens to own a horse. Piss on that, I said, and I went looking for other work.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_3']/@text" ><xsl:attribute name="text">{=FjrLf4LE}Indeed. Good infantry is the backbone of an army.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_3']/@text" ><xsl:attribute name="text">{=9jYj8jGg}Resentment is poison to an army. Men must learn to follow what orders they are given.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_3']/@text" ><xsl:attribute name="text">{=EQzHDnlS}At any rate, I'll fight for any man willing to take the same risks that his men face.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_3']/@text" ><xsl:attribute name="text">{=5hBuA8kd}I was an spearman. I fought on foot. That's usually what you do if you're not from a big clan. Twice the risk, half the pay and none of the glory. Anyway, I'm done with that for now, looking for other work.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_4']/@text" ><xsl:attribute name="text">{=B3UQTCRE}Refill my glass and I'll tell you.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_4']/@text" ><xsl:attribute name="text">{=fKuxXywF}I'm a soldier by trade. I've served in the Amago's army for 20 years. Once upon a time they were worthy of respect. I served them for years, but war was not kind to them.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_4']/@text" ><xsl:attribute name="text">{=os4ZW2gc}But Amago Yoshihisa led the army into a failed siege defense at Gassan-Toda Castle. You may have heard that story. I was laid up sick at the time. But a lot of my comrades didn't come back, and things were never the same afterward.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_4']/@text" ><xsl:attribute name="text">{=08t1XV2r}After the siege, The Amago were forced to a small island in northern San'you, with no hope of reconquering their lands.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_4']/@text" ><xsl:attribute name="text">{=0SnKUaex}No doubt a sad state of affairs. So what do you do?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_4']/@text" ><xsl:attribute name="text">{=WQCAanal}Ah, the old days. And no doubt back then they complained about the older days. I've heard enough.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_4']/@text" ><xsl:attribute name="text">{=yx5yqDby}Well, I can't just sit around and drink myself to death, so I sell my sword to anyone worth following. I'm a good trainer - I don't bother with horsemen or archers, but if you've got good steady footmen I can do a lot with them. I know a bit about siege machinery too.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_4']/@text" ><xsl:attribute name="text">{=WvwT5D2l}I was a solider in the Amago army. How we came to this sorry state is a sad tale that you've no doubt heard already from my comrades. But I'm sure you're familiar with our mettle in battle, and our skill at turning youths into soldiers.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_5']/@text" ><xsl:attribute name="text">{=56VPnxQd}You're a nosy one, I see.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_5']/@text" ><xsl:attribute name="text">{=qlAW1aTi}What do you want to know about? My family? Piss on them. I left home as a child and never had cause to regret it. My brothers can take my inheritance, and I hope they choke on it.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_5']/@text" ><xsl:attribute name="text">{=ikVu2vQU}I've fought in a few wars, for one side or the other. You want to know about my-comrades-in-arms? Piss on them too. They all turn on you in the end.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_5']/@text" ><xsl:attribute name="text">{=iWe4KrSO}About my past, that's all I have to say.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_5']/@text" ><xsl:attribute name="text">{=AX7gvmaj}So... What are you good at?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_5']/@text" ><xsl:attribute name="text">{=Aj9ulUly}You're a cheerful one. Good day to you.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_5']/@text" ><xsl:attribute name="text">{=X9zcXYPa}I can fight. And I don't mind doing work that others would shirk.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_5']/@text" ><xsl:attribute name="text">{=Ycc0gsX9}I kill for a living. You don't look too wet behind the ears, so I'm sure I don't need to tell you any more about myself than that.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_6']/@text" ><xsl:attribute name="text">{=BuamWVTp}Yes.. My story... Jealousy, envy of my talents. That's always been my undoing.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_6']/@text" ><xsl:attribute name="text">{=L64od7cC}When I was a boy, I was the best fighter in my village. 'You're stronger as a boy than a full-grown warrior,' people would say. I'm not boasting here - that's what they'd tell me. So when I came of age I went off to make my fortune.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_6']/@text" ><xsl:attribute name="text">{=PJY8IeMD}Started in the Ashigaru. I found that I was the only real warrior among them. They were all about marching here and there in their pretty uniforms, not pulling sword from scabbard for months on end. I told them what I thought, and my captain told me to keep my mouth shut or leave. So I left.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_6']/@text" ><xsl:attribute name="text">{=BDTsEQKa}Then I joined the Sakai, mercenaries. They spent most of their time using guns. Ha! Me, I'd wade into the midst of the enemy, dealing out death right and left - and, well, all they had to say afterward was 'Why didn't you keep ranks?'</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_6']/@text" ><xsl:attribute name="text">{=4ee0aofe}Hmm... Strange response.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_6']/@text" ><xsl:attribute name="text">{=8oc7bO2s}Has no one told you that leaving a gap in a formation is as good as treason?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_6']/@text" ><xsl:attribute name="text">{=qbYupvSJ}So I'm having no more of that. I'm on the look-out for an outfit that employs real fighters.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_6']/@text" ><xsl:attribute name="text">{=gnLnZuAH}Let me tell you friend, I'm hard. I've fought as an ashigaru, then with the Sakai, any mercenaries worth their salt, I've been with them. Others may tell you've they've done what I've done, but I'm the real thing.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_7']/@text" ><xsl:attribute name="text">{=g3BssthL}Oh yes. I do indeed have a story to tell you.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_7']/@text" ><xsl:attribute name="text">{=XY76uN2m}Bandits took me when I was a girl. I learned to fight with them as I grew, and did quite well with them.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_7']/@text" ><xsl:attribute name="text">{=NIy8l5HF}Perhaps it was my destiny to become like this, a warrior with who enjoys slaughtering. Most men can't handle my presence.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_7']/@text" ><xsl:attribute name="text">{=NDFxrOZq}I feel no guilt, no remorse. I kill when it is necessary, and don't ask questions.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_7']/@text" ><xsl:attribute name="text">{=rlHt9ZWE}Interesting.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_7']/@text" ><xsl:attribute name="text">{=lNjP8zRn}You seem somewhat unhealthy.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_7']/@text" ><xsl:attribute name="text">{=BYKVqoyU}There's not much more to say. I'm good at what I do, and i'll follow orders. So here I am, looking to make a living through the only means I know - shedding other people's blood. Got work?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_7']/@text" ><xsl:attribute name="text">{=HSjsEM2c}I was raised by bandits where I learned to fight. I enjoy killing and wish to do it as much as possible.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_8']/@text" ><xsl:attribute name="text">{=iK5Kaa7M}Well, if you wish to know how cruel a pack can be to one of its own, I could enlighten you.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_8']/@text" ><xsl:attribute name="text">{=lbLBkvoe}My father died shortly after my mother became pregnant with me. I was her only child. Like most of our people, she had wanted sons. So she raised me as a son, and boasted of me like she would boast about a son. When I was a baby, she boasted of how swiftly I emptied her breast of milk. When I was a girl, she boasted of how I killed steppe ducks with my bow. When I became a woman, she boasted that soon I would be the first of my age-set to bring home the head of an enemy slain in battle.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_8']/@text" ><xsl:attribute name="text">{=buxRNQSQ}Because I loved my mother, and because I was faster and stronger than the boys, I did all that she said I would do. Of those born in my year, I was the first to kill an enemy. My mother boasted even more, so that the other women came to hate her. They turned us all out of our encampment. We were forced to sell our lands, as we could not take them with us, and we were given but a fraction of the price. All we had was our horses. Of course raiders found us soon enough, and killed my mother, and took our horses. I escaped.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_8']/@text" ><xsl:attribute name="text">{=YjjgGEG5}I wandered a bit around Japan. I starved a bit. But I followed the raiders and one, when he went beyond the campfire to empty his bladder, did not return. I now have his purse and his sword.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_8']/@text" ><xsl:attribute name="text">{=IyGObqs1}I'm sorry for your loss. You drew a cruel lot in life.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_8']/@text" ><xsl:attribute name="text">{=wFRMSMQD}Every day, I give thanks to the Heavens that I was not born to that life.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_8']/@text" ><xsl:attribute name="text">{=548o0GKu}I could return to my people, I suppose, but I have no wish to do so. So I am here, in the towns, where I can make good money with my sword and care nothing about those who envy me.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_8']/@text" ><xsl:attribute name="text">{=TIYbctCQ}My father died shortly after my birth. I was my mother's only child. Our clan was poor, and a woman with a baby - especially a girl-baby - was only a drain on what little they had. So we were sold to another clan, as servants. Some years later, when my mother died, I stole one of their swords and one of their horses and rode off into the grass.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_9']/@text" ><xsl:attribute name="text">{=W5MlHm8t}Sure. You can't sell a horse if you don't shout its praises, as they say.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_9']/@text" ><xsl:attribute name="text">{=Iy7eNC0Q}I was the brat of a caravan guard. Never knew my mother, but my Da kept me close. I grew up running between the legs of horses on the roads, eavesdropping on merchant gossip in the cities, eating mochi cakes bought me by the other guards. A happier childhood you couldn't imagine.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_9']/@text" ><xsl:attribute name="text">{=TAC5Tnx4}But when I got older, well, it wasn't so easy to take me on the road. Too many boys giving me funny looks. And my Da, he wanted a good husband for me, but the boys he knew weren't the marrying type. So I said to him, 'I'll be like you, Da, carry a sword and guard rich merchants. And maybe, with the money I earn, some decent boy will love me for my dowry, if not my family name.' He fussed a bit about that but he had no better ideas.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_9']/@text" ><xsl:attribute name="text">{=toWs4s58}So here I am. Guess I'm not so interested in the marriage part, but I like the denars and I like my freedom. Maybe some day I'll surprise my Da with a nice farm and a couple of slaves to keep him happy in his old age.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_9']/@text" ><xsl:attribute name="text">{=bLZVseMd}I'm sure he'll be happy if you're happy.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_9']/@text" ><xsl:attribute name="text">{=MlXbCLlO}You must have broken your poor father's heart.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_9']/@text" ><xsl:attribute name="text">{=A6WrXPQ6}So like I said: I can ride, swing a sword, manage a caravan, and I have good idea how to turn a profit. You know anyone looking to hire someone like that?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_9']/@text" ><xsl:attribute name="text">{=NaLmWKEQ}I was the child of a caravan guard. I spent my babyhood swinging from a sling on the side of a horse, and my childhood chasing strays. But caravans are preyed upon by bandits and others, and I decided I don't like being prey. I reckon I have the skills to be a predator.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_10']/@text" ><xsl:attribute name="text">{=1Slubhxc}It's not many who ask that question.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_10']/@text" ><xsl:attribute name="text">{=Csokpo5C}I was a farmer. But I split a man's head open with a hoe. He was also a farmer. It was a dispute over a broken fence, between my pasture and his. I had no intention of killing him.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_10']/@text" ><xsl:attribute name="text">{=JLHhV1ta}His cousins came for me, to take me to judgment. I would have gone willingly; I would have paid blood-money. Gladly. But one of them laid hands on me, and a black rage came over me, and I killed two of them, too. I didn't want to kill them either. </xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_10']/@text" ><xsl:attribute name="text">{=W2Jhsc2X}That was that. I could pay blood money for one man but not three. I fled. I cannot return.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_10']/@text" ><xsl:attribute name="text">{=zX3hVUKI}It sounds like you had no choice.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_10']/@text" ><xsl:attribute name="text">{=K9ig7Mst}A man who cannot master his rage is a greater threat then the man who murders with intent.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_10']/@text" ><xsl:attribute name="text">{=1gXv1YlG}If the choice I had been mine, I would have never hurt anyone. I would live on my land, eat what I had grown, marry and have children. But the Heavens have decreed that I should eat by shedding other men's blood. In the city, rich men pay me well for that.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_10']/@text" ><xsl:attribute name="text">{=b1Ucozvw}I was a farmer once. I killed a man in a fight and could not pay the blood money, so I had to flee. It's a common enough tale in the northlands. I accept that my destiny will be blood and hardship, rather than the simple life on the land I once craved.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_11']/@text" ><xsl:attribute name="text">{=rOUaG9iG}I can tell you my story, though it is painful to recall.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_11']/@text" ><xsl:attribute name="text">{=qKFHM8ZG}I'm a surgeon. I trained at the imperial academy in Kyoto. I had many rich and influential patients in the town. I thought I was well shielded from the intrigues and dangers of the imperial Court.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_11']/@text" ><xsl:attribute name="text">{=pzK7TN05}But one day I was contacted by an agent of the Emperor. I do not know how well you know them. At first they wanted small harmless details about my patients. To do so was a violation of my oath, but I was anxious to have the favor of the Emperor. But soon they began to call on me for more and more.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_11']/@text" ><xsl:attribute name="text">{=sfFLudTM}One time they came at midnight - they had a man who plotted against the Emperor, they said, and they needed a confession, and wished me to use my art to elicit that confession. If I refused, they said, they would disclose our relationship to my patients - I would be ruined. I went with them, to my shame, and what I was asked to do to that man's body -- I shall not repeat it.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_11']/@text" ><xsl:attribute name="text">{=BIsvfC0x}You too are a victim of the hideous power of the state.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_11']/@text" ><xsl:attribute name="text">{=hikXX6zE}You broke your oath. It is not surprising that you fell further.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_11']/@text" ><xsl:attribute name="text">{=x50bW6NF}I should have refused - my practice was ruined anyway. To blot out the memory of that night, I took opium, until my pallid face so alarmed my patients that they no longer called on me. So I fled the city, and have wandered from town to town ever since. I would welcome steady work, if I could find it.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_11']/@text" ><xsl:attribute name="text">{=pya1JSNe}I was a surgeon, trained at the imperial academy. But my home and infirmary were burned in a bout of unrest, and now I must wander the world a bit. There are many of us out there, you know, forced to make what living we can.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='prebackstory.spc_wanderer_ou_12']/@text" ><xsl:attribute name="text">{=JFdjrbAF}Huh? Well, okay. Why not?</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_a.spc_wanderer_ou_12']/@text" ><xsl:attribute name="text">{=1Gr3wo1m}I was a smith. As you can see I'm a big fellow, strong... I was good at my job. Had a nice shop on the high street through my town. Saved a bit of money and thought about finding a girl to wed.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_b.spc_wanderer_ou_12']/@text" ><xsl:attribute name="text">{=qx2IjYqq}There was a woman who lived out on the street. Refugee from the wars. Had a small child, a baby really. It was all she had. She'd make small cakes of rice over a fire. Then one day a young man from the palace came down the street in his horse. Wasn't looking where he was going, didn't care, and his horse crushed that baby's head.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_c.spc_wanderer_ou_12']/@text" ><xsl:attribute name="text">{=rpOla1Vp}I saw her nurse that babe through two fevers. The patience, the sacrifice, of that mother - to see all for which she suffered snatched away like that from her, by some young drunk's carelessness... There was a crowd around them, he was yelling. I just walked over with my hammer and struck him dead.... That was the end of my life in the city. I think back, though, and can't imagine doing different.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_1.spc_wanderer_ou_12']/@text" ><xsl:attribute name="text">{=bwthhDSN}Right or wrong, I cannot blame you for your anger.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='response_2.spc_wanderer_ou_12']/@text" ><xsl:attribute name="text">{=hpKAp2ZW}The law is the law, and murder is murder.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='backstory_d.spc_wanderer_ou_12']/@text" ><xsl:attribute name="text">{=DHCTLcp1}So here I am. I know men like me can make money guarding merchants, doing other tasks such as that. As long as no one wants me to hurt the innocent... Some day, I hope to find a new place to set up a smithy and start again.</xsl:attribute></xsl:template>
	<xsl:template match="string[@id='generic_backstory.spc_wanderer_ou_12']/@text" ><xsl:attribute name="text">{=XEsq2Gd6}I was a smith, but I had a problem with gambling. I borrowed from an alley gang, I couldn't pay back, and, well, you probably know what comes next. A smith just can't pack up and go to another place. There's guilds that make that difficult. But I'm a big fellow, I figure I can swing a weapon as well as my tools, and there might be work for me in the wars.</xsl:attribute></xsl:template>
</xsl:stylesheet>