<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output version="1.0" omit-xml-declaration="yes" encoding="UTF-8" indent="yes"/>
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
  <!-- entries should be split into multiple files to avoid the exception that says "syntax is too 'complex'" caused by very inconveninent Microsoft Csharp native XSLT parser library.  -->
  <xsl:template match="NPCCharacter[@id='lord_1_kai_2']/@name" ><xsl:attribute name="name">{=AwDyF3fr}Chikahide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kai_3']/@name" ><xsl:attribute name="name">{=0dn4iBEk}Chikamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kai_4']/@name" ><xsl:attribute name="name">{=1erzaD8X}Nobunari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nawa']/@name" ><xsl:attribute name="name">{=XYmKfVXX}Yukinao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nawa_1']/@name" ><xsl:attribute name="name">{=ZQpSL7UA}Anzu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nawa_2']/@name" ><xsl:attribute name="name">{=SQP2yZeu}Akitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nawa_3']/@name" ><xsl:attribute name="name">{=KrF8FmSs}Akiteru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nawa_4']/@name" ><xsl:attribute name="name">{=1btPFqMR}Yukiyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishi']/@name" ><xsl:attribute name="name">{=XoV0TPFq}Koremitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishi_1']/@name" ><xsl:attribute name="name">{=saxrxGki}Koma</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishi_2']/@name" ><xsl:attribute name="name">{=7eurlUtR}Koreharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishi_3']/@name" ><xsl:attribute name="name">{=SRSldKIW}Uta</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishi_4']/@name" ><xsl:attribute name="name">{=4ZWfBLHb}Korenobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishi_5']/@name" ><xsl:attribute name="name">{=jpK0zLw5}Korehide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nishi_6']/@name" ><xsl:attribute name="name">{=cCBVwKSj}Seki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takezaki']/@name" ><xsl:attribute name="name">{=hv1qJGAV}Koremitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takezaki_1']/@name" ><xsl:attribute name="name">{=P62eOd0e}Sawa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takezaki_2']/@name" ><xsl:attribute name="name">{=L7lfoFu7}Nagahide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takezaki_3']/@name" ><xsl:attribute name="name">{=WRBJMAxG}Tama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_takezaki_4']/@name" ><xsl:attribute name="name">{=3IgBMBjO}Tsuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sagara_1']/@name" ><xsl:attribute name="name">{=YNU67geV}Haruhiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sagara_2']/@name" ><xsl:attribute name="name">{=916pH86X}Uchijou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sagara']/@name" ><xsl:attribute name="name">{=5eZfB982}Yoshihi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sagara_1']/@name" ><xsl:attribute name="name">{=qLcsYHM7}Chiyogiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sagara_2']/@name" ><xsl:attribute name="name">{=HAtmAA4A}Koari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sagara_3']/@name" ><xsl:attribute name="name">{=5GMpq6XY}Chiari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sagara_4']/@name" ><xsl:attribute name="name">{=NutJCPcj}Kikuchiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sagara_5']/@name" ><xsl:attribute name="name">{=NWi3RA0H}Yorisada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sagara_6']/@name" ><xsl:attribute name="name">{=dvyfGKTU}Hotaru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sagara_7']/@name" ><xsl:attribute name="name">{=bbvlOOs5}Umigiri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_indo']/@name" ><xsl:attribute name="name">{=dKC0bSr2}Yoriyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_indo_1']/@name" ><xsl:attribute name="name">{=0K6M8tdY}Myoukei-ni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_indo_2']/@name" ><xsl:attribute name="name">{=EmtnyFBl}Yorimori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_indo_3']/@name" ><xsl:attribute name="name">{=MSsRSBtV}Yusura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amakusa']/@name" ><xsl:attribute name="name">{=nnG2BZn7}Shigenao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amakusa_1']/@name" ><xsl:attribute name="name">{=L9k5QuOT}Chidori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amakusa_2']/@name" ><xsl:attribute name="name">{=16V5w91f}Hisatane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amakusa_3']/@name" ><xsl:attribute name="name">{=uq8mSvxo}Tanemoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amakusa_4']/@name" ><xsl:attribute name="name">{=MF8e93EW}Hisatake</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amakusa_5']/@name" ><xsl:attribute name="name">{=3kwAqpNa}Tsudura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_amakusa_6']/@name" ><xsl:attribute name="name">{=57TkTUlx}Tanemoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ito']/@name" ><xsl:attribute name="name">{=XTnJEsYW}Yoshisuke</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ito_1']/@name" ><xsl:attribute name="name">{=Zo5RCGJQ}Asa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ito_2']/@name" ><xsl:attribute name="name">{=4atnqu27}Takashiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ito_3']/@name" ><xsl:attribute name="name">{=uihfZdNy}Aso</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ito_4']/@name" ><xsl:attribute name="name">{=zc3RATLY}Yoshimasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ito_5']/@name" ><xsl:attribute name="name">{=bi2KysQW}Houjyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ito_6']/@name" ><xsl:attribute name="name">{=lVI3T9fG}Machigami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ito_7']/@name" ><xsl:attribute name="name">{=85Bsa0wA}Suketaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mera_6']/@name" ><xsl:attribute name="name">{=Zyip3QcN}Sukemichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mera_7']/@name" ><xsl:attribute name="name">{=ZtJyjDvr}Namomi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mera']/@name" ><xsl:attribute name="name">{=2CvJRlY1}Suketsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mera_1']/@name" ><xsl:attribute name="name">{=ioFUZ0oL}Natsugiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mera_2']/@name" ><xsl:attribute name="name">{=peaJoNOB}Sigekata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mera_3']/@name" ><xsl:attribute name="name">{=rOnLD0w7}Hana</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mera_4']/@name" ><xsl:attribute name="name">{=Zyip3QcN}Sukemichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mera_5']/@name" ><xsl:attribute name="name">{=Uf3QK6ng}Yume</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nagakura_3']/@name" ><xsl:attribute name="name">{=zE5EwPDa}Suketoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nagakura_4']/@name" ><xsl:attribute name="name">{=4EowmW3n}Hisame</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nagakura']/@name" ><xsl:attribute name="name">{=IGRDYaLn}Sukemasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nagakura_1']/@name" ><xsl:attribute name="name">{=kxPhkWeY}Asa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nagakura_2']/@name" ><xsl:attribute name="name">{=a0POjhcf}Douunsai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='main_hero']/@name" ><xsl:attribute name="name">{=w1okK9gq}Rogan</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='main_hero_father']/@name" ><xsl:attribute name="name">{=d2321253}Father</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='main_hero_mother']/@name" ><xsl:attribute name="name">{=E1C1a873}Mother</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='ferry_driver']/@name" ><xsl:attribute name="name">{=hOcFw02K}Driver</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_saionji_1']/@name" ><xsl:attribute name="name">{=gTFSsjbm}Kinnobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_saionji_2']/@name" ><xsl:attribute name="name">{=qwJbUUQV}Seikou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saionji']/@name" ><xsl:attribute name="name">{=bMfqWjqk}Kinhiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saionji_1']/@name" ><xsl:attribute name="name">{=g5pzHuFm}Nishi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saionji_2']/@name" ><xsl:attribute name="name">{=kHOJ0Awe}Nobuhisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saionji_3']/@name" ><xsl:attribute name="name">{=Jb6FawOB}Hisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashuji']/@name" ><xsl:attribute name="name">{=RzWxJC41}Motoaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashuji_1']/@name" ><xsl:attribute name="name">{=vT8u3noP}Fuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashuji_2']/@name" ><xsl:attribute name="name">{=GZEDDxOG}Motonori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kashuji_3']/@name" ><xsl:attribute name="name">{=KDfcebZ7}Sayuri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hoketsu']/@name" ><xsl:attribute name="name">{=gSncZATa}Norinobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hoketsu_1']/@name" ><xsl:attribute name="name">{=GCLn5ECy}Hama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hoketsu_2']/@name" ><xsl:attribute name="name">{=UgnuLgbA}Sakinobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hoketsu_3']/@name" ><xsl:attribute name="name">{=51dM4xsA}Kuwa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ichijo']/@name" ><xsl:attribute name="name">{=l9dNB33O}Kanesada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ichijo_1']/@name" ><xsl:attribute name="name">{=vZK6RwNC}Tamafuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ichijo_2']/@name" ><xsl:attribute name="name">{=aa7k9lsZ}Tadamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ichijo_3']/@name" ><xsl:attribute name="name">{=FH6ohwg7}Nobuko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ichijo_4']/@name" ><xsl:attribute name="name">{=84OJJiZg}Mariko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_doi']/@name" ><xsl:attribute name="name">{=j6oilqBS}Kiyoyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_doi_1']/@name" ><xsl:attribute name="name">{=R9UQCnuM}Mugi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_doi_2']/@name" ><xsl:attribute name="name">{=NrJRgRfz}Shigekiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_doi_3']/@name" ><xsl:attribute name="name">{=PGjI36Ae}Souzan</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_aki']/@name" ><xsl:attribute name="name">{=pvhvN7QV}Kunitora</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_aki_1']/@name" ><xsl:attribute name="name">{=rHKVyyVc}Nishi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_aki_2']/@name" ><xsl:attribute name="name">{=kCyapaMi}Hirotsune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_aki_3']/@name" ><xsl:attribute name="name">{=qsvolxnV}Ietomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsuno']/@name" ><xsl:attribute name="name">{=qnY9HZY8}Sadakatsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsuno_1']/@name" ><xsl:attribute name="name">{=q7dRw8dj}Sumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsuno_2']/@name" ><xsl:attribute name="name">{=Pi1K6Dyu}Katsuoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tsuno_3']/@name" ><xsl:attribute name="name">{=Q5L1Tq9A}Tomo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chosokabe']/@name" ><xsl:attribute name="name">{=EFVk0L5h}Motochika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chosokabe_1']/@name" ><xsl:attribute name="name">{=6CK8HDZR}Amane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chosokabe_2']/@name" ><xsl:attribute name="name">{=s6nTS5jf}Nobuchika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chosokabe_3']/@name" ><xsl:attribute name="name">{=OdLEdQd3}Chikakazu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chosokabe_4']/@name" ><xsl:attribute name="name">{=JVEOWyAi}Suzu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chosokabe_5']/@name" ><xsl:attribute name="name">{=MgtskN05}Honoka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_chosokabe_6']/@name" ><xsl:attribute name="name">{=ufdDL1IS}Ako</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kosokabe']/@name" ><xsl:attribute name="name">{=U9RsqAwX}Chikayasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kosokabe_1']/@name" ><xsl:attribute name="name">{=RySY5fQu}Yuzuha</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kira']/@name" ><xsl:attribute name="name">{=hvyaWDgX}Chikasada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kira_1']/@name" ><xsl:attribute name="name">{=DeCbQeHC}Yumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kira_2']/@name" ><xsl:attribute name="name">{=1YCmAvvP}Chikazane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kira_3']/@name" ><xsl:attribute name="name">{=FXZNXucw}Joen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kira_4']/@name" ><xsl:attribute name="name">{=zcC4TL48}Chikamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hisatake']/@name" ><xsl:attribute name="name">{=pGrd03pI}Chikanobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hisatake_1']/@name" ><xsl:attribute name="name">{=kKdyVFsm}En</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_hisatake_2']/@name" ><xsl:attribute name="name">{=Uk8wWxBw}Shougen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_hisatake_3']/@name" ><xsl:attribute name="name">{=gswXQDd7}Mugi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hisatake_4']/@name" ><xsl:attribute name="name">{=KwL2BhJu}Chikanao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hisatake_5']/@name" ><xsl:attribute name="name">{=NMjVGI7u}Taka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida']/@name" ><xsl:attribute name="name">{=m3YajwyO}Shigetoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida_1']/@name" ><xsl:attribute name="name">{=uht0Icck}Hisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yoshida_2']/@name" ><xsl:attribute name="name">{=YK0QNAGY}Norihiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yoshida_3']/@name" ><xsl:attribute name="name">{=uuCL0VJy}Chiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida_4']/@name" ><xsl:attribute name="name">{=1OhuHuRD}Shigeyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida_5']/@name" ><xsl:attribute name="name">{=pOfNSi6V}Naka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida_6']/@name" ><xsl:attribute name="name">{=UYASRxJw}Takatoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_yoshida_7']/@name" ><xsl:attribute name="name">{=hhYUOKRh}Takayori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida_8']/@name" ><xsl:attribute name="name">{=ic0O247n}Sen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida_9']/@name" ><xsl:attribute name="name">{=HAaOI8lO}Sadashige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida_10']/@name" ><xsl:attribute name="name">{=CLvsoPtJ}Kinu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida_11']/@name" ><xsl:attribute name="name">{=KyUYLo0G}Chikashige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_yoshida_12']/@name" ><xsl:attribute name="name">{=mfPg78eX}Toku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fukudome']/@name" ><xsl:attribute name="name">{=HVP1iekL}Yoshishige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fukudome_1']/@name" ><xsl:attribute name="name">{=g2mr3QCM}Chikamasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_fukudome_2']/@name" ><xsl:attribute name="name">{=Hlkt9zR1}Ume</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_miyoshi_1']/@name" ><xsl:attribute name="name">{=2AJOuAzz}Nagayoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miyoshi_5']/@name" ><xsl:attribute name="name">{=diWjBHKp}Syoukou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miyoshi_4']/@name" ><xsl:attribute name="name">{=NPrwtYts}Tsuru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miyoshi']/@name" ><xsl:attribute name="name">{=Mxr5FYoa}Yoshitsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miyoshi_2']/@name" ><xsl:attribute name="name">{=JLomyVbr}Yoshikane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miyoshi_3']/@name" ><xsl:attribute name="name">{=75JZYLpa}Yoshishige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_miyoshi_1']/@name" ><xsl:attribute name="name">{=6gzf2OX9}Azusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sogo_1']/@name" ><xsl:attribute name="name">{=4jgyfZ85}Kazumasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_sogo_2']/@name" ><xsl:attribute name="name">{=4MZmJxE6}Komyo-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sogo']/@name" ><xsl:attribute name="name">{=uu3PRYD5}Masayasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sogo_1']/@name" ><xsl:attribute name="name">{=HxfQ7WNA}Satsuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sogo_2']/@name" ><xsl:attribute name="name">{=GLB0eZon}Masayuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sogo_3']/@name" ><xsl:attribute name="name">{=nKh0IYa0}Mayu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sogo_4']/@name" ><xsl:attribute name="name">{=dBBf1wOB}Kazuyuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sogo_5']/@name" ><xsl:attribute name="name">{=GiqQGwGA}Yamagiri</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shingai']/@name" ><xsl:attribute name="name">{=cjm2q36D}Douzen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shingai_1']/@name" ><xsl:attribute name="name">{=0vFKvTmm}Yachiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shingai_2']/@name" ><xsl:attribute name="name">{=2yPLLgtG}Sanenari</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shingai_3']/@name" ><xsl:attribute name="name">{=cOejVaQ2}Botan</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shingai_4']/@name" ><xsl:attribute name="name">{=zQfWhCEH}Renge</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shingai_5']/@name" ><xsl:attribute name="name">{=CjIwIpNQ}Ukon</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shingai_6']/@name" ><xsl:attribute name="name">{=0D5ublc2}Kaneyasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shingai_7']/@name" ><xsl:attribute name="name">{=Z7HNxyjm}Katashiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_onishi_1']/@name" ><xsl:attribute name="name">{=EPAOxYQz}Mototaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_onishi_2']/@name" ><xsl:attribute name="name">{=wx2ueWmc}Keizen-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi']/@name" ><xsl:attribute name="name">{=RvDxK05Y}Yoritake</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_1']/@name" ><xsl:attribute name="name">{=hM5I9P0H}Amaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_2']/@name" ><xsl:attribute name="name">{=rWLTD0VP}Shigemoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_3']/@name" ><xsl:attribute name="name">{=1DquGOk6}Haruka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_4']/@name" ><xsl:attribute name="name">{=IAlJOXYB}Yoriharu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_5']/@name" ><xsl:attribute name="name">{=yHGYnv7J}Tochi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_6']/@name" ><xsl:attribute name="name">{=nTvvBSyL}Yorikane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_7']/@name" ><xsl:attribute name="name">{=SQk4kSuU}Yorinobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_8']/@name" ><xsl:attribute name="name">{=MuaWnIVG}Mototake</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_9']/@name" ><xsl:attribute name="name">{=oeXBYpPO}Suzuran</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_10']/@name" ><xsl:attribute name="name">{=vufFgWYR}Sadatake</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onishi_11']/@name" ><xsl:attribute name="name">{=CoZaJNAY}Hamagiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ashina']/@name" ><xsl:attribute name="name">{=khx3Vgh8}Morioki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ashina_1']/@name" ><xsl:attribute name="name">{=mzCn8ZC7}Hiko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ashina_2']/@name" ><xsl:attribute name="name">{=sdzqsV1G}Moriuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ashina_3']/@name" ><xsl:attribute name="name">{=liJQwhE3}Yae</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ashina_4']/@name" ><xsl:attribute name="name">{=QkJaEi3K}Yuzu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_inawashiro']/@name" ><xsl:attribute name="name">{=YwGkSfbK}Morikuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_inawashiro_1']/@name" ><xsl:attribute name="name">{=kDG4hH19}Matsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_inawashiro_2']/@name" ><xsl:attribute name="name">{=7iNle8U9}Moritane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_inawashiro_3']/@name" ><xsl:attribute name="name">{=scnJL5kL}Munekuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_inawashiro_4']/@name" ><xsl:attribute name="name">{=9wTMtQuw}Moriaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saze']/@name" ><xsl:attribute name="name">{=uSZ3ktlG}Tanetsune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saze_1']/@name" ><xsl:attribute name="name">{=eKVl7rFn}Ai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saze_2']/@name" ><xsl:attribute name="name">{=E8H6JIrN}Tsunenori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saze_3']/@name" ><xsl:attribute name="name">{=4Wvo7FV1}Tose</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saze_4']/@name" ><xsl:attribute name="name">{=Cu1xPRNB}Morimitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saze_5']/@name" ><xsl:attribute name="name">{=IWEJ4mrY}Kine</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_saze_6']/@name" ><xsl:attribute name="name">{=kJATuUtQ}Tsunehide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsumoto']/@name" ><xsl:attribute name="name">{=PBI1pb9J}Ujisuke</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsumoto_1']/@name" ><xsl:attribute name="name">{=VtEfOh9T}Hama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_matsumoto_2']/@name" ><xsl:attribute name="name">{=wnmhSjVG}Yukisuke</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaido']/@name" ><xsl:attribute name="name">{=9WmlolIC}Moriyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaido_1']/@name" ><xsl:attribute name="name">{=foAJh4Aw}Onami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaido_2']/@name" ><xsl:attribute name="name">{=4gtrnix8}Moritaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_soma']/@name" ><xsl:attribute name="name">{=CrgYCr35}Moritane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_soma_1']/@name" ><xsl:attribute name="name">{=ppxVSFKS}Kake</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_soma_2']/@name" ><xsl:attribute name="name">{=CkTKok6g}Yoshitane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_soma_3']/@name" ><xsl:attribute name="name">{=l7TOWvmc}Takatane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_soma_4']/@name" ><xsl:attribute name="name">{=YwuGBeax}Satotane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_soma_5']/@name" ><xsl:attribute name="name">{=nci1JssK}Haru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nihonmatsu']/@name" ><xsl:attribute name="name">{=BGJzNDaJ}Yoshikuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nihonmatsu_1']/@name" ><xsl:attribute name="name">{=1NJGIP9x}Aki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nihonmatsu_2']/@name" ><xsl:attribute name="name">{=4zIz7SLR}Yoshitsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tamura']/@name" ><xsl:attribute name="name">{=nlu9kbj8}Takaaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tamura_1']/@name" ><xsl:attribute name="name">{=HByndZnP}Aki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tamura_2']/@name" ><xsl:attribute name="name">{=sxbLtOpV}Kiyoaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tamura_3']/@name" ><xsl:attribute name="name">{=aZssFvBr}Kake</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tamura_4']/@name" ><xsl:attribute name="name">{=DuxfRUZv}Mego</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tamura_5']/@name" ><xsl:attribute name="name">{=oEJsVsvL}Ujiaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okada']/@name" ><xsl:attribute name="name">{=AabIiWIA}Shigetane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okada_1']/@name" ><xsl:attribute name="name">{=o5Zq7Oek}Kai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_okada_2']/@name" ><xsl:attribute name="name">{=MCup3o6i}Yoshitane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_okada_3']/@name" ><xsl:attribute name="name">{=yi11OrT2}Myoukei-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okada_4']/@name" ><xsl:attribute name="name">{=nMadfoql}Naotane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okada_5']/@name" ><xsl:attribute name="name">{=fELklkpF}Tanekage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okada_6']/@name" ><xsl:attribute name="name">{=AhCQLCtb}Kiyotane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okada_7']/@name" ><xsl:attribute name="name">{=nLNPP20E}Tanetsura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okada_8']/@name" ><xsl:attribute name="name">{=UVX0OxFg}Ise</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okada_9']/@name" ><xsl:attribute name="name">{=EB3nmSxp}Tanenobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_okada_10']/@name" ><xsl:attribute name="name">{=PIfaqh7Q}Tanekane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_date']/@name" ><xsl:attribute name="name">{=3Pn5oEfx}Terumune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_date_1']/@name" ><xsl:attribute name="name">{=EDAnoqXI}Yoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_date_2']/@name" ><xsl:attribute name="name">{=KAHCFSfY}Harumune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_date_3']/@name" ><xsl:attribute name="name">{=0JKuKUGj}Kubo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_date_4']/@name" ><xsl:attribute name="name">{=23ZArAMO}Tanemune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_date_5']/@name" ><xsl:attribute name="name">{=BX6Yp0vZ}Taishin-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_date_6']/@name" ><xsl:attribute name="name">{=5UBPnUHd}Masamune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_date_7']/@name" ><xsl:attribute name="name">{=HgsPH3W5}Sanemoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_date_8']/@name" ><xsl:attribute name="name">{=TGJrgoXP}Kyousei-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_date_9']/@name" ><xsl:attribute name="name">{=5uYt8kLx}Shigezane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_katakura']/@name" ><xsl:attribute name="name">{=ROpC8P2s}Shigetsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_katakura_1']/@name" ><xsl:attribute name="name">{=w4XrKYdu}Kageshige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_katakura_2']/@name" ><xsl:attribute name="name">{=MlE07cvv}Naoko</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_katakura_3']/@name" ><xsl:attribute name="name">{=xNmZREFs}Kita</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_katakura_4']/@name" ><xsl:attribute name="name">{=5M0NN2yN}Kagetsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oniniwa']/@name" ><xsl:attribute name="name">{=faonKywA}Yoshinao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oniniwa_1']/@name" ><xsl:attribute name="name">{=G8NxnJE5}Taki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oniniwa_2']/@name" ><xsl:attribute name="name">{=C9MEAEGI}Tsunamoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oniniwa_3']/@name" ><xsl:attribute name="name">{=tLDDSJ4h}Sagami</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oniniwa_4']/@name" ><xsl:attribute name="name">{=6syqEkxm}Yasumoto</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_watari']/@name" ><xsl:attribute name="name">{=3fLCijjk}Motomune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_watari_1']/@name" ><xsl:attribute name="name">{=ASQ0gZto}Gekkou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_watari_2']/@name" ><xsl:attribute name="name">{=JZFYlzYb}Shigemune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_watari_3']/@name" ><xsl:attribute name="name">{=chvnuxQs}Yui</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_osaki']/@name" ><xsl:attribute name="name">{=CS8KPrQ8}Yoshitaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_osaki_1']/@name" ><xsl:attribute name="name">{=hFIaafxw}Yoshinao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_osaki_2']/@name" ><xsl:attribute name="name">{=yKztqf7Y}Tani</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_osaki_3']/@name" ><xsl:attribute name="name">{=PdMyVeC2}Toshiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasai']/@name" ><xsl:attribute name="name">{=GfI6uQA0}Harunobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasai_1']/@name" ><xsl:attribute name="name">{=V03JK8Wj}Toku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasai_2']/@name" ><xsl:attribute name="name">{=4enjcrq2}Kiyotaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kasai_3']/@name" ><xsl:attribute name="name">{=uLgRyxxy}Nobuhide</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_iwaki']/@name" ><xsl:attribute name="name">{=qyv1DVLK}Chikataka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_iwaki_1']/@name" ><xsl:attribute name="name">{=zS1xCtvl}Keiju-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_iwaki_2']/@name" ><xsl:attribute name="name">{=A91ldYIn}Shigetaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_iwaki_3']/@name" ><xsl:attribute name="name">{=OMoDuAqu}Kubo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_iwaki_4']/@name" ><xsl:attribute name="name">{=uGlEqEJX}Tsunetaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_iwaki_5']/@name" ><xsl:attribute name="name">{=NpV12vkH}Takatoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_iwaki_6']/@name" ><xsl:attribute name="name">{=rg6sw1Q9}Keiju-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_iwaki_7']/@name" ><xsl:attribute name="name">{=JkZOorvD}Takamune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_iwaki_8']/@name" ><xsl:attribute name="name">{=uxzJmlwA}Tora</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_rusu']/@name" ><xsl:attribute name="name">{=2vUBdY6S}Masakage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_rusu_1']/@name" ><xsl:attribute name="name">{=bs10mHWo}Akimune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_rusu_2']/@name" ><xsl:attribute name="name">{=qLjgsdLd}Haru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mogami']/@name" ><xsl:attribute name="name">{=BabGjggN}Yoshimori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mogami_1']/@name" ><xsl:attribute name="name">{=hxOrAtOY}Renshin-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mogami_2']/@name" ><xsl:attribute name="name">{=EtRVL3Xg}Yoshiaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mogami_3']/@name" ><xsl:attribute name="name">{=4GWpCzJZ}Toshiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mogami_4']/@name" ><xsl:attribute name="name">{=AgF95oLC}Yoshitoki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_mogami_5']/@name" ><xsl:attribute name="name">{=XWlzkdNm}Mitsunao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tendo']/@name" ><xsl:attribute name="name">{=PHvwg0Xu}Yorisada</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tendo_1']/@name" ><xsl:attribute name="name">{=PF8gDLpE}Kikyou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tendo_2']/@name" ><xsl:attribute name="name">{=JjgMoz43}Kaede</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tendo_3']/@name" ><xsl:attribute name="name">{=9ipPC2rK}Yorizumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tendo_4']/@name" ><xsl:attribute name="name">{=dUHmrYee}Yorikage</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ujiie']/@name" ><xsl:attribute name="name">{=6AupeJ2N}Morimune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ujiie_1']/@name" ><xsl:attribute name="name">{=tY6vS3gw}Satsuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ujiie_2']/@name" ><xsl:attribute name="name">{=KqISOYEY}Akimune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nobesawa']/@name" ><xsl:attribute name="name">{=ZbVonqWL}Mitsunobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nobesawa_1']/@name" ><xsl:attribute name="name">{=D0DDSMQY}Yone</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nobesawa_2']/@name" ><xsl:attribute name="name">{=gyhJohjp}Mitsuaki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tateoka']/@name" ><xsl:attribute name="name">{=mWkIbjPO}Yoshikuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tateoka_1']/@name" ><xsl:attribute name="name">{=Txz2u8Oq}Ama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tateoka_2']/@name" ><xsl:attribute name="name">{=a2OoRcJh}Mitsushige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tateoka_3']/@name" ><xsl:attribute name="name">{=vktTGyQq}Mitsuhiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_daihoji']/@name" ><xsl:attribute name="name">{=XUP0oREf}Yoshimasu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_daihoji_1']/@name" ><xsl:attribute name="name">{=jg1L0wFo}One</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_daihoji_2']/@name" ><xsl:attribute name="name">{=p4t1iXm5}Yoshiuji</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_daihoji_3']/@name" ><xsl:attribute name="name">{=8hFeGd0I}Yumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_daihoji_4']/@name" ><xsl:attribute name="name">{=RhHRQkPQ}Yoshioki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onodera']/@name" ><xsl:attribute name="name">{=M12NsVpR}Kagemichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onodera_1']/@name" ><xsl:attribute name="name">{=WkEGfvdg}Sen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onodera_2']/@name" ><xsl:attribute name="name">{=62tdkvpy}Mitsumichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onodera_3']/@name" ><xsl:attribute name="name">{=VgE08XCk}Yoshimichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_onodera_4']/@name" ><xsl:attribute name="name">{=MjQRacs8}Yasumichi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakenobe']/@name" ><xsl:attribute name="name">{=cYZFWbZM}Sadatsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakenobe_1']/@name" ><xsl:attribute name="name">{=FEk7Sghh}Hana</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_sakenobe_2']/@name" ><xsl:attribute name="name">{=iMBlTpJj}Hidetsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaho']/@name" ><xsl:attribute name="name">{=WlbkIU1a}Kiyohisa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaho_1']/@name" ><xsl:attribute name="name">{=NvZMn1nx}Hagi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaho_2']/@name" ><xsl:attribute name="name">{=9NoCTl9V}Kiyonaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaho_3']/@name" ><xsl:attribute name="name">{=6VMRRxMG}Take</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaho_4']/@name" ><xsl:attribute name="name">{=bxPIgkEG}Shigekiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaho_5']/@name" ><xsl:attribute name="name">{=EI4GudVP}Haru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nikaho_6']/@name" ><xsl:attribute name="name">{=l1FlQE5M}Chiyo</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ando']/@name" ><xsl:attribute name="name">{=bLbHwsOu}Chikasue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ando_1']/@name" ><xsl:attribute name="name">{=2lCIr4Yo}Ume</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ando_2']/@name" ><xsl:attribute name="name">{=V0yNJaSo}Kiyosue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_ando_3']/@name" ><xsl:attribute name="name">{=KLD5OGKr}Mitsu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ando_4']/@name" ><xsl:attribute name="name">{=Nn83RWCj}Narisue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ando_5']/@name" ><xsl:attribute name="name">{=CuZoMuTC}Shigesue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ando_6']/@name" ><xsl:attribute name="name">{=MnxZWCfr}Fusa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_ando_7']/@name" ><xsl:attribute name="name">{=UP1GXVUv}Michisue</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asari']/@name" ><xsl:attribute name="name">{=ghllwrCJ}Katsuyori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asari_1']/@name" ><xsl:attribute name="name">{=PZT6X6Nv}Mina</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asari_2']/@name" ><xsl:attribute name="name">{=EhjiWov4}Yorihira</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asari_3']/@name" ><xsl:attribute name="name">{=J4YAWqUc}Yorihirio</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_kakizaki']/@name" ><xsl:attribute name="name">{=Y4g7oumw}Suehiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_kakizaki_1']/@name" ><xsl:attribute name="name">{=AfDpOut5}Awa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_kakizaki_2']/@name" ><xsl:attribute name="name">{=iLroIUcH}Yoshihiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_kakizaki_3']/@name" ><xsl:attribute name="name">{=hStRHmEI}Mai</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_kakizaki_4']/@name" ><xsl:attribute name="name">{=GsSSWLlB}Sadahiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_kakizaki_5']/@name" ><xsl:attribute name="name">{=NYdIhl32}Nakahiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_kakizaki_6']/@name" ><xsl:attribute name="name">{=xxpsHzns}Morihiro</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_kakizaki_7']/@name" ><xsl:attribute name="name">{=5cfM2Wsd}Sen</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_2_kakizaki_8']/@name" ><xsl:attribute name="name">{=xzgrBlXk}Kou</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tozawa']/@name" ><xsl:attribute name="name">{=kmuEpByR}Michimori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tozawa_1']/@name" ><xsl:attribute name="name">{=ZPBJZyhY}Kiku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tozawa_2']/@name" ><xsl:attribute name="name">{=97vWqS1S}Morishige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_tozawa_3']/@name" ><xsl:attribute name="name">{=97vWqS1S}Morishige</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanbu']/@name" ><xsl:attribute name="name">{=qDo4xRn3}Harumasa</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanbu_1']/@name" ><xsl:attribute name="name">{=kD2IsTSN}Tsuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanbu_2']/@name" ><xsl:attribute name="name">{=4HJGGKQV}Nobunao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_nanbu_3']/@name" ><xsl:attribute name="name">{=oG7Xj5F1}Maru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shichinohe']/@name" ><xsl:attribute name="name">{=sD4FqEXl}Naokuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shichinohe_1']/@name" ><xsl:attribute name="name">{=4fsMSmDZ}Tsuru</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shichinohe_2']/@name" ><xsl:attribute name="name">{=DjV342Vx}Iekuni</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shichinohe_3']/@name" ><xsl:attribute name="name">{=L0wrNKVa}Ume</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hachinohe']/@name" ><xsl:attribute name="name">{=50jyluRi}Masayoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hachinohe_1']/@name" ><xsl:attribute name="name">{=ly1rOf4V}Toki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_hachinohe_2']/@name" ><xsl:attribute name="name">{=IaI3rd8b}Naoyoshi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_konohe']/@name" ><xsl:attribute name="name">{=U2fcoM3V}Masazane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_konohe_1']/@name" ><xsl:attribute name="name">{=OnWob7FY}Kei</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_konohe_2']/@name" ><xsl:attribute name="name">{=ybA8C3Pn}Nobunaka</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_konohe_3']/@name" ><xsl:attribute name="name">{=F44DRUrw}Yuki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_konohe_4']/@name" ><xsl:attribute name="name">{=TLlGQ3hu}Sanechika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_konohe_5']/@name" ><xsl:attribute name="name">{=SMHA0cYX}Shino</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kita']/@name" ><xsl:attribute name="name">{=ktJ3A4pU}Nobuchika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kita_1']/@name" ><xsl:attribute name="name">{=fCPVtYJi}Miki</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kita_2']/@name" ><xsl:attribute name="name">{=0JfNpzoT}Chikakazu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kita_3']/@name" ><xsl:attribute name="name">{=VrwnAg7Z}Sumire</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kita_4']/@name" ><xsl:attribute name="name">{=WOxNvejG}Hidechika</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_kita_5']/@name" ><xsl:attribute name="name">{=1Ms9l2Vr}Naotsugu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oura']/@name" ><xsl:attribute name="name">{=PBJm4EDg}Tamenobu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_oura_1']/@name" ><xsl:attribute name="name">{=Zd7dIZYX}Fuku</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_oura_2']/@name" ><xsl:attribute name="name">{=DxKKXmBo}Tamenori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_oura_3']/@name" ><xsl:attribute name="name">{=bCUAVf01}Sumi</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shiba']/@name" ><xsl:attribute name="name">{=Kn3UwNzn}Akizane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shiba_1']/@name" ><xsl:attribute name="name">{=KJxRs4Uz}Shima</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shiba_2']/@name" ><xsl:attribute name="name">{=Yhd8MKk4}Akinao</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shiba_3']/@name" ><xsl:attribute name="name">{=aXv9jGz0}Tsuya</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_shiba_4']/@name" ><xsl:attribute name="name">{=LQ4LfBqy}Akitane</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asonuma']/@name" ><xsl:attribute name="name">{=rQvhIKmk}Hirosato</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asonuma_1']/@name" ><xsl:attribute name="name">{=Loa2z2lg}Yone</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asonuma_2']/@name" ><xsl:attribute name="name">{=k0VTBlM1}Hironaga</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_asonuma_3']/@name" ><xsl:attribute name="name">{=N8YxPOIs}Hirotsuna</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_namioka']/@name" ><xsl:attribute name="name">{=PH6vnz2s}Tomokazu</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_namioka_1']/@name" ><xsl:attribute name="name">{=UUC5lMpW}Tama</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='dead_lord_1_namioka_2']/@name" ><xsl:attribute name="name">{=7VsSFAbY}Tomomune</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_namioka_3']/@name" ><xsl:attribute name="name">{=aCGR0aAJ}Joukou-in</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_namioka_4']/@name" ><xsl:attribute name="name">{=vi4WkU82}Akimura</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_namioka_5']/@name" ><xsl:attribute name="name">{=A3IWaEnQ}Akinori</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_namioka_6']/@name" ><xsl:attribute name="name">{=JcbZs4It}Kata</xsl:attribute></xsl:template>
  <xsl:template match="NPCCharacter[@id='lord_1_namioka_7']/@name" ><xsl:attribute name="name">{=ETIKKEst}Akitada</xsl:attribute></xsl:template>
</xsl:stylesheet>